package com.wallet.membership.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;

public class CpnBankInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cpn_bank_info
	 * @mbggenerated  Fri Sep 07 22:07:33 KST 2012
	 */
	protected String orderByClause;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cpn_bank_info
	 * @mbggenerated  Fri Sep 07 22:07:33 KST 2012
	 */
	protected boolean distinct;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cpn_bank_info
	 * @mbggenerated  Fri Sep 07 22:07:33 KST 2012
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cpn_bank_info
	 * @mbggenerated  Fri Sep 07 22:07:33 KST 2012
	 */
	public CpnBankInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cpn_bank_info
	 * @mbggenerated  Fri Sep 07 22:07:33 KST 2012
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cpn_bank_info
	 * @mbggenerated  Fri Sep 07 22:07:33 KST 2012
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cpn_bank_info
	 * @mbggenerated  Fri Sep 07 22:07:33 KST 2012
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cpn_bank_info
	 * @mbggenerated  Fri Sep 07 22:07:33 KST 2012
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cpn_bank_info
	 * @mbggenerated  Fri Sep 07 22:07:33 KST 2012
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cpn_bank_info
	 * @mbggenerated  Fri Sep 07 22:07:33 KST 2012
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cpn_bank_info
	 * @mbggenerated  Fri Sep 07 22:07:33 KST 2012
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cpn_bank_info
	 * @mbggenerated  Fri Sep 07 22:07:33 KST 2012
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cpn_bank_info
	 * @mbggenerated  Fri Sep 07 22:07:33 KST 2012
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cpn_bank_info
	 * @mbggenerated  Fri Sep 07 22:07:33 KST 2012
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	public void setRowsPerPage(Integer rowsPerPage) {
		this.rowsPerPage = rowsPerPage;
	}

	public Integer getRowsPerPage() {
		return rowsPerPage;
	}

	public void setStartIndex(Integer startIndex) {
		this.startIndex = startIndex;
	}

	public Integer getStartIndex() {
		return startIndex;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table cpn_bank_info
	 * @mbggenerated  Fri Sep 07 22:07:33 KST 2012
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andBankIdIsNull() {
			addCriterion("bank_id is null");
			return (Criteria) this;
		}

		public Criteria andBankIdIsNotNull() {
			addCriterion("bank_id is not null");
			return (Criteria) this;
		}

		public Criteria andBankIdEqualTo(String value) {
			addCriterion("bank_id =", value, "bankId");
			return (Criteria) this;
		}

		public Criteria andBankIdNotEqualTo(String value) {
			addCriterion("bank_id <>", value, "bankId");
			return (Criteria) this;
		}

		public Criteria andBankIdGreaterThan(String value) {
			addCriterion("bank_id >", value, "bankId");
			return (Criteria) this;
		}

		public Criteria andBankIdGreaterThanOrEqualTo(String value) {
			addCriterion("bank_id >=", value, "bankId");
			return (Criteria) this;
		}

		public Criteria andBankIdLessThan(String value) {
			addCriterion("bank_id <", value, "bankId");
			return (Criteria) this;
		}

		public Criteria andBankIdLessThanOrEqualTo(String value) {
			addCriterion("bank_id <=", value, "bankId");
			return (Criteria) this;
		}

		public Criteria andBankIdLike(String value) {
			addCriterion("bank_id like", value, "bankId");
			return (Criteria) this;
		}

		public Criteria andBankIdNotLike(String value) {
			addCriterion("bank_id not like", value, "bankId");
			return (Criteria) this;
		}

		public Criteria andBankIdIn(List<String> values) {
			addCriterion("bank_id in", values, "bankId");
			return (Criteria) this;
		}

		public Criteria andBankIdNotIn(List<String> values) {
			addCriterion("bank_id not in", values, "bankId");
			return (Criteria) this;
		}

		public Criteria andBankIdBetween(String value1, String value2) {
			addCriterion("bank_id between", value1, value2, "bankId");
			return (Criteria) this;
		}

		public Criteria andBankIdNotBetween(String value1, String value2) {
			addCriterion("bank_id not between", value1, value2, "bankId");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andSvc1IsNull() {
			addCriterion("svc_1 is null");
			return (Criteria) this;
		}

		public Criteria andSvc1IsNotNull() {
			addCriterion("svc_1 is not null");
			return (Criteria) this;
		}

		public Criteria andSvc1EqualTo(String value) {
			addCriterion("svc_1 =", value, "svc1");
			return (Criteria) this;
		}

		public Criteria andSvc1NotEqualTo(String value) {
			addCriterion("svc_1 <>", value, "svc1");
			return (Criteria) this;
		}

		public Criteria andSvc1GreaterThan(String value) {
			addCriterion("svc_1 >", value, "svc1");
			return (Criteria) this;
		}

		public Criteria andSvc1GreaterThanOrEqualTo(String value) {
			addCriterion("svc_1 >=", value, "svc1");
			return (Criteria) this;
		}

		public Criteria andSvc1LessThan(String value) {
			addCriterion("svc_1 <", value, "svc1");
			return (Criteria) this;
		}

		public Criteria andSvc1LessThanOrEqualTo(String value) {
			addCriterion("svc_1 <=", value, "svc1");
			return (Criteria) this;
		}

		public Criteria andSvc1Like(String value) {
			addCriterion("svc_1 like", value, "svc1");
			return (Criteria) this;
		}

		public Criteria andSvc1NotLike(String value) {
			addCriterion("svc_1 not like", value, "svc1");
			return (Criteria) this;
		}

		public Criteria andSvc1In(List<String> values) {
			addCriterion("svc_1 in", values, "svc1");
			return (Criteria) this;
		}

		public Criteria andSvc1NotIn(List<String> values) {
			addCriterion("svc_1 not in", values, "svc1");
			return (Criteria) this;
		}

		public Criteria andSvc1Between(String value1, String value2) {
			addCriterion("svc_1 between", value1, value2, "svc1");
			return (Criteria) this;
		}

		public Criteria andSvc1NotBetween(String value1, String value2) {
			addCriterion("svc_1 not between", value1, value2, "svc1");
			return (Criteria) this;
		}

		public Criteria andSvc2IsNull() {
			addCriterion("svc_2 is null");
			return (Criteria) this;
		}

		public Criteria andSvc2IsNotNull() {
			addCriterion("svc_2 is not null");
			return (Criteria) this;
		}

		public Criteria andSvc2EqualTo(String value) {
			addCriterion("svc_2 =", value, "svc2");
			return (Criteria) this;
		}

		public Criteria andSvc2NotEqualTo(String value) {
			addCriterion("svc_2 <>", value, "svc2");
			return (Criteria) this;
		}

		public Criteria andSvc2GreaterThan(String value) {
			addCriterion("svc_2 >", value, "svc2");
			return (Criteria) this;
		}

		public Criteria andSvc2GreaterThanOrEqualTo(String value) {
			addCriterion("svc_2 >=", value, "svc2");
			return (Criteria) this;
		}

		public Criteria andSvc2LessThan(String value) {
			addCriterion("svc_2 <", value, "svc2");
			return (Criteria) this;
		}

		public Criteria andSvc2LessThanOrEqualTo(String value) {
			addCriterion("svc_2 <=", value, "svc2");
			return (Criteria) this;
		}

		public Criteria andSvc2Like(String value) {
			addCriterion("svc_2 like", value, "svc2");
			return (Criteria) this;
		}

		public Criteria andSvc2NotLike(String value) {
			addCriterion("svc_2 not like", value, "svc2");
			return (Criteria) this;
		}

		public Criteria andSvc2In(List<String> values) {
			addCriterion("svc_2 in", values, "svc2");
			return (Criteria) this;
		}

		public Criteria andSvc2NotIn(List<String> values) {
			addCriterion("svc_2 not in", values, "svc2");
			return (Criteria) this;
		}

		public Criteria andSvc2Between(String value1, String value2) {
			addCriterion("svc_2 between", value1, value2, "svc2");
			return (Criteria) this;
		}

		public Criteria andSvc2NotBetween(String value1, String value2) {
			addCriterion("svc_2 not between", value1, value2, "svc2");
			return (Criteria) this;
		}

		public Criteria andSvc3IsNull() {
			addCriterion("svc_3 is null");
			return (Criteria) this;
		}

		public Criteria andSvc3IsNotNull() {
			addCriterion("svc_3 is not null");
			return (Criteria) this;
		}

		public Criteria andSvc3EqualTo(String value) {
			addCriterion("svc_3 =", value, "svc3");
			return (Criteria) this;
		}

		public Criteria andSvc3NotEqualTo(String value) {
			addCriterion("svc_3 <>", value, "svc3");
			return (Criteria) this;
		}

		public Criteria andSvc3GreaterThan(String value) {
			addCriterion("svc_3 >", value, "svc3");
			return (Criteria) this;
		}

		public Criteria andSvc3GreaterThanOrEqualTo(String value) {
			addCriterion("svc_3 >=", value, "svc3");
			return (Criteria) this;
		}

		public Criteria andSvc3LessThan(String value) {
			addCriterion("svc_3 <", value, "svc3");
			return (Criteria) this;
		}

		public Criteria andSvc3LessThanOrEqualTo(String value) {
			addCriterion("svc_3 <=", value, "svc3");
			return (Criteria) this;
		}

		public Criteria andSvc3Like(String value) {
			addCriterion("svc_3 like", value, "svc3");
			return (Criteria) this;
		}

		public Criteria andSvc3NotLike(String value) {
			addCriterion("svc_3 not like", value, "svc3");
			return (Criteria) this;
		}

		public Criteria andSvc3In(List<String> values) {
			addCriterion("svc_3 in", values, "svc3");
			return (Criteria) this;
		}

		public Criteria andSvc3NotIn(List<String> values) {
			addCriterion("svc_3 not in", values, "svc3");
			return (Criteria) this;
		}

		public Criteria andSvc3Between(String value1, String value2) {
			addCriterion("svc_3 between", value1, value2, "svc3");
			return (Criteria) this;
		}

		public Criteria andSvc3NotBetween(String value1, String value2) {
			addCriterion("svc_3 not between", value1, value2, "svc3");
			return (Criteria) this;
		}

		public Criteria andSvc4IsNull() {
			addCriterion("svc_4 is null");
			return (Criteria) this;
		}

		public Criteria andSvc4IsNotNull() {
			addCriterion("svc_4 is not null");
			return (Criteria) this;
		}

		public Criteria andSvc4EqualTo(String value) {
			addCriterion("svc_4 =", value, "svc4");
			return (Criteria) this;
		}

		public Criteria andSvc4NotEqualTo(String value) {
			addCriterion("svc_4 <>", value, "svc4");
			return (Criteria) this;
		}

		public Criteria andSvc4GreaterThan(String value) {
			addCriterion("svc_4 >", value, "svc4");
			return (Criteria) this;
		}

		public Criteria andSvc4GreaterThanOrEqualTo(String value) {
			addCriterion("svc_4 >=", value, "svc4");
			return (Criteria) this;
		}

		public Criteria andSvc4LessThan(String value) {
			addCriterion("svc_4 <", value, "svc4");
			return (Criteria) this;
		}

		public Criteria andSvc4LessThanOrEqualTo(String value) {
			addCriterion("svc_4 <=", value, "svc4");
			return (Criteria) this;
		}

		public Criteria andSvc4Like(String value) {
			addCriterion("svc_4 like", value, "svc4");
			return (Criteria) this;
		}

		public Criteria andSvc4NotLike(String value) {
			addCriterion("svc_4 not like", value, "svc4");
			return (Criteria) this;
		}

		public Criteria andSvc4In(List<String> values) {
			addCriterion("svc_4 in", values, "svc4");
			return (Criteria) this;
		}

		public Criteria andSvc4NotIn(List<String> values) {
			addCriterion("svc_4 not in", values, "svc4");
			return (Criteria) this;
		}

		public Criteria andSvc4Between(String value1, String value2) {
			addCriterion("svc_4 between", value1, value2, "svc4");
			return (Criteria) this;
		}

		public Criteria andSvc4NotBetween(String value1, String value2) {
			addCriterion("svc_4 not between", value1, value2, "svc4");
			return (Criteria) this;
		}

		public Criteria andBusinessNoIsNull() {
			addCriterion("BUSINESS_NO is null");
			return (Criteria) this;
		}

		public Criteria andBusinessNoIsNotNull() {
			addCriterion("BUSINESS_NO is not null");
			return (Criteria) this;
		}

		public Criteria andBusinessNoEqualTo(String value) {
			addCriterion("BUSINESS_NO =", value, "businessNo");
			return (Criteria) this;
		}

		public Criteria andBusinessNoNotEqualTo(String value) {
			addCriterion("BUSINESS_NO <>", value, "businessNo");
			return (Criteria) this;
		}

		public Criteria andBusinessNoGreaterThan(String value) {
			addCriterion("BUSINESS_NO >", value, "businessNo");
			return (Criteria) this;
		}

		public Criteria andBusinessNoGreaterThanOrEqualTo(String value) {
			addCriterion("BUSINESS_NO >=", value, "businessNo");
			return (Criteria) this;
		}

		public Criteria andBusinessNoLessThan(String value) {
			addCriterion("BUSINESS_NO <", value, "businessNo");
			return (Criteria) this;
		}

		public Criteria andBusinessNoLessThanOrEqualTo(String value) {
			addCriterion("BUSINESS_NO <=", value, "businessNo");
			return (Criteria) this;
		}

		public Criteria andBusinessNoLike(String value) {
			addCriterion("BUSINESS_NO like", value, "businessNo");
			return (Criteria) this;
		}

		public Criteria andBusinessNoNotLike(String value) {
			addCriterion("BUSINESS_NO not like", value, "businessNo");
			return (Criteria) this;
		}

		public Criteria andBusinessNoIn(List<String> values) {
			addCriterion("BUSINESS_NO in", values, "businessNo");
			return (Criteria) this;
		}

		public Criteria andBusinessNoNotIn(List<String> values) {
			addCriterion("BUSINESS_NO not in", values, "businessNo");
			return (Criteria) this;
		}

		public Criteria andBusinessNoBetween(String value1, String value2) {
			addCriterion("BUSINESS_NO between", value1, value2, "businessNo");
			return (Criteria) this;
		}

		public Criteria andBusinessNoNotBetween(String value1, String value2) {
			addCriterion("BUSINESS_NO not between", value1, value2,
					"businessNo");
			return (Criteria) this;
		}

		public Criteria andZipcodeIsNull() {
			addCriterion("ZIPCODE is null");
			return (Criteria) this;
		}

		public Criteria andZipcodeIsNotNull() {
			addCriterion("ZIPCODE is not null");
			return (Criteria) this;
		}

		public Criteria andZipcodeEqualTo(String value) {
			addCriterion("ZIPCODE =", value, "zipcode");
			return (Criteria) this;
		}

		public Criteria andZipcodeNotEqualTo(String value) {
			addCriterion("ZIPCODE <>", value, "zipcode");
			return (Criteria) this;
		}

		public Criteria andZipcodeGreaterThan(String value) {
			addCriterion("ZIPCODE >", value, "zipcode");
			return (Criteria) this;
		}

		public Criteria andZipcodeGreaterThanOrEqualTo(String value) {
			addCriterion("ZIPCODE >=", value, "zipcode");
			return (Criteria) this;
		}

		public Criteria andZipcodeLessThan(String value) {
			addCriterion("ZIPCODE <", value, "zipcode");
			return (Criteria) this;
		}

		public Criteria andZipcodeLessThanOrEqualTo(String value) {
			addCriterion("ZIPCODE <=", value, "zipcode");
			return (Criteria) this;
		}

		public Criteria andZipcodeLike(String value) {
			addCriterion("ZIPCODE like", value, "zipcode");
			return (Criteria) this;
		}

		public Criteria andZipcodeNotLike(String value) {
			addCriterion("ZIPCODE not like", value, "zipcode");
			return (Criteria) this;
		}

		public Criteria andZipcodeIn(List<String> values) {
			addCriterion("ZIPCODE in", values, "zipcode");
			return (Criteria) this;
		}

		public Criteria andZipcodeNotIn(List<String> values) {
			addCriterion("ZIPCODE not in", values, "zipcode");
			return (Criteria) this;
		}

		public Criteria andZipcodeBetween(String value1, String value2) {
			addCriterion("ZIPCODE between", value1, value2, "zipcode");
			return (Criteria) this;
		}

		public Criteria andZipcodeNotBetween(String value1, String value2) {
			addCriterion("ZIPCODE not between", value1, value2, "zipcode");
			return (Criteria) this;
		}

		public Criteria andAddrIsNull() {
			addCriterion("ADDR is null");
			return (Criteria) this;
		}

		public Criteria andAddrIsNotNull() {
			addCriterion("ADDR is not null");
			return (Criteria) this;
		}

		public Criteria andAddrEqualTo(String value) {
			addCriterion("ADDR =", value, "addr");
			return (Criteria) this;
		}

		public Criteria andAddrNotEqualTo(String value) {
			addCriterion("ADDR <>", value, "addr");
			return (Criteria) this;
		}

		public Criteria andAddrGreaterThan(String value) {
			addCriterion("ADDR >", value, "addr");
			return (Criteria) this;
		}

		public Criteria andAddrGreaterThanOrEqualTo(String value) {
			addCriterion("ADDR >=", value, "addr");
			return (Criteria) this;
		}

		public Criteria andAddrLessThan(String value) {
			addCriterion("ADDR <", value, "addr");
			return (Criteria) this;
		}

		public Criteria andAddrLessThanOrEqualTo(String value) {
			addCriterion("ADDR <=", value, "addr");
			return (Criteria) this;
		}

		public Criteria andAddrLike(String value) {
			addCriterion("ADDR like", value, "addr");
			return (Criteria) this;
		}

		public Criteria andAddrNotLike(String value) {
			addCriterion("ADDR not like", value, "addr");
			return (Criteria) this;
		}

		public Criteria andAddrIn(List<String> values) {
			addCriterion("ADDR in", values, "addr");
			return (Criteria) this;
		}

		public Criteria andAddrNotIn(List<String> values) {
			addCriterion("ADDR not in", values, "addr");
			return (Criteria) this;
		}

		public Criteria andAddrBetween(String value1, String value2) {
			addCriterion("ADDR between", value1, value2, "addr");
			return (Criteria) this;
		}

		public Criteria andAddrNotBetween(String value1, String value2) {
			addCriterion("ADDR not between", value1, value2, "addr");
			return (Criteria) this;
		}

		public Criteria andAddrDetailIsNull() {
			addCriterion("ADDR_DETAIL is null");
			return (Criteria) this;
		}

		public Criteria andAddrDetailIsNotNull() {
			addCriterion("ADDR_DETAIL is not null");
			return (Criteria) this;
		}

		public Criteria andAddrDetailEqualTo(String value) {
			addCriterion("ADDR_DETAIL =", value, "addrDetail");
			return (Criteria) this;
		}

		public Criteria andAddrDetailNotEqualTo(String value) {
			addCriterion("ADDR_DETAIL <>", value, "addrDetail");
			return (Criteria) this;
		}

		public Criteria andAddrDetailGreaterThan(String value) {
			addCriterion("ADDR_DETAIL >", value, "addrDetail");
			return (Criteria) this;
		}

		public Criteria andAddrDetailGreaterThanOrEqualTo(String value) {
			addCriterion("ADDR_DETAIL >=", value, "addrDetail");
			return (Criteria) this;
		}

		public Criteria andAddrDetailLessThan(String value) {
			addCriterion("ADDR_DETAIL <", value, "addrDetail");
			return (Criteria) this;
		}

		public Criteria andAddrDetailLessThanOrEqualTo(String value) {
			addCriterion("ADDR_DETAIL <=", value, "addrDetail");
			return (Criteria) this;
		}

		public Criteria andAddrDetailLike(String value) {
			addCriterion("ADDR_DETAIL like", value, "addrDetail");
			return (Criteria) this;
		}

		public Criteria andAddrDetailNotLike(String value) {
			addCriterion("ADDR_DETAIL not like", value, "addrDetail");
			return (Criteria) this;
		}

		public Criteria andAddrDetailIn(List<String> values) {
			addCriterion("ADDR_DETAIL in", values, "addrDetail");
			return (Criteria) this;
		}

		public Criteria andAddrDetailNotIn(List<String> values) {
			addCriterion("ADDR_DETAIL not in", values, "addrDetail");
			return (Criteria) this;
		}

		public Criteria andAddrDetailBetween(String value1, String value2) {
			addCriterion("ADDR_DETAIL between", value1, value2, "addrDetail");
			return (Criteria) this;
		}

		public Criteria andAddrDetailNotBetween(String value1, String value2) {
			addCriterion("ADDR_DETAIL not between", value1, value2,
					"addrDetail");
			return (Criteria) this;
		}

		public Criteria andMainNumberIsNull() {
			addCriterion("MAIN_NUMBER is null");
			return (Criteria) this;
		}

		public Criteria andMainNumberIsNotNull() {
			addCriterion("MAIN_NUMBER is not null");
			return (Criteria) this;
		}

		public Criteria andMainNumberEqualTo(String value) {
			addCriterion("MAIN_NUMBER =", value, "mainNumber");
			return (Criteria) this;
		}

		public Criteria andMainNumberNotEqualTo(String value) {
			addCriterion("MAIN_NUMBER <>", value, "mainNumber");
			return (Criteria) this;
		}

		public Criteria andMainNumberGreaterThan(String value) {
			addCriterion("MAIN_NUMBER >", value, "mainNumber");
			return (Criteria) this;
		}

		public Criteria andMainNumberGreaterThanOrEqualTo(String value) {
			addCriterion("MAIN_NUMBER >=", value, "mainNumber");
			return (Criteria) this;
		}

		public Criteria andMainNumberLessThan(String value) {
			addCriterion("MAIN_NUMBER <", value, "mainNumber");
			return (Criteria) this;
		}

		public Criteria andMainNumberLessThanOrEqualTo(String value) {
			addCriterion("MAIN_NUMBER <=", value, "mainNumber");
			return (Criteria) this;
		}

		public Criteria andMainNumberLike(String value) {
			addCriterion("MAIN_NUMBER like", value, "mainNumber");
			return (Criteria) this;
		}

		public Criteria andMainNumberNotLike(String value) {
			addCriterion("MAIN_NUMBER not like", value, "mainNumber");
			return (Criteria) this;
		}

		public Criteria andMainNumberIn(List<String> values) {
			addCriterion("MAIN_NUMBER in", values, "mainNumber");
			return (Criteria) this;
		}

		public Criteria andMainNumberNotIn(List<String> values) {
			addCriterion("MAIN_NUMBER not in", values, "mainNumber");
			return (Criteria) this;
		}

		public Criteria andMainNumberBetween(String value1, String value2) {
			addCriterion("MAIN_NUMBER between", value1, value2, "mainNumber");
			return (Criteria) this;
		}

		public Criteria andMainNumberNotBetween(String value1, String value2) {
			addCriterion("MAIN_NUMBER not between", value1, value2,
					"mainNumber");
			return (Criteria) this;
		}

		public Criteria andManagerNameIsNull() {
			addCriterion("MANAGER_NAME is null");
			return (Criteria) this;
		}

		public Criteria andManagerNameIsNotNull() {
			addCriterion("MANAGER_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andManagerNameEqualTo(String value) {
			addCriterion("MANAGER_NAME =", value, "managerName");
			return (Criteria) this;
		}

		public Criteria andManagerNameNotEqualTo(String value) {
			addCriterion("MANAGER_NAME <>", value, "managerName");
			return (Criteria) this;
		}

		public Criteria andManagerNameGreaterThan(String value) {
			addCriterion("MANAGER_NAME >", value, "managerName");
			return (Criteria) this;
		}

		public Criteria andManagerNameGreaterThanOrEqualTo(String value) {
			addCriterion("MANAGER_NAME >=", value, "managerName");
			return (Criteria) this;
		}

		public Criteria andManagerNameLessThan(String value) {
			addCriterion("MANAGER_NAME <", value, "managerName");
			return (Criteria) this;
		}

		public Criteria andManagerNameLessThanOrEqualTo(String value) {
			addCriterion("MANAGER_NAME <=", value, "managerName");
			return (Criteria) this;
		}

		public Criteria andManagerNameLike(String value) {
			addCriterion("MANAGER_NAME like", value, "managerName");
			return (Criteria) this;
		}

		public Criteria andManagerNameNotLike(String value) {
			addCriterion("MANAGER_NAME not like", value, "managerName");
			return (Criteria) this;
		}

		public Criteria andManagerNameIn(List<String> values) {
			addCriterion("MANAGER_NAME in", values, "managerName");
			return (Criteria) this;
		}

		public Criteria andManagerNameNotIn(List<String> values) {
			addCriterion("MANAGER_NAME not in", values, "managerName");
			return (Criteria) this;
		}

		public Criteria andManagerNameBetween(String value1, String value2) {
			addCriterion("MANAGER_NAME between", value1, value2, "managerName");
			return (Criteria) this;
		}

		public Criteria andManagerNameNotBetween(String value1, String value2) {
			addCriterion("MANAGER_NAME not between", value1, value2,
					"managerName");
			return (Criteria) this;
		}

		public Criteria andPhoneNoIsNull() {
			addCriterion("PHONE_NO is null");
			return (Criteria) this;
		}

		public Criteria andPhoneNoIsNotNull() {
			addCriterion("PHONE_NO is not null");
			return (Criteria) this;
		}

		public Criteria andPhoneNoEqualTo(String value) {
			addCriterion("PHONE_NO =", value, "phoneNo");
			return (Criteria) this;
		}

		public Criteria andPhoneNoNotEqualTo(String value) {
			addCriterion("PHONE_NO <>", value, "phoneNo");
			return (Criteria) this;
		}

		public Criteria andPhoneNoGreaterThan(String value) {
			addCriterion("PHONE_NO >", value, "phoneNo");
			return (Criteria) this;
		}

		public Criteria andPhoneNoGreaterThanOrEqualTo(String value) {
			addCriterion("PHONE_NO >=", value, "phoneNo");
			return (Criteria) this;
		}

		public Criteria andPhoneNoLessThan(String value) {
			addCriterion("PHONE_NO <", value, "phoneNo");
			return (Criteria) this;
		}

		public Criteria andPhoneNoLessThanOrEqualTo(String value) {
			addCriterion("PHONE_NO <=", value, "phoneNo");
			return (Criteria) this;
		}

		public Criteria andPhoneNoLike(String value) {
			addCriterion("PHONE_NO like", value, "phoneNo");
			return (Criteria) this;
		}

		public Criteria andPhoneNoNotLike(String value) {
			addCriterion("PHONE_NO not like", value, "phoneNo");
			return (Criteria) this;
		}

		public Criteria andPhoneNoIn(List<String> values) {
			addCriterion("PHONE_NO in", values, "phoneNo");
			return (Criteria) this;
		}

		public Criteria andPhoneNoNotIn(List<String> values) {
			addCriterion("PHONE_NO not in", values, "phoneNo");
			return (Criteria) this;
		}

		public Criteria andPhoneNoBetween(String value1, String value2) {
			addCriterion("PHONE_NO between", value1, value2, "phoneNo");
			return (Criteria) this;
		}

		public Criteria andPhoneNoNotBetween(String value1, String value2) {
			addCriterion("PHONE_NO not between", value1, value2, "phoneNo");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneIsNull() {
			addCriterion("MOBILE_PHONE is null");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneIsNotNull() {
			addCriterion("MOBILE_PHONE is not null");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneEqualTo(String value) {
			addCriterion("MOBILE_PHONE =", value, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneNotEqualTo(String value) {
			addCriterion("MOBILE_PHONE <>", value, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneGreaterThan(String value) {
			addCriterion("MOBILE_PHONE >", value, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneGreaterThanOrEqualTo(String value) {
			addCriterion("MOBILE_PHONE >=", value, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneLessThan(String value) {
			addCriterion("MOBILE_PHONE <", value, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneLessThanOrEqualTo(String value) {
			addCriterion("MOBILE_PHONE <=", value, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneLike(String value) {
			addCriterion("MOBILE_PHONE like", value, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneNotLike(String value) {
			addCriterion("MOBILE_PHONE not like", value, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneIn(List<String> values) {
			addCriterion("MOBILE_PHONE in", values, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneNotIn(List<String> values) {
			addCriterion("MOBILE_PHONE not in", values, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneBetween(String value1, String value2) {
			addCriterion("MOBILE_PHONE between", value1, value2, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneNotBetween(String value1, String value2) {
			addCriterion("MOBILE_PHONE not between", value1, value2,
					"mobilePhone");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("EMAIL is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("EMAIL is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("EMAIL =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("EMAIL <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("EMAIL >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("EMAIL >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("EMAIL <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("EMAIL <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("EMAIL like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("EMAIL not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("EMAIL in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("EMAIL not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("EMAIL between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("EMAIL not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andAllyStatIsNull() {
			addCriterion("ALLY_STAT is null");
			return (Criteria) this;
		}

		public Criteria andAllyStatIsNotNull() {
			addCriterion("ALLY_STAT is not null");
			return (Criteria) this;
		}

		public Criteria andAllyStatEqualTo(String value) {
			addCriterion("ALLY_STAT =", value, "allyStat");
			return (Criteria) this;
		}

		public Criteria andAllyStatNotEqualTo(String value) {
			addCriterion("ALLY_STAT <>", value, "allyStat");
			return (Criteria) this;
		}

		public Criteria andAllyStatGreaterThan(String value) {
			addCriterion("ALLY_STAT >", value, "allyStat");
			return (Criteria) this;
		}

		public Criteria andAllyStatGreaterThanOrEqualTo(String value) {
			addCriterion("ALLY_STAT >=", value, "allyStat");
			return (Criteria) this;
		}

		public Criteria andAllyStatLessThan(String value) {
			addCriterion("ALLY_STAT <", value, "allyStat");
			return (Criteria) this;
		}

		public Criteria andAllyStatLessThanOrEqualTo(String value) {
			addCriterion("ALLY_STAT <=", value, "allyStat");
			return (Criteria) this;
		}

		public Criteria andAllyStatLike(String value) {
			addCriterion("ALLY_STAT like", value, "allyStat");
			return (Criteria) this;
		}

		public Criteria andAllyStatNotLike(String value) {
			addCriterion("ALLY_STAT not like", value, "allyStat");
			return (Criteria) this;
		}

		public Criteria andAllyStatIn(List<String> values) {
			addCriterion("ALLY_STAT in", values, "allyStat");
			return (Criteria) this;
		}

		public Criteria andAllyStatNotIn(List<String> values) {
			addCriterion("ALLY_STAT not in", values, "allyStat");
			return (Criteria) this;
		}

		public Criteria andAllyStatBetween(String value1, String value2) {
			addCriterion("ALLY_STAT between", value1, value2, "allyStat");
			return (Criteria) this;
		}

		public Criteria andAllyStatNotBetween(String value1, String value2) {
			addCriterion("ALLY_STAT not between", value1, value2, "allyStat");
			return (Criteria) this;
		}

		public Criteria andRegUserIsNull() {
			addCriterion("REG_USER is null");
			return (Criteria) this;
		}

		public Criteria andRegUserIsNotNull() {
			addCriterion("REG_USER is not null");
			return (Criteria) this;
		}

		public Criteria andRegUserEqualTo(String value) {
			addCriterion("REG_USER =", value, "regUser");
			return (Criteria) this;
		}

		public Criteria andRegUserNotEqualTo(String value) {
			addCriterion("REG_USER <>", value, "regUser");
			return (Criteria) this;
		}

		public Criteria andRegUserGreaterThan(String value) {
			addCriterion("REG_USER >", value, "regUser");
			return (Criteria) this;
		}

		public Criteria andRegUserGreaterThanOrEqualTo(String value) {
			addCriterion("REG_USER >=", value, "regUser");
			return (Criteria) this;
		}

		public Criteria andRegUserLessThan(String value) {
			addCriterion("REG_USER <", value, "regUser");
			return (Criteria) this;
		}

		public Criteria andRegUserLessThanOrEqualTo(String value) {
			addCriterion("REG_USER <=", value, "regUser");
			return (Criteria) this;
		}

		public Criteria andRegUserLike(String value) {
			addCriterion("REG_USER like", value, "regUser");
			return (Criteria) this;
		}

		public Criteria andRegUserNotLike(String value) {
			addCriterion("REG_USER not like", value, "regUser");
			return (Criteria) this;
		}

		public Criteria andRegUserIn(List<String> values) {
			addCriterion("REG_USER in", values, "regUser");
			return (Criteria) this;
		}

		public Criteria andRegUserNotIn(List<String> values) {
			addCriterion("REG_USER not in", values, "regUser");
			return (Criteria) this;
		}

		public Criteria andRegUserBetween(String value1, String value2) {
			addCriterion("REG_USER between", value1, value2, "regUser");
			return (Criteria) this;
		}

		public Criteria andRegUserNotBetween(String value1, String value2) {
			addCriterion("REG_USER not between", value1, value2, "regUser");
			return (Criteria) this;
		}

		public Criteria andRegDtmIsNull() {
			addCriterion("REG_DTM is null");
			return (Criteria) this;
		}

		public Criteria andRegDtmIsNotNull() {
			addCriterion("REG_DTM is not null");
			return (Criteria) this;
		}

		public Criteria andRegDtmEqualTo(Date value) {
			addCriterion("REG_DTM =", value, "regDtm");
			return (Criteria) this;
		}

		public Criteria andRegDtmNotEqualTo(Date value) {
			addCriterion("REG_DTM <>", value, "regDtm");
			return (Criteria) this;
		}

		public Criteria andRegDtmGreaterThan(Date value) {
			addCriterion("REG_DTM >", value, "regDtm");
			return (Criteria) this;
		}

		public Criteria andRegDtmGreaterThanOrEqualTo(Date value) {
			addCriterion("REG_DTM >=", value, "regDtm");
			return (Criteria) this;
		}

		public Criteria andRegDtmLessThan(Date value) {
			addCriterion("REG_DTM <", value, "regDtm");
			return (Criteria) this;
		}

		public Criteria andRegDtmLessThanOrEqualTo(Date value) {
			addCriterion("REG_DTM <=", value, "regDtm");
			return (Criteria) this;
		}

		public Criteria andRegDtmIn(List<Date> values) {
			addCriterion("REG_DTM in", values, "regDtm");
			return (Criteria) this;
		}

		public Criteria andRegDtmNotIn(List<Date> values) {
			addCriterion("REG_DTM not in", values, "regDtm");
			return (Criteria) this;
		}

		public Criteria andRegDtmBetween(Date value1, Date value2) {
			addCriterion("REG_DTM between", value1, value2, "regDtm");
			return (Criteria) this;
		}

		public Criteria andRegDtmNotBetween(Date value1, Date value2) {
			addCriterion("REG_DTM not between", value1, value2, "regDtm");
			return (Criteria) this;
		}

		public Criteria andChgUserIsNull() {
			addCriterion("CHG_USER is null");
			return (Criteria) this;
		}

		public Criteria andChgUserIsNotNull() {
			addCriterion("CHG_USER is not null");
			return (Criteria) this;
		}

		public Criteria andChgUserEqualTo(String value) {
			addCriterion("CHG_USER =", value, "chgUser");
			return (Criteria) this;
		}

		public Criteria andChgUserNotEqualTo(String value) {
			addCriterion("CHG_USER <>", value, "chgUser");
			return (Criteria) this;
		}

		public Criteria andChgUserGreaterThan(String value) {
			addCriterion("CHG_USER >", value, "chgUser");
			return (Criteria) this;
		}

		public Criteria andChgUserGreaterThanOrEqualTo(String value) {
			addCriterion("CHG_USER >=", value, "chgUser");
			return (Criteria) this;
		}

		public Criteria andChgUserLessThan(String value) {
			addCriterion("CHG_USER <", value, "chgUser");
			return (Criteria) this;
		}

		public Criteria andChgUserLessThanOrEqualTo(String value) {
			addCriterion("CHG_USER <=", value, "chgUser");
			return (Criteria) this;
		}

		public Criteria andChgUserLike(String value) {
			addCriterion("CHG_USER like", value, "chgUser");
			return (Criteria) this;
		}

		public Criteria andChgUserNotLike(String value) {
			addCriterion("CHG_USER not like", value, "chgUser");
			return (Criteria) this;
		}

		public Criteria andChgUserIn(List<String> values) {
			addCriterion("CHG_USER in", values, "chgUser");
			return (Criteria) this;
		}

		public Criteria andChgUserNotIn(List<String> values) {
			addCriterion("CHG_USER not in", values, "chgUser");
			return (Criteria) this;
		}

		public Criteria andChgUserBetween(String value1, String value2) {
			addCriterion("CHG_USER between", value1, value2, "chgUser");
			return (Criteria) this;
		}

		public Criteria andChgUserNotBetween(String value1, String value2) {
			addCriterion("CHG_USER not between", value1, value2, "chgUser");
			return (Criteria) this;
		}

		public Criteria andChgDtmIsNull() {
			addCriterion("CHG_DTM is null");
			return (Criteria) this;
		}

		public Criteria andChgDtmIsNotNull() {
			addCriterion("CHG_DTM is not null");
			return (Criteria) this;
		}

		public Criteria andChgDtmEqualTo(Date value) {
			addCriterion("CHG_DTM =", value, "chgDtm");
			return (Criteria) this;
		}

		public Criteria andChgDtmNotEqualTo(Date value) {
			addCriterion("CHG_DTM <>", value, "chgDtm");
			return (Criteria) this;
		}

		public Criteria andChgDtmGreaterThan(Date value) {
			addCriterion("CHG_DTM >", value, "chgDtm");
			return (Criteria) this;
		}

		public Criteria andChgDtmGreaterThanOrEqualTo(Date value) {
			addCriterion("CHG_DTM >=", value, "chgDtm");
			return (Criteria) this;
		}

		public Criteria andChgDtmLessThan(Date value) {
			addCriterion("CHG_DTM <", value, "chgDtm");
			return (Criteria) this;
		}

		public Criteria andChgDtmLessThanOrEqualTo(Date value) {
			addCriterion("CHG_DTM <=", value, "chgDtm");
			return (Criteria) this;
		}

		public Criteria andChgDtmIn(List<Date> values) {
			addCriterion("CHG_DTM in", values, "chgDtm");
			return (Criteria) this;
		}

		public Criteria andChgDtmNotIn(List<Date> values) {
			addCriterion("CHG_DTM not in", values, "chgDtm");
			return (Criteria) this;
		}

		public Criteria andChgDtmBetween(Date value1, Date value2) {
			addCriterion("CHG_DTM between", value1, value2, "chgDtm");
			return (Criteria) this;
		}

		public Criteria andChgDtmNotBetween(Date value1, Date value2) {
			addCriterion("CHG_DTM not between", value1, value2, "chgDtm");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table cpn_bank_info
	 * @mbggenerated  Fri Sep 07 22:07:33 KST 2012
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	private Integer rowsPerPage;

    private Integer startIndex;


    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cpn_bank_info
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 07 20:37:25 KST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}