package com.wallet.membership.model;

import java.util.Date;

import com.rocomo.common.model.Common;

public class CpnListAll extends Common {
	    /**
		 * 
		 */
		private static final long serialVersionUID = 1L;

		/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpn_list.cpn_id
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String cpnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpn_list.memb_id
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String membId;
    
    
    private String membName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpn_list.part_v
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String partV;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpn_list.disp_type
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String dispType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpn_list.name
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpn_list.use_name
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String useName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpn_list.use_code
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String useCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpn_list.menufac_id
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String menufacId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpn_list.mode_v
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String modeV;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpn_list.period_v
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String periodV;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpn_list.sort_v
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String sortV;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpn_list.cate_id
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String cateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpn_list.chg_day
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String chgDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpn_list.val_sday
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String valSday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpn_list.val_eday
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String valEday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpn_list.sday
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String sday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpn_list.eday
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String eday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpn_list.reg_user
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
//    private String regUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpn_list.reg_day
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String regDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpn_list.chg_user
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
//    private String chgUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpn_list.memo
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpn_list.info
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpn_list.usim_mode
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String usimMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpn_list.prim_mode
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String primMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpn_list.aff_type
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String affType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpn_list.main_display
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String mainDisplay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpn_list.disp_order
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String dispOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpn_list.PAY_FREE_YN
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String payFreeYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpn_list.RECOMM_YN
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String recommYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpn_list.RECOMM_SEQ
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private Integer recommSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpn_list.POPU_SEQ
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private Integer popuSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpn_list.chg_tm
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String chgTm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpn_list.COMP_PAY_YN
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String compPayYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpn_list.USIM_ID
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String usimId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.CPN_STAT
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String cpnStat;
    
    
    private String statComment;


		/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.POINT_DUP_USABLE_YN
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String pointDupUsableYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.MEMB_COMPULSORY_YN
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String membCompulsoryYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.ROAMING_TYPE
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String roamingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.ROAMING_CPN_NO
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String roamingCpnNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.USIM_CPN_NAME
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String usimCpnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.USIM_COMP_ID
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String usimCompId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.USIM_BRAN_ID
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String usimBranId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.POS_CPN_NAME
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String posCpnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.CPN_ISSUE_TYPE
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String cpnIssueType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.BAR_ISSUE_TYPE
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String barIssueType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.BAR_CONF_TYPE
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String barConfType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.CM_CONF_BARCD
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String cmConfBarcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.ONOFF_TYPE
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String onoffType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.ONLINE_URL
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String onlineUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.CPN_NOTI_URL
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String cpnNotiUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.CPN_MAX_USE_CNT
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private Integer cpnMaxUseCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.CPN_MAX_ISSUE_CNT
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private Integer cpnMaxIssueCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.YEAR_USABLE_CNT
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private Integer yearUsableCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.MONTH_USABLE_CNT
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private Integer monthUsableCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.DAY_USABLE_CNT
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private Integer dayUsableCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.DAY_ISSUE_MAX_CNT
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private Integer dayIssueMaxCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.DAY_ISSUE_STIME
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String dayIssueStime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.DAY_ISSUE_ETIME
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String dayIssueEtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.CPN_DISC_TYPE
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String cpnDiscType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.CPN_DISC_AMOUNT
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private Integer cpnDiscAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.ROUND_TYPE
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String roundType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.DC_UNIT
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String dcUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.MIN_PAY_PRICE
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private Integer minPayPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.MAX_DIC_PRICE
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private Integer maxDicPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.CALCUL_YN
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String calculYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.COMP_ID
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String compId;
    
    private String compName;
    

    private String branId;
    
    private String branName;

    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.SHOP_SVC_LIST
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String shopSvcList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.BANK_SVC_LIST
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String bankSvcList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.PAYCOM_SVC_LIST
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String paycomSvcList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.CPN_DUP_USABLE_YN
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String cpnDupUsableYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.RECOVER_YN
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String recoverYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.ISSUE_COMP_ID
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String issueCompId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.REG_USER
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String regUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.REG_DTM
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private Date regDtm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.CHG_USER
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String chgUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.CHG_DTM
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private Date chgDtm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.CPN_ISSUE_STAT
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String cpnIssueStat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.USABLE_CNT_YN
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String usableCntYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.DAY_ISSUE_YN
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String dayIssueYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.AUTO_ISSUE_TARGET
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String autoIssueTarget;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.AUTO_ISSUE_SDAY
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String autoIssueSday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.AUTO_ISSUE_EDAY
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String autoIssueEday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_LIST.DC_NOTICE
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    private String dcNotice;
    
    
    private String i3gsList;
    private String i4sList;
    private String a1List;
    private String i3gsDetail;
    private String i4sDetail;
    private String a1Detail;
    private String i3gsIntro;
    private String i4sIntro;
    private String a1Intro;
    
    private String isShare;
    private String isCompPay;
    private String isPool;

    private String regUserNm;
    private String chgUserNm;
    
    public String getRegUserNm() {
			return regUserNm;
		}

		public void setRegUserNm(String regUserNm) {
			this.regUserNm = regUserNm;
		}

		public String getChgUserNm() {
			return chgUserNm;
		}

		public void setChgUserNm(String chgUserNm) {
			this.chgUserNm = chgUserNm;
		}

		/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpn_list.cpn_id
     *
     * @return the value of cpn_list.cpn_id
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
//    public String getCpnId() {
//        return cpnId;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column cpn_list.cpn_id
//     *
//     * @param cpnId the value for cpn_list.cpn_id
//     *
//     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
//     */
//    public void setCpnId(String cpnId) {
//        this.cpnId = cpnId == null ? null : cpnId.trim();
//    }

    public String getIsShare() {
			return isShare;
		}

		public void setIsShare(String isShare) {
			this.isShare = isShare;
		}

		public String getIsCompPay() {
			return isCompPay;
		}

		public void setIsCompPay(String isCompPay) {
			this.isCompPay = isCompPay;
		}

		public String getIsPool() {
			return isPool;
		}

		public void setIsPool(String isPool) {
			this.isPool = isPool;
		}

		/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpn_list.memb_id
     *
     * @return the value of cpn_list.memb_id
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getMembId() {
        return membId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpn_list.memb_id
     *
     * @param membId the value for cpn_list.memb_id
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setMembId(String membId) {
        this.membId = membId == null ? null : membId.trim();
    }
    
    
    public String getMembName() {
      return membName;
    }

    
	  public void setMembName(String membName) {
	      this.membName = membName == null ? null : membName.trim();
	  }
	  
	  
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpn_list.part_v
     *
     * @return the value of cpn_list.part_v
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getPartV() {
        return partV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpn_list.part_v
     *
     * @param partV the value for cpn_list.part_v
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setPartV(String partV) {
        this.partV = partV == null ? null : partV.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpn_list.disp_type
     *
     * @return the value of cpn_list.disp_type
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getDispType() {
        return dispType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpn_list.disp_type
     *
     * @param dispType the value for cpn_list.disp_type
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setDispType(String dispType) {
        this.dispType = dispType == null ? null : dispType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpn_list.name
     *
     * @return the value of cpn_list.name
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpn_list.name
     *
     * @param name the value for cpn_list.name
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpn_list.use_name
     *
     * @return the value of cpn_list.use_name
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getUseName() {
        return useName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpn_list.use_name
     *
     * @param useName the value for cpn_list.use_name
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setUseName(String useName) {
        this.useName = useName == null ? null : useName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpn_list.use_code
     *
     * @return the value of cpn_list.use_code
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getUseCode() {
        return useCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpn_list.use_code
     *
     * @param useCode the value for cpn_list.use_code
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setUseCode(String useCode) {
        this.useCode = useCode == null ? null : useCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpn_list.menufac_id
     *
     * @return the value of cpn_list.menufac_id
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getMenufacId() {
        return menufacId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpn_list.menufac_id
     *
     * @param menufacId the value for cpn_list.menufac_id
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setMenufacId(String menufacId) {
        this.menufacId = menufacId == null ? null : menufacId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpn_list.mode_v
     *
     * @return the value of cpn_list.mode_v
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getModeV() {
        return modeV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpn_list.mode_v
     *
     * @param modeV the value for cpn_list.mode_v
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setModeV(String modeV) {
        this.modeV = modeV == null ? null : modeV.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpn_list.period_v
     *
     * @return the value of cpn_list.period_v
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getPeriodV() {
        return periodV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpn_list.period_v
     *
     * @param periodV the value for cpn_list.period_v
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setPeriodV(String periodV) {
        this.periodV = periodV == null ? null : periodV.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpn_list.sort_v
     *
     * @return the value of cpn_list.sort_v
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getSortV() {
        return sortV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpn_list.sort_v
     *
     * @param sortV the value for cpn_list.sort_v
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setSortV(String sortV) {
        this.sortV = sortV == null ? null : sortV.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpn_list.cate_id
     *
     * @return the value of cpn_list.cate_id
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getCateId() {
        return cateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpn_list.cate_id
     *
     * @param cateId the value for cpn_list.cate_id
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setCateId(String cateId) {
        this.cateId = cateId == null ? null : cateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpn_list.chg_day
     *
     * @return the value of cpn_list.chg_day
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getChgDay() {
        return chgDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpn_list.chg_day
     *
     * @param chgDay the value for cpn_list.chg_day
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setChgDay(String chgDay) {
        this.chgDay = chgDay == null ? null : chgDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpn_list.val_sday
     *
     * @return the value of cpn_list.val_sday
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getValSday() {
        return valSday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpn_list.val_sday
     *
     * @param valSday the value for cpn_list.val_sday
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setValSday(String valSday) {
        this.valSday = valSday == null ? null : valSday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpn_list.val_eday
     *
     * @return the value of cpn_list.val_eday
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getValEday() {
        return valEday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpn_list.val_eday
     *
     * @param valEday the value for cpn_list.val_eday
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setValEday(String valEday) {
        this.valEday = valEday == null ? null : valEday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpn_list.sday
     *
     * @return the value of cpn_list.sday
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getSday() {
        return sday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpn_list.sday
     *
     * @param sday the value for cpn_list.sday
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setSday(String sday) {
        this.sday = sday == null ? null : sday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpn_list.eday
     *
     * @return the value of cpn_list.eday
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getEday() {
        return eday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpn_list.eday
     *
     * @param eday the value for cpn_list.eday
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setEday(String eday) {
        this.eday = eday == null ? null : eday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpn_list.reg_user
     *
     * @return the value of cpn_list.reg_user
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
//     */
//    public String getRegUser() {
//        return regUser;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpn_list.reg_user
     *
     * @param regUser the value for cpn_list.reg_user
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
//    public void setRegUser(String regUser) {
//        this.regUser = regUser == null ? null : regUser.trim();
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpn_list.reg_day
     *
     * @return the value of cpn_list.reg_day
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getRegDay() {
        return regDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpn_list.reg_day
     *
     * @param regDay the value for cpn_list.reg_day
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setRegDay(String regDay) {
        this.regDay = regDay == null ? null : regDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpn_list.chg_user
     *
     * @return the value of cpn_list.chg_user
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
//    public String getChgUser() {
//        return chgUser;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpn_list.chg_user
     *
     * @param chgUser the value for cpn_list.chg_user
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
//    public void setChgUser(String chgUser) {
//        this.chgUser = chgUser == null ? null : chgUser.trim();
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpn_list.memo
     *
     * @return the value of cpn_list.memo
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpn_list.memo
     *
     * @param memo the value for cpn_list.memo
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpn_list.info
     *
     * @return the value of cpn_list.info
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpn_list.info
     *
     * @param info the value for cpn_list.info
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpn_list.usim_mode
     *
     * @return the value of cpn_list.usim_mode
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getUsimMode() {
        return usimMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpn_list.usim_mode
     *
     * @param usimMode the value for cpn_list.usim_mode
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setUsimMode(String usimMode) {
        this.usimMode = usimMode == null ? null : usimMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpn_list.prim_mode
     *
     * @return the value of cpn_list.prim_mode
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getPrimMode() {
        return primMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpn_list.prim_mode
     *
     * @param primMode the value for cpn_list.prim_mode
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setPrimMode(String primMode) {
        this.primMode = primMode == null ? null : primMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpn_list.aff_type
     *
     * @return the value of cpn_list.aff_type
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getAffType() {
        return affType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpn_list.aff_type
     *
     * @param affType the value for cpn_list.aff_type
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setAffType(String affType) {
        this.affType = affType == null ? null : affType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpn_list.main_display
     *
     * @return the value of cpn_list.main_display
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getMainDisplay() {
        return mainDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpn_list.main_display
     *
     * @param mainDisplay the value for cpn_list.main_display
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setMainDisplay(String mainDisplay) {
        this.mainDisplay = mainDisplay == null ? null : mainDisplay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpn_list.disp_order
     *
     * @return the value of cpn_list.disp_order
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getDispOrder() {
        return dispOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpn_list.disp_order
     *
     * @param dispOrder the value for cpn_list.disp_order
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setDispOrder(String dispOrder) {
        this.dispOrder = dispOrder == null ? null : dispOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpn_list.PAY_FREE_YN
     *
     * @return the value of cpn_list.PAY_FREE_YN
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getPayFreeYn() {
        return payFreeYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpn_list.PAY_FREE_YN
     *
     * @param payFreeYn the value for cpn_list.PAY_FREE_YN
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setPayFreeYn(String payFreeYn) {
        this.payFreeYn = payFreeYn == null ? null : payFreeYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpn_list.RECOMM_YN
     *
     * @return the value of cpn_list.RECOMM_YN
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getRecommYn() {
        return recommYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpn_list.RECOMM_YN
     *
     * @param recommYn the value for cpn_list.RECOMM_YN
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setRecommYn(String recommYn) {
        this.recommYn = recommYn == null ? null : recommYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpn_list.RECOMM_SEQ
     *
     * @return the value of cpn_list.RECOMM_SEQ
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public Integer getRecommSeq() {
        return recommSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpn_list.RECOMM_SEQ
     *
     * @param recommSeq the value for cpn_list.RECOMM_SEQ
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setRecommSeq(Integer recommSeq) {
        this.recommSeq = recommSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpn_list.POPU_SEQ
     *
     * @return the value of cpn_list.POPU_SEQ
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public Integer getPopuSeq() {
        return popuSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpn_list.POPU_SEQ
     *
     * @param popuSeq the value for cpn_list.POPU_SEQ
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setPopuSeq(Integer popuSeq) {
        this.popuSeq = popuSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpn_list.chg_tm
     *
     * @return the value of cpn_list.chg_tm
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getChgTm() {
        return chgTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpn_list.chg_tm
     *
     * @param chgTm the value for cpn_list.chg_tm
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setChgTm(String chgTm) {
        this.chgTm = chgTm == null ? null : chgTm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpn_list.COMP_PAY_YN
     *
     * @return the value of cpn_list.COMP_PAY_YN
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getCompPayYn() {
        return compPayYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpn_list.COMP_PAY_YN
     *
     * @param compPayYn the value for cpn_list.COMP_PAY_YN
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setCompPayYn(String compPayYn) {
        this.compPayYn = compPayYn == null ? null : compPayYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpn_list.USIM_ID
     *
     * @return the value of cpn_list.USIM_ID
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getUsimId() {
        return usimId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpn_list.USIM_ID
     *
     * @param usimId the value for cpn_list.USIM_ID
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setUsimId(String usimId) {
        this.usimId = usimId == null ? null : usimId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.CPN_ID
     *
     * @return the value of MW_CS_CPN_LIST.CPN_ID
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getCpnId() {
        return cpnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.CPN_ID
     *
     * @param cpnId the value for MW_CS_CPN_LIST.CPN_ID
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setCpnId(String cpnId) {
        this.cpnId = cpnId == null ? null : cpnId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.CPN_STAT
     *
     * @return the value of MW_CS_CPN_LIST.CPN_STAT
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getCpnStat() {
        return cpnStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.CPN_STAT
     *
     * @param cpnStat the value for MW_CS_CPN_LIST.CPN_STAT
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setCpnStat(String cpnStat) {
        this.cpnStat = cpnStat == null ? null : cpnStat.trim();
    }


    public String getStatComment() {
			return statComment;
		}

		public void setStatComment(String statComment) {
			this.statComment = statComment;
		}
		
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.POINT_DUP_USABLE_YN
     *
     * @return the value of MW_CS_CPN_LIST.POINT_DUP_USABLE_YN
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getPointDupUsableYn() {
        return pointDupUsableYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.POINT_DUP_USABLE_YN
     *
     * @param pointDupUsableYn the value for MW_CS_CPN_LIST.POINT_DUP_USABLE_YN
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setPointDupUsableYn(String pointDupUsableYn) {
        this.pointDupUsableYn = pointDupUsableYn == null ? null : pointDupUsableYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.MEMB_COMPULSORY_YN
     *
     * @return the value of MW_CS_CPN_LIST.MEMB_COMPULSORY_YN
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getMembCompulsoryYn() {
        return membCompulsoryYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.MEMB_COMPULSORY_YN
     *
     * @param membCompulsoryYn the value for MW_CS_CPN_LIST.MEMB_COMPULSORY_YN
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setMembCompulsoryYn(String membCompulsoryYn) {
        this.membCompulsoryYn = membCompulsoryYn == null ? null : membCompulsoryYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.ROAMING_TYPE
     *
     * @return the value of MW_CS_CPN_LIST.ROAMING_TYPE
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getRoamingType() {
        return roamingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.ROAMING_TYPE
     *
     * @param roamingType the value for MW_CS_CPN_LIST.ROAMING_TYPE
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setRoamingType(String roamingType) {
        this.roamingType = roamingType == null ? null : roamingType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.ROAMING_CPN_NO
     *
     * @return the value of MW_CS_CPN_LIST.ROAMING_CPN_NO
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getRoamingCpnNo() {
        return roamingCpnNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.ROAMING_CPN_NO
     *
     * @param roamingCpnNo the value for MW_CS_CPN_LIST.ROAMING_CPN_NO
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setRoamingCpnNo(String roamingCpnNo) {
        this.roamingCpnNo = roamingCpnNo == null ? null : roamingCpnNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.USIM_CPN_NAME
     *
     * @return the value of MW_CS_CPN_LIST.USIM_CPN_NAME
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getUsimCpnName() {
        return usimCpnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.USIM_CPN_NAME
     *
     * @param usimCpnName the value for MW_CS_CPN_LIST.USIM_CPN_NAME
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setUsimCpnName(String usimCpnName) {
        this.usimCpnName = usimCpnName == null ? null : usimCpnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.USIM_COMP_ID
     *
     * @return the value of MW_CS_CPN_LIST.USIM_COMP_ID
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getUsimCompId() {
        return usimCompId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.USIM_COMP_ID
     *
     * @param usimCompId the value for MW_CS_CPN_LIST.USIM_COMP_ID
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setUsimCompId(String usimCompId) {
        this.usimCompId = usimCompId == null ? null : usimCompId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.USIM_BRAN_ID
     *
     * @return the value of MW_CS_CPN_LIST.USIM_BRAN_ID
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getUsimBranId() {
        return usimBranId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.USIM_BRAN_ID
     *
     * @param usimBranId the value for MW_CS_CPN_LIST.USIM_BRAN_ID
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setUsimBranId(String usimBranId) {
        this.usimBranId = usimBranId == null ? null : usimBranId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.POS_CPN_NAME
     *
     * @return the value of MW_CS_CPN_LIST.POS_CPN_NAME
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getPosCpnName() {
        return posCpnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.POS_CPN_NAME
     *
     * @param posCpnName the value for MW_CS_CPN_LIST.POS_CPN_NAME
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setPosCpnName(String posCpnName) {
        this.posCpnName = posCpnName == null ? null : posCpnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.CPN_ISSUE_TYPE
     *
     * @return the value of MW_CS_CPN_LIST.CPN_ISSUE_TYPE
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getCpnIssueType() {
        return cpnIssueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.CPN_ISSUE_TYPE
     *
     * @param cpnIssueType the value for MW_CS_CPN_LIST.CPN_ISSUE_TYPE
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setCpnIssueType(String cpnIssueType) {
        this.cpnIssueType = cpnIssueType == null ? null : cpnIssueType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.BAR_ISSUE_TYPE
     *
     * @return the value of MW_CS_CPN_LIST.BAR_ISSUE_TYPE
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getBarIssueType() {
        return barIssueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.BAR_ISSUE_TYPE
     *
     * @param barIssueType the value for MW_CS_CPN_LIST.BAR_ISSUE_TYPE
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setBarIssueType(String barIssueType) {
        this.barIssueType = barIssueType == null ? null : barIssueType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.BAR_CONF_TYPE
     *
     * @return the value of MW_CS_CPN_LIST.BAR_CONF_TYPE
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getBarConfType() {
        return barConfType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.BAR_CONF_TYPE
     *
     * @param barConfType the value for MW_CS_CPN_LIST.BAR_CONF_TYPE
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setBarConfType(String barConfType) {
        this.barConfType = barConfType == null ? null : barConfType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.CM_CONF_BARCD
     *
     * @return the value of MW_CS_CPN_LIST.CM_CONF_BARCD
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getCmConfBarcd() {
        return cmConfBarcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.CM_CONF_BARCD
     *
     * @param cmConfBarcd the value for MW_CS_CPN_LIST.CM_CONF_BARCD
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setCmConfBarcd(String cmConfBarcd) {
        this.cmConfBarcd = cmConfBarcd == null ? null : cmConfBarcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.ONOFF_TYPE
     *
     * @return the value of MW_CS_CPN_LIST.ONOFF_TYPE
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getOnoffType() {
        return onoffType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.ONOFF_TYPE
     *
     * @param onoffType the value for MW_CS_CPN_LIST.ONOFF_TYPE
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setOnoffType(String onoffType) {
        this.onoffType = onoffType == null ? null : onoffType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.ONLINE_URL
     *
     * @return the value of MW_CS_CPN_LIST.ONLINE_URL
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getOnlineUrl() {
        return onlineUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.ONLINE_URL
     *
     * @param onlineUrl the value for MW_CS_CPN_LIST.ONLINE_URL
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setOnlineUrl(String onlineUrl) {
        this.onlineUrl = onlineUrl == null ? null : onlineUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.CPN_NOTI_URL
     *
     * @return the value of MW_CS_CPN_LIST.CPN_NOTI_URL
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getCpnNotiUrl() {
        return cpnNotiUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.CPN_NOTI_URL
     *
     * @param cpnNotiUrl the value for MW_CS_CPN_LIST.CPN_NOTI_URL
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setCpnNotiUrl(String cpnNotiUrl) {
        this.cpnNotiUrl = cpnNotiUrl == null ? null : cpnNotiUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.CPN_MAX_USE_CNT
     *
     * @return the value of MW_CS_CPN_LIST.CPN_MAX_USE_CNT
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public Integer getCpnMaxUseCnt() {
        return cpnMaxUseCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.CPN_MAX_USE_CNT
     *
     * @param cpnMaxUseCnt the value for MW_CS_CPN_LIST.CPN_MAX_USE_CNT
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setCpnMaxUseCnt(Integer cpnMaxUseCnt) {
        this.cpnMaxUseCnt = cpnMaxUseCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.CPN_MAX_ISSUE_CNT
     *
     * @return the value of MW_CS_CPN_LIST.CPN_MAX_ISSUE_CNT
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public Integer getCpnMaxIssueCnt() {
        return cpnMaxIssueCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.CPN_MAX_ISSUE_CNT
     *
     * @param cpnMaxIssueCnt the value for MW_CS_CPN_LIST.CPN_MAX_ISSUE_CNT
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setCpnMaxIssueCnt(Integer cpnMaxIssueCnt) {
        this.cpnMaxIssueCnt = cpnMaxIssueCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.YEAR_USABLE_CNT
     *
     * @return the value of MW_CS_CPN_LIST.YEAR_USABLE_CNT
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public Integer getYearUsableCnt() {
        return yearUsableCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.YEAR_USABLE_CNT
     *
     * @param yearUsableCnt the value for MW_CS_CPN_LIST.YEAR_USABLE_CNT
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setYearUsableCnt(Integer yearUsableCnt) {
        this.yearUsableCnt = yearUsableCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.MONTH_USABLE_CNT
     *
     * @return the value of MW_CS_CPN_LIST.MONTH_USABLE_CNT
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public Integer getMonthUsableCnt() {
        return monthUsableCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.MONTH_USABLE_CNT
     *
     * @param monthUsableCnt the value for MW_CS_CPN_LIST.MONTH_USABLE_CNT
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setMonthUsableCnt(Integer monthUsableCnt) {
        this.monthUsableCnt = monthUsableCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.DAY_USABLE_CNT
     *
     * @return the value of MW_CS_CPN_LIST.DAY_USABLE_CNT
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public Integer getDayUsableCnt() {
        return dayUsableCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.DAY_USABLE_CNT
     *
     * @param dayUsableCnt the value for MW_CS_CPN_LIST.DAY_USABLE_CNT
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setDayUsableCnt(Integer dayUsableCnt) {
        this.dayUsableCnt = dayUsableCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.DAY_ISSUE_MAX_CNT
     *
     * @return the value of MW_CS_CPN_LIST.DAY_ISSUE_MAX_CNT
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public Integer getDayIssueMaxCnt() {
        return dayIssueMaxCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.DAY_ISSUE_MAX_CNT
     *
     * @param dayIssueMaxCnt the value for MW_CS_CPN_LIST.DAY_ISSUE_MAX_CNT
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setDayIssueMaxCnt(Integer dayIssueMaxCnt) {
        this.dayIssueMaxCnt = dayIssueMaxCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.DAY_ISSUE_STIME
     *
     * @return the value of MW_CS_CPN_LIST.DAY_ISSUE_STIME
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getDayIssueStime() {
        return dayIssueStime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.DAY_ISSUE_STIME
     *
     * @param dayIssueStime the value for MW_CS_CPN_LIST.DAY_ISSUE_STIME
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setDayIssueStime(String dayIssueStime) {
        this.dayIssueStime = dayIssueStime == null ? null : dayIssueStime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.DAY_ISSUE_ETIME
     *
     * @return the value of MW_CS_CPN_LIST.DAY_ISSUE_ETIME
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getDayIssueEtime() {
        return dayIssueEtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.DAY_ISSUE_ETIME
     *
     * @param dayIssueEtime the value for MW_CS_CPN_LIST.DAY_ISSUE_ETIME
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setDayIssueEtime(String dayIssueEtime) {
        this.dayIssueEtime = dayIssueEtime == null ? null : dayIssueEtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.CPN_DISC_TYPE
     *
     * @return the value of MW_CS_CPN_LIST.CPN_DISC_TYPE
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getCpnDiscType() {
        return cpnDiscType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.CPN_DISC_TYPE
     *
     * @param cpnDiscType the value for MW_CS_CPN_LIST.CPN_DISC_TYPE
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setCpnDiscType(String cpnDiscType) {
        this.cpnDiscType = cpnDiscType == null ? null : cpnDiscType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.CPN_DISC_AMOUNT
     *
     * @return the value of MW_CS_CPN_LIST.CPN_DISC_AMOUNT
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public Integer getCpnDiscAmount() {
        return cpnDiscAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.CPN_DISC_AMOUNT
     *
     * @param cpnDiscAmount the value for MW_CS_CPN_LIST.CPN_DISC_AMOUNT
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setCpnDiscAmount(Integer cpnDiscAmount) {
        this.cpnDiscAmount = cpnDiscAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.ROUND_TYPE
     *
     * @return the value of MW_CS_CPN_LIST.ROUND_TYPE
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getRoundType() {
        return roundType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.ROUND_TYPE
     *
     * @param roundType the value for MW_CS_CPN_LIST.ROUND_TYPE
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setRoundType(String roundType) {
        this.roundType = roundType == null ? null : roundType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.DC_UNIT
     *
     * @return the value of MW_CS_CPN_LIST.DC_UNIT
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getDcUnit() {
        return dcUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.DC_UNIT
     *
     * @param dcUnit the value for MW_CS_CPN_LIST.DC_UNIT
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setDcUnit(String dcUnit) {
        this.dcUnit = dcUnit == null ? null : dcUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.MIN_PAY_PRICE
     *
     * @return the value of MW_CS_CPN_LIST.MIN_PAY_PRICE
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public Integer getMinPayPrice() {
        return minPayPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.MIN_PAY_PRICE
     *
     * @param minPayPrice the value for MW_CS_CPN_LIST.MIN_PAY_PRICE
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setMinPayPrice(Integer minPayPrice) {
        this.minPayPrice = minPayPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.MAX_DIC_PRICE
     *
     * @return the value of MW_CS_CPN_LIST.MAX_DIC_PRICE
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public Integer getMaxDicPrice() {
        return maxDicPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.MAX_DIC_PRICE
     *
     * @param maxDicPrice the value for MW_CS_CPN_LIST.MAX_DIC_PRICE
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setMaxDicPrice(Integer maxDicPrice) {
        this.maxDicPrice = maxDicPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.CALCUL_YN
     *
     * @return the value of MW_CS_CPN_LIST.CALCUL_YN
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getCalculYn() {
        return calculYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.CALCUL_YN
     *
     * @param calculYn the value for MW_CS_CPN_LIST.CALCUL_YN
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setCalculYn(String calculYn) {
        this.calculYn = calculYn == null ? null : calculYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.COMP_ID
     *
     * @return the value of MW_CS_CPN_LIST.COMP_ID
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.COMP_ID
     *
     * @param compId the value for MW_CS_CPN_LIST.COMP_ID
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setCompId(String compId) {
        this.compId = compId == null ? null : compId.trim();
    }


    public String getCompName() {
        return compName;
    }

    public void setCompName(String compName) {
        this.compName = compName == null ? null : compName.trim();
    }


    public String getBranId() {
        return branId;
    }

    public void setBranId(String branId) {
        this.branId = branId == null ? null : branId.trim();
    }


    public String getBranName() {
        return branName;
    }

    public void setBranName(String branName) {
        this.branName = branName == null ? null : branName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.SHOP_SVC_LIST
     *
     * @return the value of MW_CS_CPN_LIST.SHOP_SVC_LIST
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getShopSvcList() {
        return shopSvcList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.SHOP_SVC_LIST
     *
     * @param shopSvcList the value for MW_CS_CPN_LIST.SHOP_SVC_LIST
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setShopSvcList(String shopSvcList) {
        this.shopSvcList = shopSvcList == null ? null : shopSvcList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.BANK_SVC_LIST
     *
     * @return the value of MW_CS_CPN_LIST.BANK_SVC_LIST
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getBankSvcList() {
        return bankSvcList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.BANK_SVC_LIST
     *
     * @param bankSvcList the value for MW_CS_CPN_LIST.BANK_SVC_LIST
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setBankSvcList(String bankSvcList) {
        this.bankSvcList = bankSvcList == null ? null : bankSvcList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.PAYCOM_SVC_LIST
     *
     * @return the value of MW_CS_CPN_LIST.PAYCOM_SVC_LIST
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getPaycomSvcList() {
        return paycomSvcList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.PAYCOM_SVC_LIST
     *
     * @param paycomSvcList the value for MW_CS_CPN_LIST.PAYCOM_SVC_LIST
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setPaycomSvcList(String paycomSvcList) {
        this.paycomSvcList = paycomSvcList == null ? null : paycomSvcList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.CPN_DUP_USABLE_YN
     *
     * @return the value of MW_CS_CPN_LIST.CPN_DUP_USABLE_YN
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getCpnDupUsableYn() {
        return cpnDupUsableYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.CPN_DUP_USABLE_YN
     *
     * @param cpnDupUsableYn the value for MW_CS_CPN_LIST.CPN_DUP_USABLE_YN
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setCpnDupUsableYn(String cpnDupUsableYn) {
        this.cpnDupUsableYn = cpnDupUsableYn == null ? null : cpnDupUsableYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.RECOVER_YN
     *
     * @return the value of MW_CS_CPN_LIST.RECOVER_YN
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getRecoverYn() {
        return recoverYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.RECOVER_YN
     *
     * @param recoverYn the value for MW_CS_CPN_LIST.RECOVER_YN
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setRecoverYn(String recoverYn) {
        this.recoverYn = recoverYn == null ? null : recoverYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.ISSUE_COMP_ID
     *
     * @return the value of MW_CS_CPN_LIST.ISSUE_COMP_ID
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getIssueCompId() {
        return issueCompId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.ISSUE_COMP_ID
     *
     * @param issueCompId the value for MW_CS_CPN_LIST.ISSUE_COMP_ID
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setIssueCompId(String issueCompId) {
        this.issueCompId = issueCompId == null ? null : issueCompId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.REG_USER
     *
     * @return the value of MW_CS_CPN_LIST.REG_USER
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getRegUser() {
        return regUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.REG_USER
     *
     * @param regUser the value for MW_CS_CPN_LIST.REG_USER
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setRegUser(String regUser) {
        this.regUser = regUser == null ? null : regUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.REG_DTM
     *
     * @return the value of MW_CS_CPN_LIST.REG_DTM
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public Date getRegDtm() {
        return regDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.REG_DTM
     *
     * @param regDtm the value for MW_CS_CPN_LIST.REG_DTM
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setRegDtm(Date regDtm) {
        this.regDtm = regDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.CHG_USER
     *
     * @return the value of MW_CS_CPN_LIST.CHG_USER
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getChgUser() {
        return chgUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.CHG_USER
     *
     * @param chgUser the value for MW_CS_CPN_LIST.CHG_USER
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setChgUser(String chgUser) {
        this.chgUser = chgUser == null ? null : chgUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.CHG_DTM
     *
     * @return the value of MW_CS_CPN_LIST.CHG_DTM
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public Date getChgDtm() {
        return chgDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.CHG_DTM
     *
     * @param chgDtm the value for MW_CS_CPN_LIST.CHG_DTM
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setChgDtm(Date chgDtm) {
        this.chgDtm = chgDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.CPN_ISSUE_STAT
     *
     * @return the value of MW_CS_CPN_LIST.CPN_ISSUE_STAT
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getCpnIssueStat() {
        return cpnIssueStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.CPN_ISSUE_STAT
     *
     * @param cpnIssueStat the value for MW_CS_CPN_LIST.CPN_ISSUE_STAT
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setCpnIssueStat(String cpnIssueStat) {
        this.cpnIssueStat = cpnIssueStat == null ? null : cpnIssueStat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.USABLE_CNT_YN
     *
     * @return the value of MW_CS_CPN_LIST.USABLE_CNT_YN
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getUsableCntYn() {
        return usableCntYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.USABLE_CNT_YN
     *
     * @param usableCntYn the value for MW_CS_CPN_LIST.USABLE_CNT_YN
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setUsableCntYn(String usableCntYn) {
        this.usableCntYn = usableCntYn == null ? null : usableCntYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.DAY_ISSUE_YN
     *
     * @return the value of MW_CS_CPN_LIST.DAY_ISSUE_YN
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getDayIssueYn() {
        return dayIssueYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.DAY_ISSUE_YN
     *
     * @param dayIssueYn the value for MW_CS_CPN_LIST.DAY_ISSUE_YN
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setDayIssueYn(String dayIssueYn) {
        this.dayIssueYn = dayIssueYn == null ? null : dayIssueYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.AUTO_ISSUE_TARGET
     *
     * @return the value of MW_CS_CPN_LIST.AUTO_ISSUE_TARGET
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getAutoIssueTarget() {
        return autoIssueTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.AUTO_ISSUE_TARGET
     *
     * @param autoIssueTarget the value for MW_CS_CPN_LIST.AUTO_ISSUE_TARGET
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setAutoIssueTarget(String autoIssueTarget) {
        this.autoIssueTarget = autoIssueTarget == null ? null : autoIssueTarget.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.AUTO_ISSUE_SDAY
     *
     * @return the value of MW_CS_CPN_LIST.AUTO_ISSUE_SDAY
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getAutoIssueSday() {
        return autoIssueSday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.AUTO_ISSUE_SDAY
     *
     * @param autoIssueSday the value for MW_CS_CPN_LIST.AUTO_ISSUE_SDAY
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setAutoIssueSday(String autoIssueSday) {
        this.autoIssueSday = autoIssueSday == null ? null : autoIssueSday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.AUTO_ISSUE_EDAY
     *
     * @return the value of MW_CS_CPN_LIST.AUTO_ISSUE_EDAY
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getAutoIssueEday() {
        return autoIssueEday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.AUTO_ISSUE_EDAY
     *
     * @param autoIssueEday the value for MW_CS_CPN_LIST.AUTO_ISSUE_EDAY
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public void setAutoIssueEday(String autoIssueEday) {
        this.autoIssueEday = autoIssueEday == null ? null : autoIssueEday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_LIST.DC_NOTICE
     *
     * @return the value of MW_CS_CPN_LIST.DC_NOTICE
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    public String getDcNotice() {
        return dcNotice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_LIST.DC_NOTICE
     *
     * @param dcNotice the value for MW_CS_CPN_LIST.DC_NOTICE
     *
     * @mbggenerated Mon Sep 17 12:47:23 KST 2012
     */
    
    
    public void setDcNotice(String dcNotice) {
        this.dcNotice = dcNotice == null ? null : dcNotice.trim();
    }

		public String getI3gsList() {
			return i3gsList;
		}

		public void setI3gsList(String i3gsList) {
			this.i3gsList = i3gsList;
		}

		public String getI4sList() {
			return i4sList;
		}

		public void setI4sList(String i4sList) {
			this.i4sList = i4sList;
		}

		public String getA1List() {
			return a1List;
		}

		public void setA1List(String a1List) {
			this.a1List = a1List;
		}

		public String getI3gsDetail() {
			return i3gsDetail;
		}

		public void setI3gsDetail(String i3gsDetail) {
			this.i3gsDetail = i3gsDetail;
		}

		public String getI4sDetail() {
			return i4sDetail;
		}

		public void setI4sDetail(String i4sDetail) {
			this.i4sDetail = i4sDetail;
		}

		public String getA1Detail() {
			return a1Detail;
		}

		public void setA1Detail(String a1Detail) {
			this.a1Detail = a1Detail;
		}

		public String getI3gsIntro() {
			return i3gsIntro;
		}

		public void setI3gsIntro(String i3gsIntro) {
			this.i3gsIntro = i3gsIntro;
		}

		public String getI4sIntro() {
			return i4sIntro;
		}

		public void setI4sIntro(String i4sIntro) {
			this.i4sIntro = i4sIntro;
		}

		public String getA1Intro() {
			return a1Intro;
		}

		public void setA1Intro(String a1Intro) {
			this.a1Intro = a1Intro;
		}

		
		private String isTargetCpn;
		public String getIsTargetCpn(){
			return this.isTargetCpn;
		}
		public void setIsTargetCpn(String isTargetCpn){
			this.isTargetCpn = isTargetCpn;
		}
}