package com.wallet.membership.model;

import com.rocomo.common.model.Common;

public class MwCmCodeKey extends Common {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CM_CODE.GRP_CODE
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    private String grpCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CM_CODE.COM_CD
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    private String comCd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CM_CODE.GRP_CODE
     *
     * @return the value of MW_CM_CODE.GRP_CODE
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    public String getGrpCode() {
        return grpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CM_CODE.GRP_CODE
     *
     * @param grpCode the value for MW_CM_CODE.GRP_CODE
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    public void setGrpCode(String grpCode) {
        this.grpCode = grpCode == null ? null : grpCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CM_CODE.COM_CD
     *
     * @return the value of MW_CM_CODE.COM_CD
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    public String getComCd() {
        return comCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CM_CODE.COM_CD
     *
     * @param comCd the value for MW_CM_CODE.COM_CD
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    public void setComCd(String comCd) {
        this.comCd = comCd == null ? null : comCd.trim();
    }
}