package com.wallet.membership.model;

import java.util.Date;

public class MwCmCode extends MwCmCodeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CM_CODE.COM_CD_VAL
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    private String comCdVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CM_CODE.SEQ_NO
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    private Integer seqNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CM_CODE.USE_YN
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    private String useYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CM_CODE.REMARK1
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    private String remark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CM_CODE.REMARK2
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    private String remark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CM_CODE.REMARK3
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    private String remark3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CM_CODE.REMARK4
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    private String remark4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CM_CODE.REG_USER
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    private String regUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CM_CODE.REG_DTM
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    private Date regDtm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CM_CODE.CHG_USER
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    private String chgUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CM_CODE.CHG_DTM
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    private Date chgDtm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CM_CODE.COM_CD_VAL
     *
     * @return the value of MW_CM_CODE.COM_CD_VAL
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    public String getComCdVal() {
        return comCdVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CM_CODE.COM_CD_VAL
     *
     * @param comCdVal the value for MW_CM_CODE.COM_CD_VAL
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    public void setComCdVal(String comCdVal) {
        this.comCdVal = comCdVal == null ? null : comCdVal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CM_CODE.SEQ_NO
     *
     * @return the value of MW_CM_CODE.SEQ_NO
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    public Integer getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CM_CODE.SEQ_NO
     *
     * @param seqNo the value for MW_CM_CODE.SEQ_NO
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    public void setSeqNo(Integer seqNo) {
        this.seqNo = seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CM_CODE.USE_YN
     *
     * @return the value of MW_CM_CODE.USE_YN
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    public String getUseYn() {
        return useYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CM_CODE.USE_YN
     *
     * @param useYn the value for MW_CM_CODE.USE_YN
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    public void setUseYn(String useYn) {
        this.useYn = useYn == null ? null : useYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CM_CODE.REMARK1
     *
     * @return the value of MW_CM_CODE.REMARK1
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CM_CODE.REMARK1
     *
     * @param remark1 the value for MW_CM_CODE.REMARK1
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CM_CODE.REMARK2
     *
     * @return the value of MW_CM_CODE.REMARK2
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CM_CODE.REMARK2
     *
     * @param remark2 the value for MW_CM_CODE.REMARK2
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CM_CODE.REMARK3
     *
     * @return the value of MW_CM_CODE.REMARK3
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    public String getRemark3() {
        return remark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CM_CODE.REMARK3
     *
     * @param remark3 the value for MW_CM_CODE.REMARK3
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    public void setRemark3(String remark3) {
        this.remark3 = remark3 == null ? null : remark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CM_CODE.REMARK4
     *
     * @return the value of MW_CM_CODE.REMARK4
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    public String getRemark4() {
        return remark4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CM_CODE.REMARK4
     *
     * @param remark4 the value for MW_CM_CODE.REMARK4
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    public void setRemark4(String remark4) {
        this.remark4 = remark4 == null ? null : remark4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CM_CODE.REG_USER
     *
     * @return the value of MW_CM_CODE.REG_USER
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    public String getRegUser() {
        return regUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CM_CODE.REG_USER
     *
     * @param regUser the value for MW_CM_CODE.REG_USER
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    public void setRegUser(String regUser) {
        this.regUser = regUser == null ? null : regUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CM_CODE.REG_DTM
     *
     * @return the value of MW_CM_CODE.REG_DTM
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    public Date getRegDtm() {
        return regDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CM_CODE.REG_DTM
     *
     * @param regDtm the value for MW_CM_CODE.REG_DTM
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    public void setRegDtm(Date regDtm) {
        this.regDtm = regDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CM_CODE.CHG_USER
     *
     * @return the value of MW_CM_CODE.CHG_USER
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    public String getChgUser() {
        return chgUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CM_CODE.CHG_USER
     *
     * @param chgUser the value for MW_CM_CODE.CHG_USER
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    public void setChgUser(String chgUser) {
        this.chgUser = chgUser == null ? null : chgUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CM_CODE.CHG_DTM
     *
     * @return the value of MW_CM_CODE.CHG_DTM
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    public Date getChgDtm() {
        return chgDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CM_CODE.CHG_DTM
     *
     * @param chgDtm the value for MW_CM_CODE.CHG_DTM
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    public void setChgDtm(Date chgDtm) {
        this.chgDtm = chgDtm;
    }
}