package com.wallet.membership.model;

import com.rocomo.common.model.Common;

public class MwCsBulkCpnKey extends Common {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_BULK_CPN.CPN_ID
     *
     * @mbggenerated Mon Sep 17 17:56:16 KST 2012
     */
    private String cpnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_BULK_CPN.ISSUE_SEQ
     *
     * @mbggenerated Mon Sep 17 17:56:16 KST 2012
     */
    private Integer issueSeq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_BULK_CPN.CPN_ID
     *
     * @return the value of MW_CS_BULK_CPN.CPN_ID
     *
     * @mbggenerated Mon Sep 17 17:56:16 KST 2012
     */
    public String getCpnId() {
        return cpnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_BULK_CPN.CPN_ID
     *
     * @param cpnId the value for MW_CS_BULK_CPN.CPN_ID
     *
     * @mbggenerated Mon Sep 17 17:56:16 KST 2012
     */
    public void setCpnId(String cpnId) {
        this.cpnId = cpnId == null ? null : cpnId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_BULK_CPN.ISSUE_SEQ
     *
     * @return the value of MW_CS_BULK_CPN.ISSUE_SEQ
     *
     * @mbggenerated Mon Sep 17 17:56:16 KST 2012
     */
    public Integer getIssueSeq() {
        return issueSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_BULK_CPN.ISSUE_SEQ
     *
     * @param issueSeq the value for MW_CS_BULK_CPN.ISSUE_SEQ
     *
     * @mbggenerated Mon Sep 17 17:56:16 KST 2012
     */
    public void setIssueSeq(Integer issueSeq) {
        this.issueSeq = issueSeq;
    }
}