package com.wallet.membership.model;

import com.rocomo.common.model.Common;

public class MwCsCpnShareratioKey extends Common {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_SHARERATIO.CPN_ID
     *
     * @mbggenerated Mon Sep 24 01:19:50 KST 2012
     */
    private String cpnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_CS_CPN_SHARERATIO.SEQ_NO
     *
     * @mbggenerated Mon Sep 24 01:19:50 KST 2012
     */
    private Integer seqNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_SHARERATIO.CPN_ID
     *
     * @return the value of MW_CS_CPN_SHARERATIO.CPN_ID
     *
     * @mbggenerated Mon Sep 24 01:19:50 KST 2012
     */
    public String getCpnId() {
        return cpnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_SHARERATIO.CPN_ID
     *
     * @param cpnId the value for MW_CS_CPN_SHARERATIO.CPN_ID
     *
     * @mbggenerated Mon Sep 24 01:19:50 KST 2012
     */
    public void setCpnId(String cpnId) {
        this.cpnId = cpnId == null ? null : cpnId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_CS_CPN_SHARERATIO.SEQ_NO
     *
     * @return the value of MW_CS_CPN_SHARERATIO.SEQ_NO
     *
     * @mbggenerated Mon Sep 24 01:19:50 KST 2012
     */
    public Integer getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_CS_CPN_SHARERATIO.SEQ_NO
     *
     * @param seqNo the value for MW_CS_CPN_SHARERATIO.SEQ_NO
     *
     * @mbggenerated Mon Sep 24 01:19:50 KST 2012
     */
    public void setSeqNo(Integer seqNo) {
        this.seqNo = seqNo;
    }
}