package com.wallet.membership.model;

import com.rocomo.common.model.Common;

public class MwMsStampKey extends Common {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_MS_STAMP.MEMB_ID
     *
     * @mbggenerated Tue Sep 18 15:05:33 KST 2012
     */
    private String membId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MW_MS_STAMP.STAMP_SEQ
     *
     * @mbggenerated Tue Sep 18 15:05:33 KST 2012
     */
    private Integer stampSeq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_MS_STAMP.MEMB_ID
     *
     * @return the value of MW_MS_STAMP.MEMB_ID
     *
     * @mbggenerated Tue Sep 18 15:05:33 KST 2012
     */
    public String getMembId() {
        return membId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_MS_STAMP.MEMB_ID
     *
     * @param membId the value for MW_MS_STAMP.MEMB_ID
     *
     * @mbggenerated Tue Sep 18 15:05:33 KST 2012
     */
    public void setMembId(String membId) {
        this.membId = membId == null ? null : membId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MW_MS_STAMP.STAMP_SEQ
     *
     * @return the value of MW_MS_STAMP.STAMP_SEQ
     *
     * @mbggenerated Tue Sep 18 15:05:33 KST 2012
     */
    public Integer getStampSeq() {
        return stampSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MW_MS_STAMP.STAMP_SEQ
     *
     * @param stampSeq the value for MW_MS_STAMP.STAMP_SEQ
     *
     * @mbggenerated Tue Sep 18 15:05:33 KST 2012
     */
    public void setStampSeq(Integer stampSeq) {
        this.stampSeq = stampSeq;
    }
}