package com.wallet.membership.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MwMsCompPayMentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MW_MS_COMP_PAYMENT
     *
     * @mbggenerated Fri Sep 14 19:55:25 KST 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MW_MS_COMP_PAYMENT
     *
     * @mbggenerated Fri Sep 14 19:55:25 KST 2012
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MW_MS_COMP_PAYMENT
     *
     * @mbggenerated Fri Sep 14 19:55:25 KST 2012
     */
    protected List<Criteria> oredCriteria;

    private Integer rowsPerPage;

    private Integer startIndex;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_COMP_PAYMENT
     *
     * @mbggenerated Fri Sep 14 19:55:25 KST 2012
     */
    public MwMsCompPayMentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_COMP_PAYMENT
     *
     * @mbggenerated Fri Sep 14 19:55:25 KST 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_COMP_PAYMENT
     *
     * @mbggenerated Fri Sep 14 19:55:25 KST 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_COMP_PAYMENT
     *
     * @mbggenerated Fri Sep 14 19:55:25 KST 2012
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_COMP_PAYMENT
     *
     * @mbggenerated Fri Sep 14 19:55:25 KST 2012
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_COMP_PAYMENT
     *
     * @mbggenerated Fri Sep 14 19:55:25 KST 2012
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_COMP_PAYMENT
     *
     * @mbggenerated Fri Sep 14 19:55:25 KST 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_COMP_PAYMENT
     *
     * @mbggenerated Fri Sep 14 19:55:25 KST 2012
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_COMP_PAYMENT
     *
     * @mbggenerated Fri Sep 14 19:55:25 KST 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_COMP_PAYMENT
     *
     * @mbggenerated Fri Sep 14 19:55:25 KST 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_COMP_PAYMENT
     *
     * @mbggenerated Fri Sep 14 19:55:25 KST 2012
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setRowsPerPage(Integer rowsPerPage) {
        this.rowsPerPage = rowsPerPage;
    }

    public Integer getRowsPerPage() {
        return rowsPerPage;
    }

    public void setStartIndex(Integer startIndex) {
        this.startIndex = startIndex;
    }

    public Integer getStartIndex() {
        return startIndex;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MW_MS_COMP_PAYMENT
     *
     * @mbggenerated Fri Sep 14 19:55:25 KST 2012
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCompIdIsNull() {
            addCriterion("COMP_ID is null");
            return (Criteria) this;
        }

        public Criteria andCompIdIsNotNull() {
            addCriterion("COMP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCompIdEqualTo(String value) {
            addCriterion("COMP_ID =", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdNotEqualTo(String value) {
            addCriterion("COMP_ID <>", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdGreaterThan(String value) {
            addCriterion("COMP_ID >", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdGreaterThanOrEqualTo(String value) {
            addCriterion("COMP_ID >=", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdLessThan(String value) {
            addCriterion("COMP_ID <", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdLessThanOrEqualTo(String value) {
            addCriterion("COMP_ID <=", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdLike(String value) {
            addCriterion("COMP_ID like", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdNotLike(String value) {
            addCriterion("COMP_ID not like", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdIn(List<String> values) {
            addCriterion("COMP_ID in", values, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdNotIn(List<String> values) {
            addCriterion("COMP_ID not in", values, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdBetween(String value1, String value2) {
            addCriterion("COMP_ID between", value1, value2, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdNotBetween(String value1, String value2) {
            addCriterion("COMP_ID not between", value1, value2, "compId");
            return (Criteria) this;
        }

        public Criteria andCompPayMembSaveIsNull() {
            addCriterion("COMP_PAY_MEMB_SAVE is null");
            return (Criteria) this;
        }

        public Criteria andCompPayMembSaveIsNotNull() {
            addCriterion("COMP_PAY_MEMB_SAVE is not null");
            return (Criteria) this;
        }

        public Criteria andCompPayMembSaveEqualTo(String value) {
            addCriterion("COMP_PAY_MEMB_SAVE =", value, "compPayMembSave");
            return (Criteria) this;
        }

        public Criteria andCompPayMembSaveNotEqualTo(String value) {
            addCriterion("COMP_PAY_MEMB_SAVE <>", value, "compPayMembSave");
            return (Criteria) this;
        }

        public Criteria andCompPayMembSaveGreaterThan(String value) {
            addCriterion("COMP_PAY_MEMB_SAVE >", value, "compPayMembSave");
            return (Criteria) this;
        }

        public Criteria andCompPayMembSaveGreaterThanOrEqualTo(String value) {
            addCriterion("COMP_PAY_MEMB_SAVE >=", value, "compPayMembSave");
            return (Criteria) this;
        }

        public Criteria andCompPayMembSaveLessThan(String value) {
            addCriterion("COMP_PAY_MEMB_SAVE <", value, "compPayMembSave");
            return (Criteria) this;
        }

        public Criteria andCompPayMembSaveLessThanOrEqualTo(String value) {
            addCriterion("COMP_PAY_MEMB_SAVE <=", value, "compPayMembSave");
            return (Criteria) this;
        }

        public Criteria andCompPayMembSaveLike(String value) {
            addCriterion("COMP_PAY_MEMB_SAVE like", value, "compPayMembSave");
            return (Criteria) this;
        }

        public Criteria andCompPayMembSaveNotLike(String value) {
            addCriterion("COMP_PAY_MEMB_SAVE not like", value, "compPayMembSave");
            return (Criteria) this;
        }

        public Criteria andCompPayMembSaveIn(List<String> values) {
            addCriterion("COMP_PAY_MEMB_SAVE in", values, "compPayMembSave");
            return (Criteria) this;
        }

        public Criteria andCompPayMembSaveNotIn(List<String> values) {
            addCriterion("COMP_PAY_MEMB_SAVE not in", values, "compPayMembSave");
            return (Criteria) this;
        }

        public Criteria andCompPayMembSaveBetween(String value1, String value2) {
            addCriterion("COMP_PAY_MEMB_SAVE between", value1, value2, "compPayMembSave");
            return (Criteria) this;
        }

        public Criteria andCompPayMembSaveNotBetween(String value1, String value2) {
            addCriterion("COMP_PAY_MEMB_SAVE not between", value1, value2, "compPayMembSave");
            return (Criteria) this;
        }

        public Criteria andCompPayMembUseIsNull() {
            addCriterion("COMP_PAY_MEMB_USE is null");
            return (Criteria) this;
        }

        public Criteria andCompPayMembUseIsNotNull() {
            addCriterion("COMP_PAY_MEMB_USE is not null");
            return (Criteria) this;
        }

        public Criteria andCompPayMembUseEqualTo(String value) {
            addCriterion("COMP_PAY_MEMB_USE =", value, "compPayMembUse");
            return (Criteria) this;
        }

        public Criteria andCompPayMembUseNotEqualTo(String value) {
            addCriterion("COMP_PAY_MEMB_USE <>", value, "compPayMembUse");
            return (Criteria) this;
        }

        public Criteria andCompPayMembUseGreaterThan(String value) {
            addCriterion("COMP_PAY_MEMB_USE >", value, "compPayMembUse");
            return (Criteria) this;
        }

        public Criteria andCompPayMembUseGreaterThanOrEqualTo(String value) {
            addCriterion("COMP_PAY_MEMB_USE >=", value, "compPayMembUse");
            return (Criteria) this;
        }

        public Criteria andCompPayMembUseLessThan(String value) {
            addCriterion("COMP_PAY_MEMB_USE <", value, "compPayMembUse");
            return (Criteria) this;
        }

        public Criteria andCompPayMembUseLessThanOrEqualTo(String value) {
            addCriterion("COMP_PAY_MEMB_USE <=", value, "compPayMembUse");
            return (Criteria) this;
        }

        public Criteria andCompPayMembUseLike(String value) {
            addCriterion("COMP_PAY_MEMB_USE like", value, "compPayMembUse");
            return (Criteria) this;
        }

        public Criteria andCompPayMembUseNotLike(String value) {
            addCriterion("COMP_PAY_MEMB_USE not like", value, "compPayMembUse");
            return (Criteria) this;
        }

        public Criteria andCompPayMembUseIn(List<String> values) {
            addCriterion("COMP_PAY_MEMB_USE in", values, "compPayMembUse");
            return (Criteria) this;
        }

        public Criteria andCompPayMembUseNotIn(List<String> values) {
            addCriterion("COMP_PAY_MEMB_USE not in", values, "compPayMembUse");
            return (Criteria) this;
        }

        public Criteria andCompPayMembUseBetween(String value1, String value2) {
            addCriterion("COMP_PAY_MEMB_USE between", value1, value2, "compPayMembUse");
            return (Criteria) this;
        }

        public Criteria andCompPayMembUseNotBetween(String value1, String value2) {
            addCriterion("COMP_PAY_MEMB_USE not between", value1, value2, "compPayMembUse");
            return (Criteria) this;
        }

        public Criteria andCompPayMembDcIsNull() {
            addCriterion("COMP_PAY_MEMB_DC is null");
            return (Criteria) this;
        }

        public Criteria andCompPayMembDcIsNotNull() {
            addCriterion("COMP_PAY_MEMB_DC is not null");
            return (Criteria) this;
        }

        public Criteria andCompPayMembDcEqualTo(String value) {
            addCriterion("COMP_PAY_MEMB_DC =", value, "compPayMembDc");
            return (Criteria) this;
        }

        public Criteria andCompPayMembDcNotEqualTo(String value) {
            addCriterion("COMP_PAY_MEMB_DC <>", value, "compPayMembDc");
            return (Criteria) this;
        }

        public Criteria andCompPayMembDcGreaterThan(String value) {
            addCriterion("COMP_PAY_MEMB_DC >", value, "compPayMembDc");
            return (Criteria) this;
        }

        public Criteria andCompPayMembDcGreaterThanOrEqualTo(String value) {
            addCriterion("COMP_PAY_MEMB_DC >=", value, "compPayMembDc");
            return (Criteria) this;
        }

        public Criteria andCompPayMembDcLessThan(String value) {
            addCriterion("COMP_PAY_MEMB_DC <", value, "compPayMembDc");
            return (Criteria) this;
        }

        public Criteria andCompPayMembDcLessThanOrEqualTo(String value) {
            addCriterion("COMP_PAY_MEMB_DC <=", value, "compPayMembDc");
            return (Criteria) this;
        }

        public Criteria andCompPayMembDcLike(String value) {
            addCriterion("COMP_PAY_MEMB_DC like", value, "compPayMembDc");
            return (Criteria) this;
        }

        public Criteria andCompPayMembDcNotLike(String value) {
            addCriterion("COMP_PAY_MEMB_DC not like", value, "compPayMembDc");
            return (Criteria) this;
        }

        public Criteria andCompPayMembDcIn(List<String> values) {
            addCriterion("COMP_PAY_MEMB_DC in", values, "compPayMembDc");
            return (Criteria) this;
        }

        public Criteria andCompPayMembDcNotIn(List<String> values) {
            addCriterion("COMP_PAY_MEMB_DC not in", values, "compPayMembDc");
            return (Criteria) this;
        }

        public Criteria andCompPayMembDcBetween(String value1, String value2) {
            addCriterion("COMP_PAY_MEMB_DC between", value1, value2, "compPayMembDc");
            return (Criteria) this;
        }

        public Criteria andCompPayMembDcNotBetween(String value1, String value2) {
            addCriterion("COMP_PAY_MEMB_DC not between", value1, value2, "compPayMembDc");
            return (Criteria) this;
        }

        public Criteria andCompPayCpnYnIsNull() {
            addCriterion("COMP_PAY_CPN_YN is null");
            return (Criteria) this;
        }

        public Criteria andCompPayCpnYnIsNotNull() {
            addCriterion("COMP_PAY_CPN_YN is not null");
            return (Criteria) this;
        }

        public Criteria andCompPayCpnYnEqualTo(String value) {
            addCriterion("COMP_PAY_CPN_YN =", value, "compPayCpnYn");
            return (Criteria) this;
        }

        public Criteria andCompPayCpnYnNotEqualTo(String value) {
            addCriterion("COMP_PAY_CPN_YN <>", value, "compPayCpnYn");
            return (Criteria) this;
        }

        public Criteria andCompPayCpnYnGreaterThan(String value) {
            addCriterion("COMP_PAY_CPN_YN >", value, "compPayCpnYn");
            return (Criteria) this;
        }

        public Criteria andCompPayCpnYnGreaterThanOrEqualTo(String value) {
            addCriterion("COMP_PAY_CPN_YN >=", value, "compPayCpnYn");
            return (Criteria) this;
        }

        public Criteria andCompPayCpnYnLessThan(String value) {
            addCriterion("COMP_PAY_CPN_YN <", value, "compPayCpnYn");
            return (Criteria) this;
        }

        public Criteria andCompPayCpnYnLessThanOrEqualTo(String value) {
            addCriterion("COMP_PAY_CPN_YN <=", value, "compPayCpnYn");
            return (Criteria) this;
        }

        public Criteria andCompPayCpnYnLike(String value) {
            addCriterion("COMP_PAY_CPN_YN like", value, "compPayCpnYn");
            return (Criteria) this;
        }

        public Criteria andCompPayCpnYnNotLike(String value) {
            addCriterion("COMP_PAY_CPN_YN not like", value, "compPayCpnYn");
            return (Criteria) this;
        }

        public Criteria andCompPayCpnYnIn(List<String> values) {
            addCriterion("COMP_PAY_CPN_YN in", values, "compPayCpnYn");
            return (Criteria) this;
        }

        public Criteria andCompPayCpnYnNotIn(List<String> values) {
            addCriterion("COMP_PAY_CPN_YN not in", values, "compPayCpnYn");
            return (Criteria) this;
        }

        public Criteria andCompPayCpnYnBetween(String value1, String value2) {
            addCriterion("COMP_PAY_CPN_YN between", value1, value2, "compPayCpnYn");
            return (Criteria) this;
        }

        public Criteria andCompPayCpnYnNotBetween(String value1, String value2) {
            addCriterion("COMP_PAY_CPN_YN not between", value1, value2, "compPayCpnYn");
            return (Criteria) this;
        }

        public Criteria andCompPayStampYnIsNull() {
            addCriterion("COMP_PAY_STAMP_YN is null");
            return (Criteria) this;
        }

        public Criteria andCompPayStampYnIsNotNull() {
            addCriterion("COMP_PAY_STAMP_YN is not null");
            return (Criteria) this;
        }

        public Criteria andCompPayStampYnEqualTo(String value) {
            addCriterion("COMP_PAY_STAMP_YN =", value, "compPayStampYn");
            return (Criteria) this;
        }

        public Criteria andCompPayStampYnNotEqualTo(String value) {
            addCriterion("COMP_PAY_STAMP_YN <>", value, "compPayStampYn");
            return (Criteria) this;
        }

        public Criteria andCompPayStampYnGreaterThan(String value) {
            addCriterion("COMP_PAY_STAMP_YN >", value, "compPayStampYn");
            return (Criteria) this;
        }

        public Criteria andCompPayStampYnGreaterThanOrEqualTo(String value) {
            addCriterion("COMP_PAY_STAMP_YN >=", value, "compPayStampYn");
            return (Criteria) this;
        }

        public Criteria andCompPayStampYnLessThan(String value) {
            addCriterion("COMP_PAY_STAMP_YN <", value, "compPayStampYn");
            return (Criteria) this;
        }

        public Criteria andCompPayStampYnLessThanOrEqualTo(String value) {
            addCriterion("COMP_PAY_STAMP_YN <=", value, "compPayStampYn");
            return (Criteria) this;
        }

        public Criteria andCompPayStampYnLike(String value) {
            addCriterion("COMP_PAY_STAMP_YN like", value, "compPayStampYn");
            return (Criteria) this;
        }

        public Criteria andCompPayStampYnNotLike(String value) {
            addCriterion("COMP_PAY_STAMP_YN not like", value, "compPayStampYn");
            return (Criteria) this;
        }

        public Criteria andCompPayStampYnIn(List<String> values) {
            addCriterion("COMP_PAY_STAMP_YN in", values, "compPayStampYn");
            return (Criteria) this;
        }

        public Criteria andCompPayStampYnNotIn(List<String> values) {
            addCriterion("COMP_PAY_STAMP_YN not in", values, "compPayStampYn");
            return (Criteria) this;
        }

        public Criteria andCompPayStampYnBetween(String value1, String value2) {
            addCriterion("COMP_PAY_STAMP_YN between", value1, value2, "compPayStampYn");
            return (Criteria) this;
        }

        public Criteria andCompPayStampYnNotBetween(String value1, String value2) {
            addCriterion("COMP_PAY_STAMP_YN not between", value1, value2, "compPayStampYn");
            return (Criteria) this;
        }

        public Criteria andCompPayStampSaveYnIsNull() {
            addCriterion("COMP_PAY_STAMP_SAVE_YN is null");
            return (Criteria) this;
        }

        public Criteria andCompPayStampSaveYnIsNotNull() {
            addCriterion("COMP_PAY_STAMP_SAVE_YN is not null");
            return (Criteria) this;
        }

        public Criteria andCompPayStampSaveYnEqualTo(String value) {
            addCriterion("COMP_PAY_STAMP_SAVE_YN =", value, "compPayStampSaveYn");
            return (Criteria) this;
        }

        public Criteria andCompPayStampSaveYnNotEqualTo(String value) {
            addCriterion("COMP_PAY_STAMP_SAVE_YN <>", value, "compPayStampSaveYn");
            return (Criteria) this;
        }

        public Criteria andCompPayStampSaveYnGreaterThan(String value) {
            addCriterion("COMP_PAY_STAMP_SAVE_YN >", value, "compPayStampSaveYn");
            return (Criteria) this;
        }

        public Criteria andCompPayStampSaveYnGreaterThanOrEqualTo(String value) {
            addCriterion("COMP_PAY_STAMP_SAVE_YN >=", value, "compPayStampSaveYn");
            return (Criteria) this;
        }

        public Criteria andCompPayStampSaveYnLessThan(String value) {
            addCriterion("COMP_PAY_STAMP_SAVE_YN <", value, "compPayStampSaveYn");
            return (Criteria) this;
        }

        public Criteria andCompPayStampSaveYnLessThanOrEqualTo(String value) {
            addCriterion("COMP_PAY_STAMP_SAVE_YN <=", value, "compPayStampSaveYn");
            return (Criteria) this;
        }

        public Criteria andCompPayStampSaveYnLike(String value) {
            addCriterion("COMP_PAY_STAMP_SAVE_YN like", value, "compPayStampSaveYn");
            return (Criteria) this;
        }

        public Criteria andCompPayStampSaveYnNotLike(String value) {
            addCriterion("COMP_PAY_STAMP_SAVE_YN not like", value, "compPayStampSaveYn");
            return (Criteria) this;
        }

        public Criteria andCompPayStampSaveYnIn(List<String> values) {
            addCriterion("COMP_PAY_STAMP_SAVE_YN in", values, "compPayStampSaveYn");
            return (Criteria) this;
        }

        public Criteria andCompPayStampSaveYnNotIn(List<String> values) {
            addCriterion("COMP_PAY_STAMP_SAVE_YN not in", values, "compPayStampSaveYn");
            return (Criteria) this;
        }

        public Criteria andCompPayStampSaveYnBetween(String value1, String value2) {
            addCriterion("COMP_PAY_STAMP_SAVE_YN between", value1, value2, "compPayStampSaveYn");
            return (Criteria) this;
        }

        public Criteria andCompPayStampSaveYnNotBetween(String value1, String value2) {
            addCriterion("COMP_PAY_STAMP_SAVE_YN not between", value1, value2, "compPayStampSaveYn");
            return (Criteria) this;
        }

        public Criteria andSaveRateFixedYnIsNull() {
            addCriterion("SAVE_RATE_FIXED_YN is null");
            return (Criteria) this;
        }

        public Criteria andSaveRateFixedYnIsNotNull() {
            addCriterion("SAVE_RATE_FIXED_YN is not null");
            return (Criteria) this;
        }

        public Criteria andSaveRateFixedYnEqualTo(String value) {
            addCriterion("SAVE_RATE_FIXED_YN =", value, "saveRateFixedYn");
            return (Criteria) this;
        }

        public Criteria andSaveRateFixedYnNotEqualTo(String value) {
            addCriterion("SAVE_RATE_FIXED_YN <>", value, "saveRateFixedYn");
            return (Criteria) this;
        }

        public Criteria andSaveRateFixedYnGreaterThan(String value) {
            addCriterion("SAVE_RATE_FIXED_YN >", value, "saveRateFixedYn");
            return (Criteria) this;
        }

        public Criteria andSaveRateFixedYnGreaterThanOrEqualTo(String value) {
            addCriterion("SAVE_RATE_FIXED_YN >=", value, "saveRateFixedYn");
            return (Criteria) this;
        }

        public Criteria andSaveRateFixedYnLessThan(String value) {
            addCriterion("SAVE_RATE_FIXED_YN <", value, "saveRateFixedYn");
            return (Criteria) this;
        }

        public Criteria andSaveRateFixedYnLessThanOrEqualTo(String value) {
            addCriterion("SAVE_RATE_FIXED_YN <=", value, "saveRateFixedYn");
            return (Criteria) this;
        }

        public Criteria andSaveRateFixedYnLike(String value) {
            addCriterion("SAVE_RATE_FIXED_YN like", value, "saveRateFixedYn");
            return (Criteria) this;
        }

        public Criteria andSaveRateFixedYnNotLike(String value) {
            addCriterion("SAVE_RATE_FIXED_YN not like", value, "saveRateFixedYn");
            return (Criteria) this;
        }

        public Criteria andSaveRateFixedYnIn(List<String> values) {
            addCriterion("SAVE_RATE_FIXED_YN in", values, "saveRateFixedYn");
            return (Criteria) this;
        }

        public Criteria andSaveRateFixedYnNotIn(List<String> values) {
            addCriterion("SAVE_RATE_FIXED_YN not in", values, "saveRateFixedYn");
            return (Criteria) this;
        }

        public Criteria andSaveRateFixedYnBetween(String value1, String value2) {
            addCriterion("SAVE_RATE_FIXED_YN between", value1, value2, "saveRateFixedYn");
            return (Criteria) this;
        }

        public Criteria andSaveRateFixedYnNotBetween(String value1, String value2) {
            addCriterion("SAVE_RATE_FIXED_YN not between", value1, value2, "saveRateFixedYn");
            return (Criteria) this;
        }

        public Criteria andCashSaveRateIsNull() {
            addCriterion("CASH_SAVE_RATE is null");
            return (Criteria) this;
        }

        public Criteria andCashSaveRateIsNotNull() {
            addCriterion("CASH_SAVE_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andCashSaveRateEqualTo(Integer value) {
            addCriterion("CASH_SAVE_RATE =", value, "cashSaveRate");
            return (Criteria) this;
        }

        public Criteria andCashSaveRateNotEqualTo(Integer value) {
            addCriterion("CASH_SAVE_RATE <>", value, "cashSaveRate");
            return (Criteria) this;
        }

        public Criteria andCashSaveRateGreaterThan(Integer value) {
            addCriterion("CASH_SAVE_RATE >", value, "cashSaveRate");
            return (Criteria) this;
        }

        public Criteria andCashSaveRateGreaterThanOrEqualTo(Integer value) {
            addCriterion("CASH_SAVE_RATE >=", value, "cashSaveRate");
            return (Criteria) this;
        }

        public Criteria andCashSaveRateLessThan(Integer value) {
            addCriterion("CASH_SAVE_RATE <", value, "cashSaveRate");
            return (Criteria) this;
        }

        public Criteria andCashSaveRateLessThanOrEqualTo(Integer value) {
            addCriterion("CASH_SAVE_RATE <=", value, "cashSaveRate");
            return (Criteria) this;
        }

        public Criteria andCashSaveRateIn(List<Integer> values) {
            addCriterion("CASH_SAVE_RATE in", values, "cashSaveRate");
            return (Criteria) this;
        }

        public Criteria andCashSaveRateNotIn(List<Integer> values) {
            addCriterion("CASH_SAVE_RATE not in", values, "cashSaveRate");
            return (Criteria) this;
        }

        public Criteria andCashSaveRateBetween(Integer value1, Integer value2) {
            addCriterion("CASH_SAVE_RATE between", value1, value2, "cashSaveRate");
            return (Criteria) this;
        }

        public Criteria andCashSaveRateNotBetween(Integer value1, Integer value2) {
            addCriterion("CASH_SAVE_RATE not between", value1, value2, "cashSaveRate");
            return (Criteria) this;
        }

        public Criteria andCardSaveRateIsNull() {
            addCriterion("CARD_SAVE_RATE is null");
            return (Criteria) this;
        }

        public Criteria andCardSaveRateIsNotNull() {
            addCriterion("CARD_SAVE_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andCardSaveRateEqualTo(Integer value) {
            addCriterion("CARD_SAVE_RATE =", value, "cardSaveRate");
            return (Criteria) this;
        }

        public Criteria andCardSaveRateNotEqualTo(Integer value) {
            addCriterion("CARD_SAVE_RATE <>", value, "cardSaveRate");
            return (Criteria) this;
        }

        public Criteria andCardSaveRateGreaterThan(Integer value) {
            addCriterion("CARD_SAVE_RATE >", value, "cardSaveRate");
            return (Criteria) this;
        }

        public Criteria andCardSaveRateGreaterThanOrEqualTo(Integer value) {
            addCriterion("CARD_SAVE_RATE >=", value, "cardSaveRate");
            return (Criteria) this;
        }

        public Criteria andCardSaveRateLessThan(Integer value) {
            addCriterion("CARD_SAVE_RATE <", value, "cardSaveRate");
            return (Criteria) this;
        }

        public Criteria andCardSaveRateLessThanOrEqualTo(Integer value) {
            addCriterion("CARD_SAVE_RATE <=", value, "cardSaveRate");
            return (Criteria) this;
        }

        public Criteria andCardSaveRateIn(List<Integer> values) {
            addCriterion("CARD_SAVE_RATE in", values, "cardSaveRate");
            return (Criteria) this;
        }

        public Criteria andCardSaveRateNotIn(List<Integer> values) {
            addCriterion("CARD_SAVE_RATE not in", values, "cardSaveRate");
            return (Criteria) this;
        }

        public Criteria andCardSaveRateBetween(Integer value1, Integer value2) {
            addCriterion("CARD_SAVE_RATE between", value1, value2, "cardSaveRate");
            return (Criteria) this;
        }

        public Criteria andCardSaveRateNotBetween(Integer value1, Integer value2) {
            addCriterion("CARD_SAVE_RATE not between", value1, value2, "cardSaveRate");
            return (Criteria) this;
        }

        public Criteria andCompSaveRateIsNull() {
            addCriterion("COMP_SAVE_RATE is null");
            return (Criteria) this;
        }

        public Criteria andCompSaveRateIsNotNull() {
            addCriterion("COMP_SAVE_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andCompSaveRateEqualTo(Integer value) {
            addCriterion("COMP_SAVE_RATE =", value, "compSaveRate");
            return (Criteria) this;
        }

        public Criteria andCompSaveRateNotEqualTo(Integer value) {
            addCriterion("COMP_SAVE_RATE <>", value, "compSaveRate");
            return (Criteria) this;
        }

        public Criteria andCompSaveRateGreaterThan(Integer value) {
            addCriterion("COMP_SAVE_RATE >", value, "compSaveRate");
            return (Criteria) this;
        }

        public Criteria andCompSaveRateGreaterThanOrEqualTo(Integer value) {
            addCriterion("COMP_SAVE_RATE >=", value, "compSaveRate");
            return (Criteria) this;
        }

        public Criteria andCompSaveRateLessThan(Integer value) {
            addCriterion("COMP_SAVE_RATE <", value, "compSaveRate");
            return (Criteria) this;
        }

        public Criteria andCompSaveRateLessThanOrEqualTo(Integer value) {
            addCriterion("COMP_SAVE_RATE <=", value, "compSaveRate");
            return (Criteria) this;
        }

        public Criteria andCompSaveRateIn(List<Integer> values) {
            addCriterion("COMP_SAVE_RATE in", values, "compSaveRate");
            return (Criteria) this;
        }

        public Criteria andCompSaveRateNotIn(List<Integer> values) {
            addCriterion("COMP_SAVE_RATE not in", values, "compSaveRate");
            return (Criteria) this;
        }

        public Criteria andCompSaveRateBetween(Integer value1, Integer value2) {
            addCriterion("COMP_SAVE_RATE between", value1, value2, "compSaveRate");
            return (Criteria) this;
        }

        public Criteria andCompSaveRateNotBetween(Integer value1, Integer value2) {
            addCriterion("COMP_SAVE_RATE not between", value1, value2, "compSaveRate");
            return (Criteria) this;
        }

        public Criteria andDebitSaveRateIsNull() {
            addCriterion("DEBIT_SAVE_RATE is null");
            return (Criteria) this;
        }

        public Criteria andDebitSaveRateIsNotNull() {
            addCriterion("DEBIT_SAVE_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andDebitSaveRateEqualTo(Integer value) {
            addCriterion("DEBIT_SAVE_RATE =", value, "debitSaveRate");
            return (Criteria) this;
        }

        public Criteria andDebitSaveRateNotEqualTo(Integer value) {
            addCriterion("DEBIT_SAVE_RATE <>", value, "debitSaveRate");
            return (Criteria) this;
        }

        public Criteria andDebitSaveRateGreaterThan(Integer value) {
            addCriterion("DEBIT_SAVE_RATE >", value, "debitSaveRate");
            return (Criteria) this;
        }

        public Criteria andDebitSaveRateGreaterThanOrEqualTo(Integer value) {
            addCriterion("DEBIT_SAVE_RATE >=", value, "debitSaveRate");
            return (Criteria) this;
        }

        public Criteria andDebitSaveRateLessThan(Integer value) {
            addCriterion("DEBIT_SAVE_RATE <", value, "debitSaveRate");
            return (Criteria) this;
        }

        public Criteria andDebitSaveRateLessThanOrEqualTo(Integer value) {
            addCriterion("DEBIT_SAVE_RATE <=", value, "debitSaveRate");
            return (Criteria) this;
        }

        public Criteria andDebitSaveRateIn(List<Integer> values) {
            addCriterion("DEBIT_SAVE_RATE in", values, "debitSaveRate");
            return (Criteria) this;
        }

        public Criteria andDebitSaveRateNotIn(List<Integer> values) {
            addCriterion("DEBIT_SAVE_RATE not in", values, "debitSaveRate");
            return (Criteria) this;
        }

        public Criteria andDebitSaveRateBetween(Integer value1, Integer value2) {
            addCriterion("DEBIT_SAVE_RATE between", value1, value2, "debitSaveRate");
            return (Criteria) this;
        }

        public Criteria andDebitSaveRateNotBetween(Integer value1, Integer value2) {
            addCriterion("DEBIT_SAVE_RATE not between", value1, value2, "debitSaveRate");
            return (Criteria) this;
        }

        public Criteria andEtcSaveRateIsNull() {
            addCriterion("ETC_SAVE_RATE is null");
            return (Criteria) this;
        }

        public Criteria andEtcSaveRateIsNotNull() {
            addCriterion("ETC_SAVE_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andEtcSaveRateEqualTo(Integer value) {
            addCriterion("ETC_SAVE_RATE =", value, "etcSaveRate");
            return (Criteria) this;
        }

        public Criteria andEtcSaveRateNotEqualTo(Integer value) {
            addCriterion("ETC_SAVE_RATE <>", value, "etcSaveRate");
            return (Criteria) this;
        }

        public Criteria andEtcSaveRateGreaterThan(Integer value) {
            addCriterion("ETC_SAVE_RATE >", value, "etcSaveRate");
            return (Criteria) this;
        }

        public Criteria andEtcSaveRateGreaterThanOrEqualTo(Integer value) {
            addCriterion("ETC_SAVE_RATE >=", value, "etcSaveRate");
            return (Criteria) this;
        }

        public Criteria andEtcSaveRateLessThan(Integer value) {
            addCriterion("ETC_SAVE_RATE <", value, "etcSaveRate");
            return (Criteria) this;
        }

        public Criteria andEtcSaveRateLessThanOrEqualTo(Integer value) {
            addCriterion("ETC_SAVE_RATE <=", value, "etcSaveRate");
            return (Criteria) this;
        }

        public Criteria andEtcSaveRateIn(List<Integer> values) {
            addCriterion("ETC_SAVE_RATE in", values, "etcSaveRate");
            return (Criteria) this;
        }

        public Criteria andEtcSaveRateNotIn(List<Integer> values) {
            addCriterion("ETC_SAVE_RATE not in", values, "etcSaveRate");
            return (Criteria) this;
        }

        public Criteria andEtcSaveRateBetween(Integer value1, Integer value2) {
            addCriterion("ETC_SAVE_RATE between", value1, value2, "etcSaveRate");
            return (Criteria) this;
        }

        public Criteria andEtcSaveRateNotBetween(Integer value1, Integer value2) {
            addCriterion("ETC_SAVE_RATE not between", value1, value2, "etcSaveRate");
            return (Criteria) this;
        }

        public Criteria andSaveUnitIsNull() {
            addCriterion("SAVE_UNIT is null");
            return (Criteria) this;
        }

        public Criteria andSaveUnitIsNotNull() {
            addCriterion("SAVE_UNIT is not null");
            return (Criteria) this;
        }

        public Criteria andSaveUnitEqualTo(String value) {
            addCriterion("SAVE_UNIT =", value, "saveUnit");
            return (Criteria) this;
        }

        public Criteria andSaveUnitNotEqualTo(String value) {
            addCriterion("SAVE_UNIT <>", value, "saveUnit");
            return (Criteria) this;
        }

        public Criteria andSaveUnitGreaterThan(String value) {
            addCriterion("SAVE_UNIT >", value, "saveUnit");
            return (Criteria) this;
        }

        public Criteria andSaveUnitGreaterThanOrEqualTo(String value) {
            addCriterion("SAVE_UNIT >=", value, "saveUnit");
            return (Criteria) this;
        }

        public Criteria andSaveUnitLessThan(String value) {
            addCriterion("SAVE_UNIT <", value, "saveUnit");
            return (Criteria) this;
        }

        public Criteria andSaveUnitLessThanOrEqualTo(String value) {
            addCriterion("SAVE_UNIT <=", value, "saveUnit");
            return (Criteria) this;
        }

        public Criteria andSaveUnitLike(String value) {
            addCriterion("SAVE_UNIT like", value, "saveUnit");
            return (Criteria) this;
        }

        public Criteria andSaveUnitNotLike(String value) {
            addCriterion("SAVE_UNIT not like", value, "saveUnit");
            return (Criteria) this;
        }

        public Criteria andSaveUnitIn(List<String> values) {
            addCriterion("SAVE_UNIT in", values, "saveUnit");
            return (Criteria) this;
        }

        public Criteria andSaveUnitNotIn(List<String> values) {
            addCriterion("SAVE_UNIT not in", values, "saveUnit");
            return (Criteria) this;
        }

        public Criteria andSaveUnitBetween(String value1, String value2) {
            addCriterion("SAVE_UNIT between", value1, value2, "saveUnit");
            return (Criteria) this;
        }

        public Criteria andSaveUnitNotBetween(String value1, String value2) {
            addCriterion("SAVE_UNIT not between", value1, value2, "saveUnit");
            return (Criteria) this;
        }

        public Criteria andSaveRoundTypeIsNull() {
            addCriterion("SAVE_ROUND_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andSaveRoundTypeIsNotNull() {
            addCriterion("SAVE_ROUND_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSaveRoundTypeEqualTo(String value) {
            addCriterion("SAVE_ROUND_TYPE =", value, "saveRoundType");
            return (Criteria) this;
        }

        public Criteria andSaveRoundTypeNotEqualTo(String value) {
            addCriterion("SAVE_ROUND_TYPE <>", value, "saveRoundType");
            return (Criteria) this;
        }

        public Criteria andSaveRoundTypeGreaterThan(String value) {
            addCriterion("SAVE_ROUND_TYPE >", value, "saveRoundType");
            return (Criteria) this;
        }

        public Criteria andSaveRoundTypeGreaterThanOrEqualTo(String value) {
            addCriterion("SAVE_ROUND_TYPE >=", value, "saveRoundType");
            return (Criteria) this;
        }

        public Criteria andSaveRoundTypeLessThan(String value) {
            addCriterion("SAVE_ROUND_TYPE <", value, "saveRoundType");
            return (Criteria) this;
        }

        public Criteria andSaveRoundTypeLessThanOrEqualTo(String value) {
            addCriterion("SAVE_ROUND_TYPE <=", value, "saveRoundType");
            return (Criteria) this;
        }

        public Criteria andSaveRoundTypeLike(String value) {
            addCriterion("SAVE_ROUND_TYPE like", value, "saveRoundType");
            return (Criteria) this;
        }

        public Criteria andSaveRoundTypeNotLike(String value) {
            addCriterion("SAVE_ROUND_TYPE not like", value, "saveRoundType");
            return (Criteria) this;
        }

        public Criteria andSaveRoundTypeIn(List<String> values) {
            addCriterion("SAVE_ROUND_TYPE in", values, "saveRoundType");
            return (Criteria) this;
        }

        public Criteria andSaveRoundTypeNotIn(List<String> values) {
            addCriterion("SAVE_ROUND_TYPE not in", values, "saveRoundType");
            return (Criteria) this;
        }

        public Criteria andSaveRoundTypeBetween(String value1, String value2) {
            addCriterion("SAVE_ROUND_TYPE between", value1, value2, "saveRoundType");
            return (Criteria) this;
        }

        public Criteria andSaveRoundTypeNotBetween(String value1, String value2) {
            addCriterion("SAVE_ROUND_TYPE not between", value1, value2, "saveRoundType");
            return (Criteria) this;
        }

        public Criteria andDcSavePriceTypeIsNull() {
            addCriterion("DC_SAVE_PRICE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andDcSavePriceTypeIsNotNull() {
            addCriterion("DC_SAVE_PRICE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andDcSavePriceTypeEqualTo(String value) {
            addCriterion("DC_SAVE_PRICE_TYPE =", value, "dcSavePriceType");
            return (Criteria) this;
        }

        public Criteria andDcSavePriceTypeNotEqualTo(String value) {
            addCriterion("DC_SAVE_PRICE_TYPE <>", value, "dcSavePriceType");
            return (Criteria) this;
        }

        public Criteria andDcSavePriceTypeGreaterThan(String value) {
            addCriterion("DC_SAVE_PRICE_TYPE >", value, "dcSavePriceType");
            return (Criteria) this;
        }

        public Criteria andDcSavePriceTypeGreaterThanOrEqualTo(String value) {
            addCriterion("DC_SAVE_PRICE_TYPE >=", value, "dcSavePriceType");
            return (Criteria) this;
        }

        public Criteria andDcSavePriceTypeLessThan(String value) {
            addCriterion("DC_SAVE_PRICE_TYPE <", value, "dcSavePriceType");
            return (Criteria) this;
        }

        public Criteria andDcSavePriceTypeLessThanOrEqualTo(String value) {
            addCriterion("DC_SAVE_PRICE_TYPE <=", value, "dcSavePriceType");
            return (Criteria) this;
        }

        public Criteria andDcSavePriceTypeLike(String value) {
            addCriterion("DC_SAVE_PRICE_TYPE like", value, "dcSavePriceType");
            return (Criteria) this;
        }

        public Criteria andDcSavePriceTypeNotLike(String value) {
            addCriterion("DC_SAVE_PRICE_TYPE not like", value, "dcSavePriceType");
            return (Criteria) this;
        }

        public Criteria andDcSavePriceTypeIn(List<String> values) {
            addCriterion("DC_SAVE_PRICE_TYPE in", values, "dcSavePriceType");
            return (Criteria) this;
        }

        public Criteria andDcSavePriceTypeNotIn(List<String> values) {
            addCriterion("DC_SAVE_PRICE_TYPE not in", values, "dcSavePriceType");
            return (Criteria) this;
        }

        public Criteria andDcSavePriceTypeBetween(String value1, String value2) {
            addCriterion("DC_SAVE_PRICE_TYPE between", value1, value2, "dcSavePriceType");
            return (Criteria) this;
        }

        public Criteria andDcSavePriceTypeNotBetween(String value1, String value2) {
            addCriterion("DC_SAVE_PRICE_TYPE not between", value1, value2, "dcSavePriceType");
            return (Criteria) this;
        }

        public Criteria andSaveMinPayPriceIsNull() {
            addCriterion("SAVE_MIN_PAY_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andSaveMinPayPriceIsNotNull() {
            addCriterion("SAVE_MIN_PAY_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andSaveMinPayPriceEqualTo(Integer value) {
            addCriterion("SAVE_MIN_PAY_PRICE =", value, "saveMinPayPrice");
            return (Criteria) this;
        }

        public Criteria andSaveMinPayPriceNotEqualTo(Integer value) {
            addCriterion("SAVE_MIN_PAY_PRICE <>", value, "saveMinPayPrice");
            return (Criteria) this;
        }

        public Criteria andSaveMinPayPriceGreaterThan(Integer value) {
            addCriterion("SAVE_MIN_PAY_PRICE >", value, "saveMinPayPrice");
            return (Criteria) this;
        }

        public Criteria andSaveMinPayPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("SAVE_MIN_PAY_PRICE >=", value, "saveMinPayPrice");
            return (Criteria) this;
        }

        public Criteria andSaveMinPayPriceLessThan(Integer value) {
            addCriterion("SAVE_MIN_PAY_PRICE <", value, "saveMinPayPrice");
            return (Criteria) this;
        }

        public Criteria andSaveMinPayPriceLessThanOrEqualTo(Integer value) {
            addCriterion("SAVE_MIN_PAY_PRICE <=", value, "saveMinPayPrice");
            return (Criteria) this;
        }

        public Criteria andSaveMinPayPriceIn(List<Integer> values) {
            addCriterion("SAVE_MIN_PAY_PRICE in", values, "saveMinPayPrice");
            return (Criteria) this;
        }

        public Criteria andSaveMinPayPriceNotIn(List<Integer> values) {
            addCriterion("SAVE_MIN_PAY_PRICE not in", values, "saveMinPayPrice");
            return (Criteria) this;
        }

        public Criteria andSaveMinPayPriceBetween(Integer value1, Integer value2) {
            addCriterion("SAVE_MIN_PAY_PRICE between", value1, value2, "saveMinPayPrice");
            return (Criteria) this;
        }

        public Criteria andSaveMinPayPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("SAVE_MIN_PAY_PRICE not between", value1, value2, "saveMinPayPrice");
            return (Criteria) this;
        }

        public Criteria andSaveMaxPayPriceIsNull() {
            addCriterion("SAVE_MAX_PAY_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andSaveMaxPayPriceIsNotNull() {
            addCriterion("SAVE_MAX_PAY_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andSaveMaxPayPriceEqualTo(Integer value) {
            addCriterion("SAVE_MAX_PAY_PRICE =", value, "saveMaxPayPrice");
            return (Criteria) this;
        }

        public Criteria andSaveMaxPayPriceNotEqualTo(Integer value) {
            addCriterion("SAVE_MAX_PAY_PRICE <>", value, "saveMaxPayPrice");
            return (Criteria) this;
        }

        public Criteria andSaveMaxPayPriceGreaterThan(Integer value) {
            addCriterion("SAVE_MAX_PAY_PRICE >", value, "saveMaxPayPrice");
            return (Criteria) this;
        }

        public Criteria andSaveMaxPayPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("SAVE_MAX_PAY_PRICE >=", value, "saveMaxPayPrice");
            return (Criteria) this;
        }

        public Criteria andSaveMaxPayPriceLessThan(Integer value) {
            addCriterion("SAVE_MAX_PAY_PRICE <", value, "saveMaxPayPrice");
            return (Criteria) this;
        }

        public Criteria andSaveMaxPayPriceLessThanOrEqualTo(Integer value) {
            addCriterion("SAVE_MAX_PAY_PRICE <=", value, "saveMaxPayPrice");
            return (Criteria) this;
        }

        public Criteria andSaveMaxPayPriceIn(List<Integer> values) {
            addCriterion("SAVE_MAX_PAY_PRICE in", values, "saveMaxPayPrice");
            return (Criteria) this;
        }

        public Criteria andSaveMaxPayPriceNotIn(List<Integer> values) {
            addCriterion("SAVE_MAX_PAY_PRICE not in", values, "saveMaxPayPrice");
            return (Criteria) this;
        }

        public Criteria andSaveMaxPayPriceBetween(Integer value1, Integer value2) {
            addCriterion("SAVE_MAX_PAY_PRICE between", value1, value2, "saveMaxPayPrice");
            return (Criteria) this;
        }

        public Criteria andSaveMaxPayPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("SAVE_MAX_PAY_PRICE not between", value1, value2, "saveMaxPayPrice");
            return (Criteria) this;
        }

        public Criteria andMaxSavePointIsNull() {
            addCriterion("MAX_SAVE_POINT is null");
            return (Criteria) this;
        }

        public Criteria andMaxSavePointIsNotNull() {
            addCriterion("MAX_SAVE_POINT is not null");
            return (Criteria) this;
        }

        public Criteria andMaxSavePointEqualTo(Integer value) {
            addCriterion("MAX_SAVE_POINT =", value, "maxSavePoint");
            return (Criteria) this;
        }

        public Criteria andMaxSavePointNotEqualTo(Integer value) {
            addCriterion("MAX_SAVE_POINT <>", value, "maxSavePoint");
            return (Criteria) this;
        }

        public Criteria andMaxSavePointGreaterThan(Integer value) {
            addCriterion("MAX_SAVE_POINT >", value, "maxSavePoint");
            return (Criteria) this;
        }

        public Criteria andMaxSavePointGreaterThanOrEqualTo(Integer value) {
            addCriterion("MAX_SAVE_POINT >=", value, "maxSavePoint");
            return (Criteria) this;
        }

        public Criteria andMaxSavePointLessThan(Integer value) {
            addCriterion("MAX_SAVE_POINT <", value, "maxSavePoint");
            return (Criteria) this;
        }

        public Criteria andMaxSavePointLessThanOrEqualTo(Integer value) {
            addCriterion("MAX_SAVE_POINT <=", value, "maxSavePoint");
            return (Criteria) this;
        }

        public Criteria andMaxSavePointIn(List<Integer> values) {
            addCriterion("MAX_SAVE_POINT in", values, "maxSavePoint");
            return (Criteria) this;
        }

        public Criteria andMaxSavePointNotIn(List<Integer> values) {
            addCriterion("MAX_SAVE_POINT not in", values, "maxSavePoint");
            return (Criteria) this;
        }

        public Criteria andMaxSavePointBetween(Integer value1, Integer value2) {
            addCriterion("MAX_SAVE_POINT between", value1, value2, "maxSavePoint");
            return (Criteria) this;
        }

        public Criteria andMaxSavePointNotBetween(Integer value1, Integer value2) {
            addCriterion("MAX_SAVE_POINT not between", value1, value2, "maxSavePoint");
            return (Criteria) this;
        }

        public Criteria andPointUseTypeIsNull() {
            addCriterion("POINT_USE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andPointUseTypeIsNotNull() {
            addCriterion("POINT_USE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andPointUseTypeEqualTo(String value) {
            addCriterion("POINT_USE_TYPE =", value, "pointUseType");
            return (Criteria) this;
        }

        public Criteria andPointUseTypeNotEqualTo(String value) {
            addCriterion("POINT_USE_TYPE <>", value, "pointUseType");
            return (Criteria) this;
        }

        public Criteria andPointUseTypeGreaterThan(String value) {
            addCriterion("POINT_USE_TYPE >", value, "pointUseType");
            return (Criteria) this;
        }

        public Criteria andPointUseTypeGreaterThanOrEqualTo(String value) {
            addCriterion("POINT_USE_TYPE >=", value, "pointUseType");
            return (Criteria) this;
        }

        public Criteria andPointUseTypeLessThan(String value) {
            addCriterion("POINT_USE_TYPE <", value, "pointUseType");
            return (Criteria) this;
        }

        public Criteria andPointUseTypeLessThanOrEqualTo(String value) {
            addCriterion("POINT_USE_TYPE <=", value, "pointUseType");
            return (Criteria) this;
        }

        public Criteria andPointUseTypeLike(String value) {
            addCriterion("POINT_USE_TYPE like", value, "pointUseType");
            return (Criteria) this;
        }

        public Criteria andPointUseTypeNotLike(String value) {
            addCriterion("POINT_USE_TYPE not like", value, "pointUseType");
            return (Criteria) this;
        }

        public Criteria andPointUseTypeIn(List<String> values) {
            addCriterion("POINT_USE_TYPE in", values, "pointUseType");
            return (Criteria) this;
        }

        public Criteria andPointUseTypeNotIn(List<String> values) {
            addCriterion("POINT_USE_TYPE not in", values, "pointUseType");
            return (Criteria) this;
        }

        public Criteria andPointUseTypeBetween(String value1, String value2) {
            addCriterion("POINT_USE_TYPE between", value1, value2, "pointUseType");
            return (Criteria) this;
        }

        public Criteria andPointUseTypeNotBetween(String value1, String value2) {
            addCriterion("POINT_USE_TYPE not between", value1, value2, "pointUseType");
            return (Criteria) this;
        }

        public Criteria andPointUseUnitIsNull() {
            addCriterion("POINT_USE_UNIT is null");
            return (Criteria) this;
        }

        public Criteria andPointUseUnitIsNotNull() {
            addCriterion("POINT_USE_UNIT is not null");
            return (Criteria) this;
        }

        public Criteria andPointUseUnitEqualTo(String value) {
            addCriterion("POINT_USE_UNIT =", value, "pointUseUnit");
            return (Criteria) this;
        }

        public Criteria andPointUseUnitNotEqualTo(String value) {
            addCriterion("POINT_USE_UNIT <>", value, "pointUseUnit");
            return (Criteria) this;
        }

        public Criteria andPointUseUnitGreaterThan(String value) {
            addCriterion("POINT_USE_UNIT >", value, "pointUseUnit");
            return (Criteria) this;
        }

        public Criteria andPointUseUnitGreaterThanOrEqualTo(String value) {
            addCriterion("POINT_USE_UNIT >=", value, "pointUseUnit");
            return (Criteria) this;
        }

        public Criteria andPointUseUnitLessThan(String value) {
            addCriterion("POINT_USE_UNIT <", value, "pointUseUnit");
            return (Criteria) this;
        }

        public Criteria andPointUseUnitLessThanOrEqualTo(String value) {
            addCriterion("POINT_USE_UNIT <=", value, "pointUseUnit");
            return (Criteria) this;
        }

        public Criteria andPointUseUnitLike(String value) {
            addCriterion("POINT_USE_UNIT like", value, "pointUseUnit");
            return (Criteria) this;
        }

        public Criteria andPointUseUnitNotLike(String value) {
            addCriterion("POINT_USE_UNIT not like", value, "pointUseUnit");
            return (Criteria) this;
        }

        public Criteria andPointUseUnitIn(List<String> values) {
            addCriterion("POINT_USE_UNIT in", values, "pointUseUnit");
            return (Criteria) this;
        }

        public Criteria andPointUseUnitNotIn(List<String> values) {
            addCriterion("POINT_USE_UNIT not in", values, "pointUseUnit");
            return (Criteria) this;
        }

        public Criteria andPointUseUnitBetween(String value1, String value2) {
            addCriterion("POINT_USE_UNIT between", value1, value2, "pointUseUnit");
            return (Criteria) this;
        }

        public Criteria andPointUseUnitNotBetween(String value1, String value2) {
            addCriterion("POINT_USE_UNIT not between", value1, value2, "pointUseUnit");
            return (Criteria) this;
        }

        public Criteria andUseRoundTypeIsNull() {
            addCriterion("USE_ROUND_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andUseRoundTypeIsNotNull() {
            addCriterion("USE_ROUND_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andUseRoundTypeEqualTo(String value) {
            addCriterion("USE_ROUND_TYPE =", value, "useRoundType");
            return (Criteria) this;
        }

        public Criteria andUseRoundTypeNotEqualTo(String value) {
            addCriterion("USE_ROUND_TYPE <>", value, "useRoundType");
            return (Criteria) this;
        }

        public Criteria andUseRoundTypeGreaterThan(String value) {
            addCriterion("USE_ROUND_TYPE >", value, "useRoundType");
            return (Criteria) this;
        }

        public Criteria andUseRoundTypeGreaterThanOrEqualTo(String value) {
            addCriterion("USE_ROUND_TYPE >=", value, "useRoundType");
            return (Criteria) this;
        }

        public Criteria andUseRoundTypeLessThan(String value) {
            addCriterion("USE_ROUND_TYPE <", value, "useRoundType");
            return (Criteria) this;
        }

        public Criteria andUseRoundTypeLessThanOrEqualTo(String value) {
            addCriterion("USE_ROUND_TYPE <=", value, "useRoundType");
            return (Criteria) this;
        }

        public Criteria andUseRoundTypeLike(String value) {
            addCriterion("USE_ROUND_TYPE like", value, "useRoundType");
            return (Criteria) this;
        }

        public Criteria andUseRoundTypeNotLike(String value) {
            addCriterion("USE_ROUND_TYPE not like", value, "useRoundType");
            return (Criteria) this;
        }

        public Criteria andUseRoundTypeIn(List<String> values) {
            addCriterion("USE_ROUND_TYPE in", values, "useRoundType");
            return (Criteria) this;
        }

        public Criteria andUseRoundTypeNotIn(List<String> values) {
            addCriterion("USE_ROUND_TYPE not in", values, "useRoundType");
            return (Criteria) this;
        }

        public Criteria andUseRoundTypeBetween(String value1, String value2) {
            addCriterion("USE_ROUND_TYPE between", value1, value2, "useRoundType");
            return (Criteria) this;
        }

        public Criteria andUseRoundTypeNotBetween(String value1, String value2) {
            addCriterion("USE_ROUND_TYPE not between", value1, value2, "useRoundType");
            return (Criteria) this;
        }

        public Criteria andFixedPointIsNull() {
            addCriterion("FIXED_POINT is null");
            return (Criteria) this;
        }

        public Criteria andFixedPointIsNotNull() {
            addCriterion("FIXED_POINT is not null");
            return (Criteria) this;
        }

        public Criteria andFixedPointEqualTo(Integer value) {
            addCriterion("FIXED_POINT =", value, "fixedPoint");
            return (Criteria) this;
        }

        public Criteria andFixedPointNotEqualTo(Integer value) {
            addCriterion("FIXED_POINT <>", value, "fixedPoint");
            return (Criteria) this;
        }

        public Criteria andFixedPointGreaterThan(Integer value) {
            addCriterion("FIXED_POINT >", value, "fixedPoint");
            return (Criteria) this;
        }

        public Criteria andFixedPointGreaterThanOrEqualTo(Integer value) {
            addCriterion("FIXED_POINT >=", value, "fixedPoint");
            return (Criteria) this;
        }

        public Criteria andFixedPointLessThan(Integer value) {
            addCriterion("FIXED_POINT <", value, "fixedPoint");
            return (Criteria) this;
        }

        public Criteria andFixedPointLessThanOrEqualTo(Integer value) {
            addCriterion("FIXED_POINT <=", value, "fixedPoint");
            return (Criteria) this;
        }

        public Criteria andFixedPointIn(List<Integer> values) {
            addCriterion("FIXED_POINT in", values, "fixedPoint");
            return (Criteria) this;
        }

        public Criteria andFixedPointNotIn(List<Integer> values) {
            addCriterion("FIXED_POINT not in", values, "fixedPoint");
            return (Criteria) this;
        }

        public Criteria andFixedPointBetween(Integer value1, Integer value2) {
            addCriterion("FIXED_POINT between", value1, value2, "fixedPoint");
            return (Criteria) this;
        }

        public Criteria andFixedPointNotBetween(Integer value1, Integer value2) {
            addCriterion("FIXED_POINT not between", value1, value2, "fixedPoint");
            return (Criteria) this;
        }

        public Criteria andFixedRateIsNull() {
            addCriterion("FIXED_RATE is null");
            return (Criteria) this;
        }

        public Criteria andFixedRateIsNotNull() {
            addCriterion("FIXED_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andFixedRateEqualTo(Integer value) {
            addCriterion("FIXED_RATE =", value, "fixedRate");
            return (Criteria) this;
        }

        public Criteria andFixedRateNotEqualTo(Integer value) {
            addCriterion("FIXED_RATE <>", value, "fixedRate");
            return (Criteria) this;
        }

        public Criteria andFixedRateGreaterThan(Integer value) {
            addCriterion("FIXED_RATE >", value, "fixedRate");
            return (Criteria) this;
        }

        public Criteria andFixedRateGreaterThanOrEqualTo(Integer value) {
            addCriterion("FIXED_RATE >=", value, "fixedRate");
            return (Criteria) this;
        }

        public Criteria andFixedRateLessThan(Integer value) {
            addCriterion("FIXED_RATE <", value, "fixedRate");
            return (Criteria) this;
        }

        public Criteria andFixedRateLessThanOrEqualTo(Integer value) {
            addCriterion("FIXED_RATE <=", value, "fixedRate");
            return (Criteria) this;
        }

        public Criteria andFixedRateIn(List<Integer> values) {
            addCriterion("FIXED_RATE in", values, "fixedRate");
            return (Criteria) this;
        }

        public Criteria andFixedRateNotIn(List<Integer> values) {
            addCriterion("FIXED_RATE not in", values, "fixedRate");
            return (Criteria) this;
        }

        public Criteria andFixedRateBetween(Integer value1, Integer value2) {
            addCriterion("FIXED_RATE between", value1, value2, "fixedRate");
            return (Criteria) this;
        }

        public Criteria andFixedRateNotBetween(Integer value1, Integer value2) {
            addCriterion("FIXED_RATE not between", value1, value2, "fixedRate");
            return (Criteria) this;
        }

        public Criteria andMinPayPriceIsNull() {
            addCriterion("MIN_PAY_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andMinPayPriceIsNotNull() {
            addCriterion("MIN_PAY_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andMinPayPriceEqualTo(Integer value) {
            addCriterion("MIN_PAY_PRICE =", value, "minPayPrice");
            return (Criteria) this;
        }

        public Criteria andMinPayPriceNotEqualTo(Integer value) {
            addCriterion("MIN_PAY_PRICE <>", value, "minPayPrice");
            return (Criteria) this;
        }

        public Criteria andMinPayPriceGreaterThan(Integer value) {
            addCriterion("MIN_PAY_PRICE >", value, "minPayPrice");
            return (Criteria) this;
        }

        public Criteria andMinPayPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("MIN_PAY_PRICE >=", value, "minPayPrice");
            return (Criteria) this;
        }

        public Criteria andMinPayPriceLessThan(Integer value) {
            addCriterion("MIN_PAY_PRICE <", value, "minPayPrice");
            return (Criteria) this;
        }

        public Criteria andMinPayPriceLessThanOrEqualTo(Integer value) {
            addCriterion("MIN_PAY_PRICE <=", value, "minPayPrice");
            return (Criteria) this;
        }

        public Criteria andMinPayPriceIn(List<Integer> values) {
            addCriterion("MIN_PAY_PRICE in", values, "minPayPrice");
            return (Criteria) this;
        }

        public Criteria andMinPayPriceNotIn(List<Integer> values) {
            addCriterion("MIN_PAY_PRICE not in", values, "minPayPrice");
            return (Criteria) this;
        }

        public Criteria andMinPayPriceBetween(Integer value1, Integer value2) {
            addCriterion("MIN_PAY_PRICE between", value1, value2, "minPayPrice");
            return (Criteria) this;
        }

        public Criteria andMinPayPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("MIN_PAY_PRICE not between", value1, value2, "minPayPrice");
            return (Criteria) this;
        }

        public Criteria andMinUsePointIsNull() {
            addCriterion("MIN_USE_POINT is null");
            return (Criteria) this;
        }

        public Criteria andMinUsePointIsNotNull() {
            addCriterion("MIN_USE_POINT is not null");
            return (Criteria) this;
        }

        public Criteria andMinUsePointEqualTo(Integer value) {
            addCriterion("MIN_USE_POINT =", value, "minUsePoint");
            return (Criteria) this;
        }

        public Criteria andMinUsePointNotEqualTo(Integer value) {
            addCriterion("MIN_USE_POINT <>", value, "minUsePoint");
            return (Criteria) this;
        }

        public Criteria andMinUsePointGreaterThan(Integer value) {
            addCriterion("MIN_USE_POINT >", value, "minUsePoint");
            return (Criteria) this;
        }

        public Criteria andMinUsePointGreaterThanOrEqualTo(Integer value) {
            addCriterion("MIN_USE_POINT >=", value, "minUsePoint");
            return (Criteria) this;
        }

        public Criteria andMinUsePointLessThan(Integer value) {
            addCriterion("MIN_USE_POINT <", value, "minUsePoint");
            return (Criteria) this;
        }

        public Criteria andMinUsePointLessThanOrEqualTo(Integer value) {
            addCriterion("MIN_USE_POINT <=", value, "minUsePoint");
            return (Criteria) this;
        }

        public Criteria andMinUsePointIn(List<Integer> values) {
            addCriterion("MIN_USE_POINT in", values, "minUsePoint");
            return (Criteria) this;
        }

        public Criteria andMinUsePointNotIn(List<Integer> values) {
            addCriterion("MIN_USE_POINT not in", values, "minUsePoint");
            return (Criteria) this;
        }

        public Criteria andMinUsePointBetween(Integer value1, Integer value2) {
            addCriterion("MIN_USE_POINT between", value1, value2, "minUsePoint");
            return (Criteria) this;
        }

        public Criteria andMinUsePointNotBetween(Integer value1, Integer value2) {
            addCriterion("MIN_USE_POINT not between", value1, value2, "minUsePoint");
            return (Criteria) this;
        }

        public Criteria andMaxUsePointIsNull() {
            addCriterion("MAX_USE_POINT is null");
            return (Criteria) this;
        }

        public Criteria andMaxUsePointIsNotNull() {
            addCriterion("MAX_USE_POINT is not null");
            return (Criteria) this;
        }

        public Criteria andMaxUsePointEqualTo(Integer value) {
            addCriterion("MAX_USE_POINT =", value, "maxUsePoint");
            return (Criteria) this;
        }

        public Criteria andMaxUsePointNotEqualTo(Integer value) {
            addCriterion("MAX_USE_POINT <>", value, "maxUsePoint");
            return (Criteria) this;
        }

        public Criteria andMaxUsePointGreaterThan(Integer value) {
            addCriterion("MAX_USE_POINT >", value, "maxUsePoint");
            return (Criteria) this;
        }

        public Criteria andMaxUsePointGreaterThanOrEqualTo(Integer value) {
            addCriterion("MAX_USE_POINT >=", value, "maxUsePoint");
            return (Criteria) this;
        }

        public Criteria andMaxUsePointLessThan(Integer value) {
            addCriterion("MAX_USE_POINT <", value, "maxUsePoint");
            return (Criteria) this;
        }

        public Criteria andMaxUsePointLessThanOrEqualTo(Integer value) {
            addCriterion("MAX_USE_POINT <=", value, "maxUsePoint");
            return (Criteria) this;
        }

        public Criteria andMaxUsePointIn(List<Integer> values) {
            addCriterion("MAX_USE_POINT in", values, "maxUsePoint");
            return (Criteria) this;
        }

        public Criteria andMaxUsePointNotIn(List<Integer> values) {
            addCriterion("MAX_USE_POINT not in", values, "maxUsePoint");
            return (Criteria) this;
        }

        public Criteria andMaxUsePointBetween(Integer value1, Integer value2) {
            addCriterion("MAX_USE_POINT between", value1, value2, "maxUsePoint");
            return (Criteria) this;
        }

        public Criteria andMaxUsePointNotBetween(Integer value1, Integer value2) {
            addCriterion("MAX_USE_POINT not between", value1, value2, "maxUsePoint");
            return (Criteria) this;
        }

        public Criteria andDcRateIsNull() {
            addCriterion("DC_RATE is null");
            return (Criteria) this;
        }

        public Criteria andDcRateIsNotNull() {
            addCriterion("DC_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andDcRateEqualTo(Integer value) {
            addCriterion("DC_RATE =", value, "dcRate");
            return (Criteria) this;
        }

        public Criteria andDcRateNotEqualTo(Integer value) {
            addCriterion("DC_RATE <>", value, "dcRate");
            return (Criteria) this;
        }

        public Criteria andDcRateGreaterThan(Integer value) {
            addCriterion("DC_RATE >", value, "dcRate");
            return (Criteria) this;
        }

        public Criteria andDcRateGreaterThanOrEqualTo(Integer value) {
            addCriterion("DC_RATE >=", value, "dcRate");
            return (Criteria) this;
        }

        public Criteria andDcRateLessThan(Integer value) {
            addCriterion("DC_RATE <", value, "dcRate");
            return (Criteria) this;
        }

        public Criteria andDcRateLessThanOrEqualTo(Integer value) {
            addCriterion("DC_RATE <=", value, "dcRate");
            return (Criteria) this;
        }

        public Criteria andDcRateIn(List<Integer> values) {
            addCriterion("DC_RATE in", values, "dcRate");
            return (Criteria) this;
        }

        public Criteria andDcRateNotIn(List<Integer> values) {
            addCriterion("DC_RATE not in", values, "dcRate");
            return (Criteria) this;
        }

        public Criteria andDcRateBetween(Integer value1, Integer value2) {
            addCriterion("DC_RATE between", value1, value2, "dcRate");
            return (Criteria) this;
        }

        public Criteria andDcRateNotBetween(Integer value1, Integer value2) {
            addCriterion("DC_RATE not between", value1, value2, "dcRate");
            return (Criteria) this;
        }

        public Criteria andDcUnitIsNull() {
            addCriterion("DC_UNIT is null");
            return (Criteria) this;
        }

        public Criteria andDcUnitIsNotNull() {
            addCriterion("DC_UNIT is not null");
            return (Criteria) this;
        }

        public Criteria andDcUnitEqualTo(String value) {
            addCriterion("DC_UNIT =", value, "dcUnit");
            return (Criteria) this;
        }

        public Criteria andDcUnitNotEqualTo(String value) {
            addCriterion("DC_UNIT <>", value, "dcUnit");
            return (Criteria) this;
        }

        public Criteria andDcUnitGreaterThan(String value) {
            addCriterion("DC_UNIT >", value, "dcUnit");
            return (Criteria) this;
        }

        public Criteria andDcUnitGreaterThanOrEqualTo(String value) {
            addCriterion("DC_UNIT >=", value, "dcUnit");
            return (Criteria) this;
        }

        public Criteria andDcUnitLessThan(String value) {
            addCriterion("DC_UNIT <", value, "dcUnit");
            return (Criteria) this;
        }

        public Criteria andDcUnitLessThanOrEqualTo(String value) {
            addCriterion("DC_UNIT <=", value, "dcUnit");
            return (Criteria) this;
        }

        public Criteria andDcUnitLike(String value) {
            addCriterion("DC_UNIT like", value, "dcUnit");
            return (Criteria) this;
        }

        public Criteria andDcUnitNotLike(String value) {
            addCriterion("DC_UNIT not like", value, "dcUnit");
            return (Criteria) this;
        }

        public Criteria andDcUnitIn(List<String> values) {
            addCriterion("DC_UNIT in", values, "dcUnit");
            return (Criteria) this;
        }

        public Criteria andDcUnitNotIn(List<String> values) {
            addCriterion("DC_UNIT not in", values, "dcUnit");
            return (Criteria) this;
        }

        public Criteria andDcUnitBetween(String value1, String value2) {
            addCriterion("DC_UNIT between", value1, value2, "dcUnit");
            return (Criteria) this;
        }

        public Criteria andDcUnitNotBetween(String value1, String value2) {
            addCriterion("DC_UNIT not between", value1, value2, "dcUnit");
            return (Criteria) this;
        }

        public Criteria andDcRoundTypeIsNull() {
            addCriterion("DC_ROUND_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andDcRoundTypeIsNotNull() {
            addCriterion("DC_ROUND_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andDcRoundTypeEqualTo(String value) {
            addCriterion("DC_ROUND_TYPE =", value, "dcRoundType");
            return (Criteria) this;
        }

        public Criteria andDcRoundTypeNotEqualTo(String value) {
            addCriterion("DC_ROUND_TYPE <>", value, "dcRoundType");
            return (Criteria) this;
        }

        public Criteria andDcRoundTypeGreaterThan(String value) {
            addCriterion("DC_ROUND_TYPE >", value, "dcRoundType");
            return (Criteria) this;
        }

        public Criteria andDcRoundTypeGreaterThanOrEqualTo(String value) {
            addCriterion("DC_ROUND_TYPE >=", value, "dcRoundType");
            return (Criteria) this;
        }

        public Criteria andDcRoundTypeLessThan(String value) {
            addCriterion("DC_ROUND_TYPE <", value, "dcRoundType");
            return (Criteria) this;
        }

        public Criteria andDcRoundTypeLessThanOrEqualTo(String value) {
            addCriterion("DC_ROUND_TYPE <=", value, "dcRoundType");
            return (Criteria) this;
        }

        public Criteria andDcRoundTypeLike(String value) {
            addCriterion("DC_ROUND_TYPE like", value, "dcRoundType");
            return (Criteria) this;
        }

        public Criteria andDcRoundTypeNotLike(String value) {
            addCriterion("DC_ROUND_TYPE not like", value, "dcRoundType");
            return (Criteria) this;
        }

        public Criteria andDcRoundTypeIn(List<String> values) {
            addCriterion("DC_ROUND_TYPE in", values, "dcRoundType");
            return (Criteria) this;
        }

        public Criteria andDcRoundTypeNotIn(List<String> values) {
            addCriterion("DC_ROUND_TYPE not in", values, "dcRoundType");
            return (Criteria) this;
        }

        public Criteria andDcRoundTypeBetween(String value1, String value2) {
            addCriterion("DC_ROUND_TYPE between", value1, value2, "dcRoundType");
            return (Criteria) this;
        }

        public Criteria andDcRoundTypeNotBetween(String value1, String value2) {
            addCriterion("DC_ROUND_TYPE not between", value1, value2, "dcRoundType");
            return (Criteria) this;
        }

        public Criteria andDcMinPayPriceIsNull() {
            addCriterion("DC_MIN_PAY_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andDcMinPayPriceIsNotNull() {
            addCriterion("DC_MIN_PAY_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andDcMinPayPriceEqualTo(Integer value) {
            addCriterion("DC_MIN_PAY_PRICE =", value, "dcMinPayPrice");
            return (Criteria) this;
        }

        public Criteria andDcMinPayPriceNotEqualTo(Integer value) {
            addCriterion("DC_MIN_PAY_PRICE <>", value, "dcMinPayPrice");
            return (Criteria) this;
        }

        public Criteria andDcMinPayPriceGreaterThan(Integer value) {
            addCriterion("DC_MIN_PAY_PRICE >", value, "dcMinPayPrice");
            return (Criteria) this;
        }

        public Criteria andDcMinPayPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("DC_MIN_PAY_PRICE >=", value, "dcMinPayPrice");
            return (Criteria) this;
        }

        public Criteria andDcMinPayPriceLessThan(Integer value) {
            addCriterion("DC_MIN_PAY_PRICE <", value, "dcMinPayPrice");
            return (Criteria) this;
        }

        public Criteria andDcMinPayPriceLessThanOrEqualTo(Integer value) {
            addCriterion("DC_MIN_PAY_PRICE <=", value, "dcMinPayPrice");
            return (Criteria) this;
        }

        public Criteria andDcMinPayPriceIn(List<Integer> values) {
            addCriterion("DC_MIN_PAY_PRICE in", values, "dcMinPayPrice");
            return (Criteria) this;
        }

        public Criteria andDcMinPayPriceNotIn(List<Integer> values) {
            addCriterion("DC_MIN_PAY_PRICE not in", values, "dcMinPayPrice");
            return (Criteria) this;
        }

        public Criteria andDcMinPayPriceBetween(Integer value1, Integer value2) {
            addCriterion("DC_MIN_PAY_PRICE between", value1, value2, "dcMinPayPrice");
            return (Criteria) this;
        }

        public Criteria andDcMinPayPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("DC_MIN_PAY_PRICE not between", value1, value2, "dcMinPayPrice");
            return (Criteria) this;
        }

        public Criteria andMaxDcPriceIsNull() {
            addCriterion("MAX_DC_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andMaxDcPriceIsNotNull() {
            addCriterion("MAX_DC_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andMaxDcPriceEqualTo(Integer value) {
            addCriterion("MAX_DC_PRICE =", value, "maxDcPrice");
            return (Criteria) this;
        }

        public Criteria andMaxDcPriceNotEqualTo(Integer value) {
            addCriterion("MAX_DC_PRICE <>", value, "maxDcPrice");
            return (Criteria) this;
        }

        public Criteria andMaxDcPriceGreaterThan(Integer value) {
            addCriterion("MAX_DC_PRICE >", value, "maxDcPrice");
            return (Criteria) this;
        }

        public Criteria andMaxDcPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("MAX_DC_PRICE >=", value, "maxDcPrice");
            return (Criteria) this;
        }

        public Criteria andMaxDcPriceLessThan(Integer value) {
            addCriterion("MAX_DC_PRICE <", value, "maxDcPrice");
            return (Criteria) this;
        }

        public Criteria andMaxDcPriceLessThanOrEqualTo(Integer value) {
            addCriterion("MAX_DC_PRICE <=", value, "maxDcPrice");
            return (Criteria) this;
        }

        public Criteria andMaxDcPriceIn(List<Integer> values) {
            addCriterion("MAX_DC_PRICE in", values, "maxDcPrice");
            return (Criteria) this;
        }

        public Criteria andMaxDcPriceNotIn(List<Integer> values) {
            addCriterion("MAX_DC_PRICE not in", values, "maxDcPrice");
            return (Criteria) this;
        }

        public Criteria andMaxDcPriceBetween(Integer value1, Integer value2) {
            addCriterion("MAX_DC_PRICE between", value1, value2, "maxDcPrice");
            return (Criteria) this;
        }

        public Criteria andMaxDcPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("MAX_DC_PRICE not between", value1, value2, "maxDcPrice");
            return (Criteria) this;
        }

        public Criteria andRegUserIsNull() {
            addCriterion("REG_USER is null");
            return (Criteria) this;
        }

        public Criteria andRegUserIsNotNull() {
            addCriterion("REG_USER is not null");
            return (Criteria) this;
        }

        public Criteria andRegUserEqualTo(String value) {
            addCriterion("REG_USER =", value, "regUser");
            return (Criteria) this;
        }

        public Criteria andRegUserNotEqualTo(String value) {
            addCriterion("REG_USER <>", value, "regUser");
            return (Criteria) this;
        }

        public Criteria andRegUserGreaterThan(String value) {
            addCriterion("REG_USER >", value, "regUser");
            return (Criteria) this;
        }

        public Criteria andRegUserGreaterThanOrEqualTo(String value) {
            addCriterion("REG_USER >=", value, "regUser");
            return (Criteria) this;
        }

        public Criteria andRegUserLessThan(String value) {
            addCriterion("REG_USER <", value, "regUser");
            return (Criteria) this;
        }

        public Criteria andRegUserLessThanOrEqualTo(String value) {
            addCriterion("REG_USER <=", value, "regUser");
            return (Criteria) this;
        }

        public Criteria andRegUserLike(String value) {
            addCriterion("REG_USER like", value, "regUser");
            return (Criteria) this;
        }

        public Criteria andRegUserNotLike(String value) {
            addCriterion("REG_USER not like", value, "regUser");
            return (Criteria) this;
        }

        public Criteria andRegUserIn(List<String> values) {
            addCriterion("REG_USER in", values, "regUser");
            return (Criteria) this;
        }

        public Criteria andRegUserNotIn(List<String> values) {
            addCriterion("REG_USER not in", values, "regUser");
            return (Criteria) this;
        }

        public Criteria andRegUserBetween(String value1, String value2) {
            addCriterion("REG_USER between", value1, value2, "regUser");
            return (Criteria) this;
        }

        public Criteria andRegUserNotBetween(String value1, String value2) {
            addCriterion("REG_USER not between", value1, value2, "regUser");
            return (Criteria) this;
        }

        public Criteria andRegDtmIsNull() {
            addCriterion("REG_DTM is null");
            return (Criteria) this;
        }

        public Criteria andRegDtmIsNotNull() {
            addCriterion("REG_DTM is not null");
            return (Criteria) this;
        }

        public Criteria andRegDtmEqualTo(Date value) {
            addCriterion("REG_DTM =", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmNotEqualTo(Date value) {
            addCriterion("REG_DTM <>", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmGreaterThan(Date value) {
            addCriterion("REG_DTM >", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmGreaterThanOrEqualTo(Date value) {
            addCriterion("REG_DTM >=", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmLessThan(Date value) {
            addCriterion("REG_DTM <", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmLessThanOrEqualTo(Date value) {
            addCriterion("REG_DTM <=", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmIn(List<Date> values) {
            addCriterion("REG_DTM in", values, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmNotIn(List<Date> values) {
            addCriterion("REG_DTM not in", values, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmBetween(Date value1, Date value2) {
            addCriterion("REG_DTM between", value1, value2, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmNotBetween(Date value1, Date value2) {
            addCriterion("REG_DTM not between", value1, value2, "regDtm");
            return (Criteria) this;
        }

        public Criteria andChgUserIsNull() {
            addCriterion("CHG_USER is null");
            return (Criteria) this;
        }

        public Criteria andChgUserIsNotNull() {
            addCriterion("CHG_USER is not null");
            return (Criteria) this;
        }

        public Criteria andChgUserEqualTo(String value) {
            addCriterion("CHG_USER =", value, "chgUser");
            return (Criteria) this;
        }

        public Criteria andChgUserNotEqualTo(String value) {
            addCriterion("CHG_USER <>", value, "chgUser");
            return (Criteria) this;
        }

        public Criteria andChgUserGreaterThan(String value) {
            addCriterion("CHG_USER >", value, "chgUser");
            return (Criteria) this;
        }

        public Criteria andChgUserGreaterThanOrEqualTo(String value) {
            addCriterion("CHG_USER >=", value, "chgUser");
            return (Criteria) this;
        }

        public Criteria andChgUserLessThan(String value) {
            addCriterion("CHG_USER <", value, "chgUser");
            return (Criteria) this;
        }

        public Criteria andChgUserLessThanOrEqualTo(String value) {
            addCriterion("CHG_USER <=", value, "chgUser");
            return (Criteria) this;
        }

        public Criteria andChgUserLike(String value) {
            addCriterion("CHG_USER like", value, "chgUser");
            return (Criteria) this;
        }

        public Criteria andChgUserNotLike(String value) {
            addCriterion("CHG_USER not like", value, "chgUser");
            return (Criteria) this;
        }

        public Criteria andChgUserIn(List<String> values) {
            addCriterion("CHG_USER in", values, "chgUser");
            return (Criteria) this;
        }

        public Criteria andChgUserNotIn(List<String> values) {
            addCriterion("CHG_USER not in", values, "chgUser");
            return (Criteria) this;
        }

        public Criteria andChgUserBetween(String value1, String value2) {
            addCriterion("CHG_USER between", value1, value2, "chgUser");
            return (Criteria) this;
        }

        public Criteria andChgUserNotBetween(String value1, String value2) {
            addCriterion("CHG_USER not between", value1, value2, "chgUser");
            return (Criteria) this;
        }

        public Criteria andChgDtmIsNull() {
            addCriterion("CHG_DTM is null");
            return (Criteria) this;
        }

        public Criteria andChgDtmIsNotNull() {
            addCriterion("CHG_DTM is not null");
            return (Criteria) this;
        }

        public Criteria andChgDtmEqualTo(Date value) {
            addCriterion("CHG_DTM =", value, "chgDtm");
            return (Criteria) this;
        }

        public Criteria andChgDtmNotEqualTo(Date value) {
            addCriterion("CHG_DTM <>", value, "chgDtm");
            return (Criteria) this;
        }

        public Criteria andChgDtmGreaterThan(Date value) {
            addCriterion("CHG_DTM >", value, "chgDtm");
            return (Criteria) this;
        }

        public Criteria andChgDtmGreaterThanOrEqualTo(Date value) {
            addCriterion("CHG_DTM >=", value, "chgDtm");
            return (Criteria) this;
        }

        public Criteria andChgDtmLessThan(Date value) {
            addCriterion("CHG_DTM <", value, "chgDtm");
            return (Criteria) this;
        }

        public Criteria andChgDtmLessThanOrEqualTo(Date value) {
            addCriterion("CHG_DTM <=", value, "chgDtm");
            return (Criteria) this;
        }

        public Criteria andChgDtmIn(List<Date> values) {
            addCriterion("CHG_DTM in", values, "chgDtm");
            return (Criteria) this;
        }

        public Criteria andChgDtmNotIn(List<Date> values) {
            addCriterion("CHG_DTM not in", values, "chgDtm");
            return (Criteria) this;
        }

        public Criteria andChgDtmBetween(Date value1, Date value2) {
            addCriterion("CHG_DTM between", value1, value2, "chgDtm");
            return (Criteria) this;
        }

        public Criteria andChgDtmNotBetween(Date value1, Date value2) {
            addCriterion("CHG_DTM not between", value1, value2, "chgDtm");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MW_MS_COMP_PAYMENT
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 14 19:55:25 KST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MW_MS_COMP_PAYMENT
     *
     * @mbggenerated Fri Sep 14 19:55:25 KST 2012
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}