package com.wallet.membership.mapper;

import com.wallet.membership.model.CpnList;
import com.wallet.membership.model.CpnListExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface CpnListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpn_list
     *
     * @mbggenerated Thu Sep 20 17:55:39 KST 2012
     */
    int countByExample(CpnListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpn_list
     *
     * @mbggenerated Thu Sep 20 17:55:39 KST 2012
     */
    int deleteByExample(CpnListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpn_list
     *
     * @mbggenerated Thu Sep 20 17:55:39 KST 2012
     */
    @Delete({
        "delete from cpn_list",
        "where cpn_id = #{cpnId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String cpnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpn_list
     *
     * @mbggenerated Thu Sep 20 17:55:39 KST 2012
     */
    @Insert({
        "insert into cpn_list (cpn_id, memb_id, ",
        "part_v, disp_type, ",
        "name, use_name, use_code, ",
        "menufac_id, mode_v, ",
        "period_v, sort_v, ",
        "cate_id, chg_day, ",
        "val_sday, val_eday, ",
        "sday, eday, reg_user, ",
        "reg_day, chg_user, ",
        "memo, info, usim_mode, ",
        "prim_mode, aff_type, ",
        "main_display, disp_order, ",
        "PAY_FREE_YN, RECOMM_YN, RECOMM_SEQ, ",
        "POPU_SEQ, chg_tm, ",
        "COMP_PAY_YN, USIM_ID)",
        "values (#{cpnId,jdbcType=VARCHAR}, #{membId,jdbcType=VARCHAR}, ",
        "#{partV,jdbcType=VARCHAR}, #{dispType,jdbcType=VARCHAR}, ",
        "#{name,jdbcType=VARCHAR}, #{useName,jdbcType=VARCHAR}, #{useCode,jdbcType=VARCHAR}, ",
        "#{menufacId,jdbcType=VARCHAR}, #{modeV,jdbcType=VARCHAR}, ",
        "#{periodV,jdbcType=VARCHAR}, #{sortV,jdbcType=VARCHAR}, ",
        "#{cateId,jdbcType=VARCHAR}, #{chgDay,jdbcType=VARCHAR}, ",
        "#{valSday,jdbcType=VARCHAR}, #{valEday,jdbcType=VARCHAR}, ",
        "#{sday,jdbcType=VARCHAR}, #{eday,jdbcType=VARCHAR}, #{regUser,jdbcType=VARCHAR}, ",
        "#{regDay,jdbcType=VARCHAR}, #{chgUser,jdbcType=VARCHAR}, ",
        "#{memo,jdbcType=VARCHAR}, #{info,jdbcType=VARCHAR}, #{usimMode,jdbcType=VARCHAR}, ",
        "#{primMode,jdbcType=CHAR}, #{affType,jdbcType=VARCHAR}, ",
        "#{mainDisplay,jdbcType=CHAR}, #{dispOrder,jdbcType=VARCHAR}, ",
        "#{payFreeYn,jdbcType=CHAR}, #{recommYn,jdbcType=CHAR}, #{recommSeq,jdbcType=INTEGER}, ",
        "#{popuSeq,jdbcType=INTEGER}, #{chgTm,jdbcType=VARCHAR}, ",
        "#{compPayYn,jdbcType=CHAR}, #{usimId,jdbcType=VARCHAR})"
    })
    int insert(CpnList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpn_list
     *
     * @mbggenerated Thu Sep 20 17:55:39 KST 2012
     */
    int insertSelective(CpnList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpn_list
     *
     * @mbggenerated Thu Sep 20 17:55:39 KST 2012
     */
    List<CpnList> selectByExample(CpnListExample example);
    List<CpnList> CouponOrderByExample(CpnListExample example);
    int CouponOrderCount(CpnListExample example);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpn_list
     *
     * @mbggenerated Thu Sep 20 17:55:39 KST 2012
     */
    @Select({
        "select",
        "cpn_id, memb_id, part_v, disp_type, name, use_name, use_code, menufac_id, mode_v, ",
        "period_v, sort_v, cate_id, chg_day, val_sday, val_eday, sday, eday, reg_user, ",
        "reg_day, chg_user, memo, info, usim_mode, prim_mode, aff_type, main_display, ",
        "disp_order, PAY_FREE_YN, RECOMM_YN, RECOMM_SEQ, POPU_SEQ, chg_tm, COMP_PAY_YN, ",
        "USIM_ID",
        "from cpn_list",
        "where cpn_id = #{cpnId,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    CpnList selectByPrimaryKey(String cpnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpn_list
     *
     * @mbggenerated Thu Sep 20 17:55:39 KST 2012
     */
    int updateByExampleSelective(@Param("record") CpnList record, @Param("example") CpnListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpn_list
     *
     * @mbggenerated Thu Sep 20 17:55:39 KST 2012
     */
    int updateByExample(@Param("record") CpnList record, @Param("example") CpnListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpn_list
     *
     * @mbggenerated Thu Sep 20 17:55:39 KST 2012
     */
    int updateByPrimaryKeySelective(CpnList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpn_list
     *
     * @mbggenerated Thu Sep 20 17:55:39 KST 2012
     */
    @Update({
        "update cpn_list",
        "set memb_id = #{membId,jdbcType=VARCHAR},",
          "part_v = #{partV,jdbcType=VARCHAR},",
          "disp_type = #{dispType,jdbcType=VARCHAR},",
          "name = #{name,jdbcType=VARCHAR},",
          "use_name = #{useName,jdbcType=VARCHAR},",
          "use_code = #{useCode,jdbcType=VARCHAR},",
          "menufac_id = #{menufacId,jdbcType=VARCHAR},",
          "mode_v = #{modeV,jdbcType=VARCHAR},",
          "period_v = #{periodV,jdbcType=VARCHAR},",
          "sort_v = #{sortV,jdbcType=VARCHAR},",
          "cate_id = #{cateId,jdbcType=VARCHAR},",
          "chg_day = #{chgDay,jdbcType=VARCHAR},",
          "val_sday = #{valSday,jdbcType=VARCHAR},",
          "val_eday = #{valEday,jdbcType=VARCHAR},",
          "sday = #{sday,jdbcType=VARCHAR},",
          "eday = #{eday,jdbcType=VARCHAR},",
          "reg_user = #{regUser,jdbcType=VARCHAR},",
          "reg_day = #{regDay,jdbcType=VARCHAR},",
          "chg_user = #{chgUser,jdbcType=VARCHAR},",
          "memo = #{memo,jdbcType=VARCHAR},",
          "info = #{info,jdbcType=VARCHAR},",
          "usim_mode = #{usimMode,jdbcType=VARCHAR},",
          "prim_mode = #{primMode,jdbcType=CHAR},",
          "aff_type = #{affType,jdbcType=VARCHAR},",
          "main_display = #{mainDisplay,jdbcType=CHAR},",
          "disp_order = #{dispOrder,jdbcType=VARCHAR},",
          "PAY_FREE_YN = #{payFreeYn,jdbcType=CHAR},",
          "RECOMM_YN = #{recommYn,jdbcType=CHAR},",
          "RECOMM_SEQ = #{recommSeq,jdbcType=INTEGER},",
          "POPU_SEQ = #{popuSeq,jdbcType=INTEGER},",
          "chg_tm = #{chgTm,jdbcType=VARCHAR},",
          "COMP_PAY_YN = #{compPayYn,jdbcType=CHAR},",
          "USIM_ID = #{usimId,jdbcType=VARCHAR}",
        "where cpn_id = #{cpnId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(CpnList record);
}