package com.wallet.membership.mapper;

import com.wallet.membership.model.MwCmCompany;
import com.wallet.membership.model.MwCmCompanyExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface MwCmCompanyMapper {

	List<MwCmCompany> nextBrandId(MwCmCompanyExample example);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MW_CM_COMPANY
	 * @mbggenerated  Thu Sep 06 14:03:53 KST 2012
	 */
	int countByExample(MwCmCompanyExample example);
	int FranchiseSelectByCount(MwCmCompanyExample example);
	int MemberStoreSelectByCount(MwCmCompanyExample example);
	int MemberPatnerSelectByCount(MwCmCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MW_CM_COMPANY
	 * @mbggenerated  Thu Sep 06 14:03:53 KST 2012
	 */
	int deleteByExample(MwCmCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MW_CM_COMPANY
	 * @mbggenerated  Thu Sep 06 14:03:53 KST 2012
	 */
	@Delete({ "delete from MW_CM_COMPANY",
			"where COMP_ID = #{compId,jdbcType=VARCHAR}" })
	int deleteByPrimaryKey(String compId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MW_CM_COMPANY
	 * @mbggenerated  Thu Sep 06 14:03:53 KST 2012
	 */
	@Insert({
			"insert into MW_CM_COMPANY (COMP_ID, COMP_NAME, ",
			"ALLY_STAT, UPPER_COMP_ID, ",
			"COMP_LEVEL_TYPE, COMP_TYPE, ",
			"CPN_RTIME_ISSUE_YN, COMPLEX_PAYMENT_YN, ",
			"ZIPCODE, ADDR, ADDR_DETAIL, ",
			"MAIN_NUMBER, PHONE_NO, ",
			"MOBILE_PHONE, EMAIL, ",
			"LIMIT_AMOUNT_DAY, LIMIT_AMOUNT_WEEK, ",
			"LIMIT_AMOUNT_MONTH, LIMIT_AMOUNT_YEAR, ",
			"BUSINESS_NO, GPS_X, ",
			"GPS_Y, SHOP_INFO_URL, ",
			"COMP_SHOP_ID, MEMB_ID, ",
			"REG_USER, REG_DTM, ",
			"CHG_USER, CHG_DTM, ",
			"REGION_TYPE, MANAGER_NAME, ",
			"MEMO, MID_SHOP_ID)",
			"values (#{compId,jdbcType=VARCHAR}, #{compName,jdbcType=VARCHAR}, ",
			"#{allyStat,jdbcType=CHAR}, #{upperCompId,jdbcType=VARCHAR}, ",
			"#{compLevelType,jdbcType=CHAR}, #{compType,jdbcType=CHAR}, ",
			"#{cpnRtimeIssueYn,jdbcType=CHAR}, #{complexPaymentYn,jdbcType=CHAR}, ",
			"#{compPayMembYn,jdbcType=CHAR}, #{compPayMembSave,jdbcType=CHAR}, ",
			"#{compPayMembUse,jdbcType=CHAR}, #{compPayMembDc,jdbcType=CHAR}, ",
			"#{compPayCpnYn,jdbcType=CHAR}, #{compPayStampYn,jdbcType=CHAR}, ",
			"#{zipcode,jdbcType=VARCHAR}, #{addr,jdbcType=VARCHAR}, #{addrDetail,jdbcType=VARCHAR}, ",
			"#{mainNumber,jdbcType=VARCHAR}, #{phoneNo,jdbcType=VARCHAR}, ",
			"#{mobilePhone,jdbcType=VARCHAR}, #{email,jdbcType=VARCHAR}, ",
			"#{limitAmountDay,jdbcType=INTEGER}, #{limitAmountWeek,jdbcType=INTEGER}, ",
			"#{limitAmountMonth,jdbcType=INTEGER}, #{limitAmountYear,jdbcType=INTEGER}, ",
			"#{businessNo,jdbcType=VARCHAR}, #{gpsX,jdbcType=VARCHAR}, ",
			"#{gpsY,jdbcType=VARCHAR}, #{shopInfoUrl,jdbcType=VARCHAR}, ",
			"#{compShopId,jdbcType=VARCHAR}, #{membId,jdbcType=VARCHAR}, ",
			"#{regUser,jdbcType=VARCHAR}, #{regDtm,jdbcType=TIMESTAMP}, ",
			"#{chgUser,jdbcType=VARCHAR}, #{chgDtm,jdbcType=TIMESTAMP}, ",
			"#{regionType,jdbcType=CHAR}, #{managerName,jdbcType=VARCHAR}, ",
			"#{memo,jdbcType=LONGVARCHAR}, #{midShopId,jdbcType=VARCHAR})" })
	int insert(MwCmCompany record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MW_CM_COMPANY
	 * @mbggenerated  Thu Sep 06 14:03:53 KST 2012
	 */
	int insertSelective(MwCmCompany record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MW_CM_COMPANY
	 * @mbggenerated  Thu Sep 06 14:03:53 KST 2012
	 */
	
	int partnerInsertSelective(MwCmCompany record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MW_CM_COMPANY
	 * @mbggenerated  Thu Sep 06 14:03:53 KST 2012
	 */
	
	int storeInsertSelective(MwCmCompany record);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MW_CM_COMPANY
	 * @mbggenerated  Thu Sep 06 14:03:53 KST 2012
	 */
	
	int FranchiseInsertSelective(MwCmCompany record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MW_CM_COMPANY
	 * @mbggenerated  Thu Sep 06 14:03:53 KST 2012
	 */
	List<MwCmCompany> selectByExampleWithBLOBs(MwCmCompanyExample example);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MW_CM_COMPANY
	 * @mbggenerated  Thu Sep 06 14:03:53 KST 2012
	 */
	List<MwCmCompany> selectByExample(MwCmCompanyExample example);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MW_CM_COMPANY
	 * @mbggenerated  Thu Sep 06 14:03:53 KST 2012
	 */
	List<MwCmCompany> MemberPatnerSelectByExample(MwCmCompanyExample example);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MW_CM_COMPANY
	 * @mbggenerated  Thu Sep 06 14:03:53 KST 2012
	 */
	List<MwCmCompany> MemberStoreSelectByExample(MwCmCompanyExample example);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MW_CM_COMPANY
	 * @mbggenerated  Thu Sep 06 14:03:53 KST 2012
	 */
	List<MwCmCompany> FranchiseSelectByExample(MwCmCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MW_CM_COMPANY
	 * @mbggenerated  Thu Sep 06 14:03:53 KST 2012
	 */
	@Select({
			"select",
			"COMP_ID, COMP_NAME, ALLY_STAT, UPPER_COMP_ID, COMP_LEVEL_TYPE, COMP_TYPE, CPN_RTIME_ISSUE_YN, ",
			"COMPLEX_PAYMENT_YN, ZIPCODE, ADDR, ADDR_DETAIL, ",
			"MAIN_NUMBER, PHONE_NO, MOBILE_PHONE, EMAIL, LIMIT_AMOUNT_DAY, LIMIT_AMOUNT_WEEK, ",
			"LIMIT_AMOUNT_MONTH, LIMIT_AMOUNT_YEAR, BUSINESS_NO, GPS_X, GPS_Y, SHOP_INFO_URL, ",
			"COMP_SHOP_ID, MEMB_ID, REG_USER, REG_DTM, CHG_USER, CHG_DTM, REGION_TYPE, MANAGER_NAME, ",
			"MEMO", "from MW_CM_COMPANY",
			"where COMP_ID = #{compId,jdbcType=VARCHAR}" })
	@ResultMap("ResultMapWithBLOBs")
	MwCmCompany selectByPrimaryKey(String compId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MW_CM_COMPANY
	 * @mbggenerated  Thu Sep 06 14:03:53 KST 2012
	 */
	int updateByExampleSelective(@Param("record") MwCmCompany record,
			@Param("example") MwCmCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MW_CM_COMPANY
	 * @mbggenerated  Thu Sep 06 14:03:53 KST 2012
	 */
	int updateByExampleWithBLOBs(@Param("record") MwCmCompany record,
			@Param("example") MwCmCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MW_CM_COMPANY
	 * @mbggenerated  Thu Sep 06 14:03:53 KST 2012
	 */
	int updateByExample(@Param("record") MwCmCompany record,
			@Param("example") MwCmCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MW_CM_COMPANY
	 * @mbggenerated  Thu Sep 06 14:03:53 KST 2012
	 */
	int updateByPrimaryKeySelective(MwCmCompany record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MW_CM_COMPANY
	 * @mbggenerated  Thu Sep 06 14:03:53 KST 2012
	 */
	@Update({ "update MW_CM_COMPANY",
			"set COMP_NAME = #{compName,jdbcType=VARCHAR},",
			"ALLY_STAT = #{allyStat,jdbcType=CHAR},",
			"UPPER_COMP_ID = #{upperCompId,jdbcType=VARCHAR},",
			"COMP_LEVEL_TYPE = #{compLevelType,jdbcType=CHAR},",
			"COMP_TYPE = #{compType,jdbcType=CHAR},",
			"CPN_RTIME_ISSUE_YN = #{cpnRtimeIssueYn,jdbcType=CHAR},",
			"COMPLEX_PAYMENT_YN = #{complexPaymentYn,jdbcType=CHAR},",
			"ZIPCODE = #{zipcode,jdbcType=VARCHAR},",
			"ADDR = #{addr,jdbcType=VARCHAR},",
			"ADDR_DETAIL = #{addrDetail,jdbcType=VARCHAR},",
			"MAIN_NUMBER = #{mainNumber,jdbcType=VARCHAR},",
			"PHONE_NO = #{phoneNo,jdbcType=VARCHAR},",
			"MOBILE_PHONE = #{mobilePhone,jdbcType=VARCHAR},",
			"EMAIL = #{email,jdbcType=VARCHAR},",
			"LIMIT_AMOUNT_DAY = #{limitAmountDay,jdbcType=INTEGER},",
			"LIMIT_AMOUNT_WEEK = #{limitAmountWeek,jdbcType=INTEGER},",
			"LIMIT_AMOUNT_MONTH = #{limitAmountMonth,jdbcType=INTEGER},",
			"LIMIT_AMOUNT_YEAR = #{limitAmountYear,jdbcType=INTEGER},",
			"BUSINESS_NO = #{businessNo,jdbcType=VARCHAR},",
			"GPS_X = #{gpsX,jdbcType=VARCHAR},", "GPS_Y = #{gpsY,jdbcType=VARCHAR},",
			"SHOP_INFO_URL = #{shopInfoUrl,jdbcType=VARCHAR},",
			"COMP_SHOP_ID = #{compShopId,jdbcType=VARCHAR},",
			"MEMB_ID = #{membId,jdbcType=VARCHAR},",
			"REG_USER = #{regUser,jdbcType=VARCHAR},",
			"REG_DTM = #{regDtm,jdbcType=TIMESTAMP},",
			"CHG_USER = #{chgUser,jdbcType=VARCHAR},",
			"CHG_DTM = #{chgDtm,jdbcType=TIMESTAMP},",
			"REGION_TYPE = #{regionType,jdbcType=CHAR},",
			"MANAGER_NAME = #{managerName,jdbcType=VARCHAR},",
			"MEMO = #{memo,jdbcType=LONGVARCHAR}",
			"where COMP_ID = #{compId,jdbcType=VARCHAR}" })
	int updateByPrimaryKeyWithBLOBs(MwCmCompany record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MW_CM_COMPANY
	 * @mbggenerated  Thu Sep 06 14:03:53 KST 2012
	 */
	@Update({ "update MW_CM_COMPANY",
			"set COMP_NAME = #{compName,jdbcType=VARCHAR},",
			"ALLY_STAT = #{allyStat,jdbcType=CHAR},",
			"UPPER_COMP_ID = #{upperCompId,jdbcType=VARCHAR},",
			"COMP_LEVEL_TYPE = #{compLevelType,jdbcType=CHAR},",
			"COMP_TYPE = #{compType,jdbcType=CHAR},",
			"CPN_RTIME_ISSUE_YN = #{cpnRtimeIssueYn,jdbcType=CHAR},",
			"COMPLEX_PAYMENT_YN = #{complexPaymentYn,jdbcType=CHAR},",
			"ZIPCODE = #{zipcode,jdbcType=VARCHAR},",
			"ADDR = #{addr,jdbcType=VARCHAR},",
			"ADDR_DETAIL = #{addrDetail,jdbcType=VARCHAR},",
			"MAIN_NUMBER = #{mainNumber,jdbcType=VARCHAR},",
			"PHONE_NO = #{phoneNo,jdbcType=VARCHAR},",
			"MOBILE_PHONE = #{mobilePhone,jdbcType=VARCHAR},",
			"EMAIL = #{email,jdbcType=VARCHAR},",
			"LIMIT_AMOUNT_DAY = #{limitAmountDay,jdbcType=INTEGER},",
			"LIMIT_AMOUNT_WEEK = #{limitAmountWeek,jdbcType=INTEGER},",
			"LIMIT_AMOUNT_MONTH = #{limitAmountMonth,jdbcType=INTEGER},",
			"LIMIT_AMOUNT_YEAR = #{limitAmountYear,jdbcType=INTEGER},",
			"BUSINESS_NO = #{businessNo,jdbcType=VARCHAR},",
			"GPS_X = #{gpsX,jdbcType=VARCHAR},", "GPS_Y = #{gpsY,jdbcType=VARCHAR},",
			"SHOP_INFO_URL = #{shopInfoUrl,jdbcType=VARCHAR},",
			"COMP_SHOP_ID = #{compShopId,jdbcType=VARCHAR},",
			"MEMB_ID = #{membId,jdbcType=VARCHAR},",
			"REG_USER = #{regUser,jdbcType=VARCHAR},",
			"REG_DTM = #{regDtm,jdbcType=TIMESTAMP},",
			"CHG_USER = #{chgUser,jdbcType=VARCHAR},",
			"CHG_DTM = #{chgDtm,jdbcType=TIMESTAMP},",
			"REGION_TYPE = #{regionType,jdbcType=CHAR},",
			"MANAGER_NAME = #{managerName,jdbcType=VARCHAR}",
			"where COMP_ID = #{compId,jdbcType=VARCHAR}" }) 
	int updateByPrimaryKey(MwCmCompany record);
}