package com.wallet.membership.mapper;

import com.wallet.membership.model.MwCmAdminInfo;
import com.wallet.membership.model.MwCmAdminInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface MwCmAdminInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_ADMIN_INFO
     *
     * @mbggenerated Wed Sep 26 13:24:52 KST 2012
     */
    int countByExample(MwCmAdminInfoExample example);
    int selectByAdminCount(MwCmAdminInfoExample example);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_ADMIN_INFO
     *
     * @mbggenerated Wed Sep 26 13:24:52 KST 2012
     */
    int deleteByExample(MwCmAdminInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_ADMIN_INFO
     *
     * @mbggenerated Wed Sep 26 13:24:52 KST 2012
     */
    @Delete({
        "delete from MW_CM_ADMIN_INFO",
        "where ADMIN_ID = #{adminId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_ADMIN_INFO
     *
     * @mbggenerated Wed Sep 26 13:24:52 KST 2012
     */
    @Insert({
        "insert into MW_CM_ADMIN_INFO (ADMIN_ID, ADMIN_LEVEL, ",
        "COMP_ID, BRAN_ID, ",
        "SHOP_ID, ADMIN_NAME, ",
        "IP, MOBILE_PHONE, ",
        "EMERGEN_PHONE, EMAIL, ",
        "REG_USER, REG_DTM, ",
        "CHG_USER, CHG_DTM)",
        "values (#{adminId,jdbcType=VARCHAR}, #{adminLevel,jdbcType=CHAR}, ",
        "#{compId,jdbcType=VARCHAR}, #{branId,jdbcType=VARCHAR}, ",
        "#{shopId,jdbcType=VARCHAR}, #{adminName,jdbcType=VARCHAR}, ",
        "#{ip,jdbcType=VARCHAR}, #{mobilePhone,jdbcType=VARCHAR}, ",
        "#{emergenPhone,jdbcType=VARCHAR}, #{email,jdbcType=VARCHAR}, ",
        "#{regUser,jdbcType=VARCHAR}, #{regDtm,jdbcType=TIMESTAMP}, ",
        "#{chgUser,jdbcType=VARCHAR}, #{chgDtm,jdbcType=TIMESTAMP})"
    })
    int insert(MwCmAdminInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_ADMIN_INFO
     *
     * @mbggenerated Wed Sep 26 13:24:52 KST 2012
     */
    int insertSelective(MwCmAdminInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_ADMIN_INFO
     *
     * @mbggenerated Wed Sep 26 13:24:52 KST 2012
     */
    List<MwCmAdminInfo> selectByExample(MwCmAdminInfoExample example);
    List<MwCmAdminInfo> selectByAdmin(MwCmAdminInfoExample example);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_ADMIN_INFO
     *
     * @mbggenerated Wed Sep 26 13:24:52 KST 2012
     */
    @Select({
        "select",
        "ADMIN_ID, ADMIN_LEVEL, COMP_ID, BRAN_ID, SHOP_ID, ADMIN_NAME, IP, MOBILE_PHONE, ",
        "EMERGEN_PHONE, EMAIL, REG_USER, REG_DTM, CHG_USER, CHG_DTM",
        "from MW_CM_ADMIN_INFO",
        "where ADMIN_ID = #{adminId,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    MwCmAdminInfo selectByPrimaryKey(String adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_ADMIN_INFO
     *
     * @mbggenerated Wed Sep 26 13:24:52 KST 2012
     */
    int updateByExampleSelective(@Param("record") MwCmAdminInfo record, @Param("example") MwCmAdminInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_ADMIN_INFO
     *
     * @mbggenerated Wed Sep 26 13:24:52 KST 2012
     */
    int updateByExample(@Param("record") MwCmAdminInfo record, @Param("example") MwCmAdminInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_ADMIN_INFO
     *
     * @mbggenerated Wed Sep 26 13:24:52 KST 2012
     */
    int updateByPrimaryKeySelective(MwCmAdminInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_ADMIN_INFO
     *
     * @mbggenerated Wed Sep 26 13:24:52 KST 2012
     */
    @Update({
        "update MW_CM_ADMIN_INFO",
        "set ADMIN_LEVEL = #{adminLevel,jdbcType=CHAR},",
          "COMP_ID = #{compId,jdbcType=VARCHAR},",
          "BRAN_ID = #{branId,jdbcType=VARCHAR},",
          "SHOP_ID = #{shopId,jdbcType=VARCHAR},",
          "ADMIN_NAME = #{adminName,jdbcType=VARCHAR},",
          "IP = #{ip,jdbcType=VARCHAR},",
          "MOBILE_PHONE = #{mobilePhone,jdbcType=VARCHAR},",
          "EMERGEN_PHONE = #{emergenPhone,jdbcType=VARCHAR},",
          "EMAIL = #{email,jdbcType=VARCHAR},",
          "REG_USER = #{regUser,jdbcType=VARCHAR},",
          "REG_DTM = #{regDtm,jdbcType=TIMESTAMP},",
          "CHG_USER = #{chgUser,jdbcType=VARCHAR},",
          "CHG_DTM = #{chgDtm,jdbcType=TIMESTAMP}",
        "where ADMIN_ID = #{adminId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(MwCmAdminInfo record);
}