package com.wallet.membership.mapper;

import com.wallet.membership.model.MwCmPayCompany;
import com.wallet.membership.model.MwCmPayCompanyExample;
import com.wallet.membership.model.MwCmPayCompanyWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface MwCmPayCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_PAYCOMPANY
     *
     * @mbggenerated Thu Sep 06 15:42:10 KST 2012
     */
    int countByExample(MwCmPayCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_PAYCOMPANY
     *
     * @mbggenerated Thu Sep 06 15:42:10 KST 2012
     */
    int deleteByExample(MwCmPayCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_PAYCOMPANY
     *
     * @mbggenerated Thu Sep 06 15:42:10 KST 2012
     */
    @Delete({
        "delete from MW_CM_PAYCOMPANY",
        "where PAYCOMP_ID = #{paycompId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String paycompId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_PAYCOMPANY
     *
     * @mbggenerated Thu Sep 06 15:42:10 KST 2012
     */
    @Insert({
        "insert into MW_CM_PAYCOMPANY (PAYCOMP_ID, PAYCOMP_NAME, ",
        "ALLY_STAT, BUSINESS_NO, ",
        "ZIPCODE, ADDR, ADDR_DETAIL, ",
        "MAIN_NUMBER, PHONE_NO, ",
        "MOBILE_PHONE, EMAIL, ",
        "REG_USER, REG_DTM, ",
        "CHG_USER, CHG_DTM, ",
        "MANAGER_NAME, DC_METHOD_INFO, ",
        "MEMO)",
        "values (#{paycompId,jdbcType=VARCHAR}, #{paycompName,jdbcType=VARCHAR}, ",
        "#{allyStat,jdbcType=CHAR}, #{businessNo,jdbcType=VARCHAR}, ",
        "#{zipcode,jdbcType=VARCHAR}, #{addr,jdbcType=VARCHAR}, #{addrDetail,jdbcType=VARCHAR}, ",
        "#{mainNumber,jdbcType=VARCHAR}, #{phoneNo,jdbcType=VARCHAR}, ",
        "#{mobilePhone,jdbcType=VARCHAR}, #{email,jdbcType=VARCHAR}, ",
        "#{regUser,jdbcType=VARCHAR}, #{regDtm,jdbcType=TIMESTAMP}, ",
        "#{chgUser,jdbcType=VARCHAR}, #{chgDtm,jdbcType=TIMESTAMP}, ",
        "#{managerName,jdbcType=VARCHAR}, #{dcMethodInfo,jdbcType=LONGVARCHAR}, ",
        "#{memo,jdbcType=LONGVARCHAR})"
    })
    int insert(MwCmPayCompanyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_PAYCOMPANY
     *
     * @mbggenerated Thu Sep 06 15:42:10 KST 2012
     */
    int insertSelective(MwCmPayCompanyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_PAYCOMPANY
     *
     * @mbggenerated Thu Sep 06 15:42:10 KST 2012
     */
    List<MwCmPayCompanyWithBLOBs> selectByExampleWithBLOBs(MwCmPayCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_PAYCOMPANY
     *
     * @mbggenerated Thu Sep 06 15:42:10 KST 2012
     */
    List<MwCmPayCompany> selectByExample(MwCmPayCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_PAYCOMPANY
     *
     * @mbggenerated Thu Sep 06 15:42:10 KST 2012
     */
    @Select({
        "select",
        "PAYCOMP_ID, PAYCOMP_NAME, ALLY_STAT, BUSINESS_NO, ZIPCODE, ADDR, ADDR_DETAIL, ",
        "MAIN_NUMBER, PHONE_NO, MOBILE_PHONE, EMAIL, REG_USER, REG_DTM, CHG_USER, CHG_DTM, ",
        "MANAGER_NAME, DC_METHOD_INFO, MEMO",
        "from MW_CM_PAYCOMPANY",
        "where PAYCOMP_ID = #{paycompId,jdbcType=VARCHAR}"
    })
    @ResultMap("ResultMapWithBLOBs")
    MwCmPayCompanyWithBLOBs selectByPrimaryKey(String paycompId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_PAYCOMPANY
     *
     * @mbggenerated Thu Sep 06 15:42:10 KST 2012
     */
    int updateByExampleSelective(@Param("record") MwCmPayCompanyWithBLOBs record, @Param("example") MwCmPayCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_PAYCOMPANY
     *
     * @mbggenerated Thu Sep 06 15:42:10 KST 2012
     */
    int updateByExampleWithBLOBs(@Param("record") MwCmPayCompanyWithBLOBs record, @Param("example") MwCmPayCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_PAYCOMPANY
     *
     * @mbggenerated Thu Sep 06 15:42:10 KST 2012
     */
    int updateByExample(@Param("record") MwCmPayCompany record, @Param("example") MwCmPayCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_PAYCOMPANY
     *
     * @mbggenerated Thu Sep 06 15:42:10 KST 2012
     */
    int updateByPrimaryKeySelective(MwCmPayCompanyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_PAYCOMPANY
     *
     * @mbggenerated Thu Sep 06 15:42:10 KST 2012
     */
    @Update({
        "update MW_CM_PAYCOMPANY",
        "set PAYCOMP_NAME = #{paycompName,jdbcType=VARCHAR},",
          "ALLY_STAT = #{allyStat,jdbcType=CHAR},",
          "BUSINESS_NO = #{businessNo,jdbcType=VARCHAR},",
          "ZIPCODE = #{zipcode,jdbcType=VARCHAR},",
          "ADDR = #{addr,jdbcType=VARCHAR},",
          "ADDR_DETAIL = #{addrDetail,jdbcType=VARCHAR},",
          "MAIN_NUMBER = #{mainNumber,jdbcType=VARCHAR},",
          "PHONE_NO = #{phoneNo,jdbcType=VARCHAR},",
          "MOBILE_PHONE = #{mobilePhone,jdbcType=VARCHAR},",
          "EMAIL = #{email,jdbcType=VARCHAR},",
          "REG_USER = #{regUser,jdbcType=VARCHAR},",
          "REG_DTM = #{regDtm,jdbcType=TIMESTAMP},",
          "CHG_USER = #{chgUser,jdbcType=VARCHAR},",
          "CHG_DTM = #{chgDtm,jdbcType=TIMESTAMP},",
          "MANAGER_NAME = #{managerName,jdbcType=VARCHAR},",
          "DC_METHOD_INFO = #{dcMethodInfo,jdbcType=LONGVARCHAR},",
          "MEMO = #{memo,jdbcType=LONGVARCHAR}",
        "where PAYCOMP_ID = #{paycompId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKeyWithBLOBs(MwCmPayCompanyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_PAYCOMPANY
     *
     * @mbggenerated Thu Sep 06 15:42:10 KST 2012
     */
    @Update({
        "update MW_CM_PAYCOMPANY",
        "set PAYCOMP_NAME = #{paycompName,jdbcType=VARCHAR},",
          "ALLY_STAT = #{allyStat,jdbcType=CHAR},",
          "BUSINESS_NO = #{businessNo,jdbcType=VARCHAR},",
          "ZIPCODE = #{zipcode,jdbcType=VARCHAR},",
          "ADDR = #{addr,jdbcType=VARCHAR},",
          "ADDR_DETAIL = #{addrDetail,jdbcType=VARCHAR},",
          "MAIN_NUMBER = #{mainNumber,jdbcType=VARCHAR},",
          "PHONE_NO = #{phoneNo,jdbcType=VARCHAR},",
          "MOBILE_PHONE = #{mobilePhone,jdbcType=VARCHAR},",
          "EMAIL = #{email,jdbcType=VARCHAR},",
          "REG_USER = #{regUser,jdbcType=VARCHAR},",
          "REG_DTM = #{regDtm,jdbcType=TIMESTAMP},",
          "CHG_USER = #{chgUser,jdbcType=VARCHAR},",
          "CHG_DTM = #{chgDtm,jdbcType=TIMESTAMP},",
          "MANAGER_NAME = #{managerName,jdbcType=VARCHAR}",
        "where PAYCOMP_ID = #{paycompId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(MwCmPayCompany record);
}