package com.wallet.membership.mapper;

import com.wallet.membership.model.MwCmCode;
import com.wallet.membership.model.MwCmCodeExample;
import com.wallet.membership.model.MwCmCodeKey;
import com.wallet.membership.model.MwCmCodeWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface MwCmCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_CODE
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    int countByExample(MwCmCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_CODE
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    int deleteByExample(MwCmCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_CODE
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    @Delete({
        "delete from MW_CM_CODE",
        "where GRP_CODE = #{grpCode,jdbcType=VARCHAR}",
          "and COM_CD = #{comCd,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(MwCmCodeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_CODE
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    @Insert({
        "insert into MW_CM_CODE (GRP_CODE, COM_CD, ",
        "COM_CD_VAL, SEQ_NO, ",
        "USE_YN, REMARK1, REMARK2, ",
        "REMARK3, REMARK4, ",
        "REG_USER, REG_DTM, ",
        "CHG_USER, CHG_DTM, ",
        "COM_CD_DESC, REMARK5)",
        "values (#{grpCode,jdbcType=VARCHAR}, #{comCd,jdbcType=VARCHAR}, ",
        "#{comCdVal,jdbcType=VARCHAR}, #{seqNo,jdbcType=INTEGER}, ",
        "#{useYn,jdbcType=CHAR}, #{remark1,jdbcType=VARCHAR}, #{remark2,jdbcType=VARCHAR}, ",
        "#{remark3,jdbcType=VARCHAR}, #{remark4,jdbcType=VARCHAR}, ",
        "#{regUser,jdbcType=VARCHAR}, #{regDtm,jdbcType=TIMESTAMP}, ",
        "#{chgUser,jdbcType=VARCHAR}, #{chgDtm,jdbcType=TIMESTAMP}, ",
        "#{comCdDesc,jdbcType=LONGVARCHAR}, #{remark5,jdbcType=LONGVARCHAR})"
    })
    int insert(MwCmCodeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_CODE
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    int insertSelective(MwCmCodeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_CODE
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    List<MwCmCodeWithBLOBs> selectByExampleWithBLOBs(MwCmCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_CODE
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    List<MwCmCode> selectByExample(MwCmCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_CODE
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    @Select({
        "select",
        "GRP_CODE, COM_CD, COM_CD_VAL, SEQ_NO, USE_YN, REMARK1, REMARK2, REMARK3, REMARK4, ",
        "REG_USER, REG_DTM, CHG_USER, CHG_DTM, COM_CD_DESC, REMARK5",
        "from MW_CM_CODE",
        "where GRP_CODE = #{grpCode,jdbcType=VARCHAR}",
          "and COM_CD = #{comCd,jdbcType=VARCHAR}"
    })
    @ResultMap("ResultMapWithBLOBs")
    MwCmCodeWithBLOBs selectByPrimaryKey(MwCmCodeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_CODE
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    int updateByExampleSelective(@Param("record") MwCmCodeWithBLOBs record, @Param("example") MwCmCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_CODE
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    int updateByExampleWithBLOBs(@Param("record") MwCmCodeWithBLOBs record, @Param("example") MwCmCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_CODE
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    int updateByExample(@Param("record") MwCmCode record, @Param("example") MwCmCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_CODE
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    int updateByPrimaryKeySelective(MwCmCodeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_CODE
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    @Update({
        "update MW_CM_CODE",
        "set COM_CD_VAL = #{comCdVal,jdbcType=VARCHAR},",
          "SEQ_NO = #{seqNo,jdbcType=INTEGER},",
          "USE_YN = #{useYn,jdbcType=CHAR},",
          "REMARK1 = #{remark1,jdbcType=VARCHAR},",
          "REMARK2 = #{remark2,jdbcType=VARCHAR},",
          "REMARK3 = #{remark3,jdbcType=VARCHAR},",
          "REMARK4 = #{remark4,jdbcType=VARCHAR},",
          "REG_USER = #{regUser,jdbcType=VARCHAR},",
          "REG_DTM = #{regDtm,jdbcType=TIMESTAMP},",
          "CHG_USER = #{chgUser,jdbcType=VARCHAR},",
          "CHG_DTM = #{chgDtm,jdbcType=TIMESTAMP},",
          "COM_CD_DESC = #{comCdDesc,jdbcType=LONGVARCHAR},",
          "REMARK5 = #{remark5,jdbcType=LONGVARCHAR}",
        "where GRP_CODE = #{grpCode,jdbcType=VARCHAR}",
          "and COM_CD = #{comCd,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKeyWithBLOBs(MwCmCodeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CM_CODE
     *
     * @mbggenerated Mon Sep 03 14:39:06 KST 2012
     */
    @Update({
        "update MW_CM_CODE",
        "set COM_CD_VAL = #{comCdVal,jdbcType=VARCHAR},",
          "SEQ_NO = #{seqNo,jdbcType=INTEGER},",
          "USE_YN = #{useYn,jdbcType=CHAR},",
          "REMARK1 = #{remark1,jdbcType=VARCHAR},",
          "REMARK2 = #{remark2,jdbcType=VARCHAR},",
          "REMARK3 = #{remark3,jdbcType=VARCHAR},",
          "REMARK4 = #{remark4,jdbcType=VARCHAR},",
          "REG_USER = #{regUser,jdbcType=VARCHAR},",
          "REG_DTM = #{regDtm,jdbcType=TIMESTAMP},",
          "CHG_USER = #{chgUser,jdbcType=VARCHAR},",
          "CHG_DTM = #{chgDtm,jdbcType=TIMESTAMP}",
        "where GRP_CODE = #{grpCode,jdbcType=VARCHAR}",
          "and COM_CD = #{comCd,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(MwCmCode record);
}