package com.wallet.membership.mapper;

import com.wallet.membership.model.MwCsCpnregHist;
import com.wallet.membership.model.MwCsCpnregHistExample;
import com.wallet.membership.model.MwCsCpnregHistKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface MwCsCpnregHistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_CPNREG_HIST
     *
     * @mbggenerated Wed Sep 19 17:03:49 KST 2012
     */
    int countByExample(MwCsCpnregHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_CPNREG_HIST
     *
     * @mbggenerated Wed Sep 19 17:03:49 KST 2012
     */
    int deleteByExample(MwCsCpnregHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_CPNREG_HIST
     *
     * @mbggenerated Wed Sep 19 17:03:49 KST 2012
     */
    @Delete({
        "delete from MW_CS_CPNREG_HIST",
        "where CPN_ID = #{cpnId,jdbcType=VARCHAR}",
          "and SEQ_NO = #{seqNo,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(MwCsCpnregHistKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_CPNREG_HIST
     *
     * @mbggenerated Wed Sep 19 17:03:49 KST 2012
     */
    @Insert({
        "insert into MW_CS_CPNREG_HIST (CPN_ID, SEQ_NO, ",
        "CPN_STAT, REG_USER, REG_DTM, ",
        "STAT_COMMENT)",
        "values (#{cpnId,jdbcType=VARCHAR}, #{seqNo,jdbcType=INTEGER}, ",
        "#{cpnStat,jdbcType=CHAR}, #{regUser,jdbcType=VARCHAR}, #{regDtm,jdbcType=TIMESTAMP}, ",
        "#{statComment,jdbcType=LONGVARCHAR})"
    })
    int insert(MwCsCpnregHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_CPNREG_HIST
     *
     * @mbggenerated Wed Sep 19 17:03:49 KST 2012
     */
    int insertSelective(MwCsCpnregHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_CPNREG_HIST
     *
     * @mbggenerated Wed Sep 19 17:03:49 KST 2012
     */
    List<MwCsCpnregHist> selectByExampleWithBLOBs(MwCsCpnregHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_CPNREG_HIST
     *
     * @mbggenerated Wed Sep 19 17:03:49 KST 2012
     */
    List<MwCsCpnregHist> selectByExample(MwCsCpnregHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_CPNREG_HIST
     *
     * @mbggenerated Wed Sep 19 17:03:49 KST 2012
     */
    @Select({
        "select",
        "CPN_ID, SEQ_NO, CPN_STAT, REG_USER, REG_DTM, STAT_COMMENT",
        "from MW_CS_CPNREG_HIST",
        "where CPN_ID = #{cpnId,jdbcType=VARCHAR}",
          "and SEQ_NO = #{seqNo,jdbcType=INTEGER}"
    })
    @ResultMap("ResultMapWithBLOBs")
    MwCsCpnregHist selectByPrimaryKey(MwCsCpnregHistKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_CPNREG_HIST
     *
     * @mbggenerated Wed Sep 19 17:03:49 KST 2012
     */
    int updateByExampleSelective(@Param("record") MwCsCpnregHist record, @Param("example") MwCsCpnregHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_CPNREG_HIST
     *
     * @mbggenerated Wed Sep 19 17:03:49 KST 2012
     */
    int updateByExampleWithBLOBs(@Param("record") MwCsCpnregHist record, @Param("example") MwCsCpnregHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_CPNREG_HIST
     *
     * @mbggenerated Wed Sep 19 17:03:49 KST 2012
     */
    int updateByExample(@Param("record") MwCsCpnregHist record, @Param("example") MwCsCpnregHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_CPNREG_HIST
     *
     * @mbggenerated Wed Sep 19 17:03:49 KST 2012
     */
    int updateByPrimaryKeySelective(MwCsCpnregHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_CPNREG_HIST
     *
     * @mbggenerated Wed Sep 19 17:03:49 KST 2012
     */
    @Update({
        "update MW_CS_CPNREG_HIST",
        "set CPN_STAT = #{cpnStat,jdbcType=CHAR},",
          "REG_USER = #{regUser,jdbcType=VARCHAR},",
          "REG_DTM = #{regDtm,jdbcType=TIMESTAMP},",
          "STAT_COMMENT = #{statComment,jdbcType=LONGVARCHAR}",
        "where CPN_ID = #{cpnId,jdbcType=VARCHAR}",
          "and SEQ_NO = #{seqNo,jdbcType=INTEGER}"
    })
    int updateByPrimaryKeyWithBLOBs(MwCsCpnregHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_CPNREG_HIST
     *
     * @mbggenerated Wed Sep 19 17:03:49 KST 2012
     */
    @Update({
        "update MW_CS_CPNREG_HIST",
        "set CPN_STAT = #{cpnStat,jdbcType=CHAR},",
          "REG_USER = #{regUser,jdbcType=VARCHAR},",
          "REG_DTM = #{regDtm,jdbcType=TIMESTAMP}",
        "where CPN_ID = #{cpnId,jdbcType=VARCHAR}",
          "and SEQ_NO = #{seqNo,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(MwCsCpnregHist record);
}