package com.wallet.membership.mapper;

import com.wallet.membership.model.MwCsBulkCpn;
import com.wallet.membership.model.MwCsBulkCpnExample;
import com.wallet.membership.model.MwCsBulkCpnKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface MwCsBulkCpnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_BULK_CPN
     *
     * @mbggenerated Mon Sep 17 17:56:16 KST 2012
     */
    int countByExample(MwCsBulkCpnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_BULK_CPN
     *
     * @mbggenerated Mon Sep 17 17:56:16 KST 2012
     */
    int deleteByExample(MwCsBulkCpnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_BULK_CPN
     *
     * @mbggenerated Mon Sep 17 17:56:16 KST 2012
     */
    @Delete({
        "delete from MW_CS_BULK_CPN",
        "where CPN_ID = #{cpnId,jdbcType=VARCHAR}",
          "and ISSUE_SEQ = #{issueSeq,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(MwCsBulkCpnKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_BULK_CPN
     *
     * @mbggenerated Mon Sep 17 17:56:16 KST 2012
     */
    @Insert({
        "insert into MW_CS_BULK_CPN (CPN_ID, ISSUE_SEQ, ",
        "BARCODE, ISSUE_YN, COMP_BARCODE, ",
        "REG_USER, REG_DTM)",
        "values (#{cpnId,jdbcType=VARCHAR}, #{issueSeq,jdbcType=INTEGER}, ",
        "#{barcode,jdbcType=VARCHAR}, #{issueYn,jdbcType=CHAR}, #{compBarcode,jdbcType=VARCHAR}, ",
        "#{regUser,jdbcType=VARCHAR}, #{regDtm,jdbcType=TIMESTAMP})"
    })
    int insert(MwCsBulkCpn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_BULK_CPN
     *
     * @mbggenerated Mon Sep 17 17:56:16 KST 2012
     */
    int insertSelective(MwCsBulkCpn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_BULK_CPN
     *
     * @mbggenerated Mon Sep 17 17:56:16 KST 2012
     */
    List<MwCsBulkCpn> selectByExample(MwCsBulkCpnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_BULK_CPN
     *
     * @mbggenerated Mon Sep 17 17:56:16 KST 2012
     */
    @Select({
        "select",
        "CPN_ID, ISSUE_SEQ, BARCODE, ISSUE_YN, COMP_BARCODE, REG_USER, REG_DTM",
        "from MW_CS_BULK_CPN",
        "where CPN_ID = #{cpnId,jdbcType=VARCHAR}",
          "and ISSUE_SEQ = #{issueSeq,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    MwCsBulkCpn selectByPrimaryKey(MwCsBulkCpnKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_BULK_CPN
     *
     * @mbggenerated Mon Sep 17 17:56:16 KST 2012
     */
    int updateByExampleSelective(@Param("record") MwCsBulkCpn record, @Param("example") MwCsBulkCpnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_BULK_CPN
     *
     * @mbggenerated Mon Sep 17 17:56:16 KST 2012
     */
    int updateByExample(@Param("record") MwCsBulkCpn record, @Param("example") MwCsBulkCpnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_BULK_CPN
     *
     * @mbggenerated Mon Sep 17 17:56:16 KST 2012
     */
    int updateByPrimaryKeySelective(MwCsBulkCpn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_BULK_CPN
     *
     * @mbggenerated Mon Sep 17 17:56:16 KST 2012
     */
    @Update({
        "update MW_CS_BULK_CPN",
        "set BARCODE = #{barcode,jdbcType=VARCHAR},",
          "ISSUE_YN = #{issueYn,jdbcType=CHAR},",
          "COMP_BARCODE = #{compBarcode,jdbcType=VARCHAR},",
          "REG_USER = #{regUser,jdbcType=VARCHAR},",
          "REG_DTM = #{regDtm,jdbcType=TIMESTAMP}",
        "where CPN_ID = #{cpnId,jdbcType=VARCHAR}",
          "and ISSUE_SEQ = #{issueSeq,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(MwCsBulkCpn record);
}