package com.wallet.membership.mapper;

import com.wallet.membership.model.MwCsCpnShareratio;
import com.wallet.membership.model.MwCsCpnShareratioExample;
import com.wallet.membership.model.MwCsCpnShareratioKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface MwCsCpnShareratioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_CPN_SHARERATIO
     *
     * @mbggenerated Mon Sep 24 01:19:50 KST 2012
     */
    int countByExample(MwCsCpnShareratioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_CPN_SHARERATIO
     *
     * @mbggenerated Mon Sep 24 01:19:50 KST 2012
     */
    int deleteByExample(MwCsCpnShareratioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_CPN_SHARERATIO
     *
     * @mbggenerated Mon Sep 24 01:19:50 KST 2012
     */
    @Delete({
        "delete from MW_CS_CPN_SHARERATIO",
        "where CPN_ID = #{cpnId,jdbcType=VARCHAR}",
          "and SEQ_NO = #{seqNo,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(MwCsCpnShareratioKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_CPN_SHARERATIO
     *
     * @mbggenerated Mon Sep 24 01:19:50 KST 2012
     */
    @Insert({
        "insert into MW_CS_CPN_SHARERATIO (CPN_ID, SEQ_NO, ",
        "COMP_TYPE, COMP_ID, COMP_SHARE_RATIO, ",
        "USE_YN, REG_USER, REG_DTM)",
        "values (#{cpnId,jdbcType=VARCHAR}, #{seqNo,jdbcType=INTEGER}, ",
        "#{compType,jdbcType=CHAR}, #{compId,jdbcType=VARCHAR}, #{compShareRatio,jdbcType=INTEGER}, ",
        "#{useYn,jdbcType=CHAR}, #{regUser,jdbcType=VARCHAR}, #{regDtm,jdbcType=TIMESTAMP})"
    })
    int insert(MwCsCpnShareratio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_CPN_SHARERATIO
     *
     * @mbggenerated Mon Sep 24 01:19:50 KST 2012
     */
    int insertSelective(MwCsCpnShareratio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_CPN_SHARERATIO
     *
     * @mbggenerated Mon Sep 24 01:19:50 KST 2012
     */
    List<MwCsCpnShareratio> selectByExample(MwCsCpnShareratioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_CPN_SHARERATIO
     *
     * @mbggenerated Mon Sep 24 01:19:50 KST 2012
     */
    @Select({
        "select",
        "CPN_ID, SEQ_NO, COMP_TYPE, COMP_ID, COMP_SHARE_RATIO, USE_YN, REG_USER, REG_DTM",
        "from MW_CS_CPN_SHARERATIO",
        "where CPN_ID = #{cpnId,jdbcType=VARCHAR}",
          "and SEQ_NO = #{seqNo,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    MwCsCpnShareratio selectByPrimaryKey(MwCsCpnShareratioKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_CPN_SHARERATIO
     *
     * @mbggenerated Mon Sep 24 01:19:50 KST 2012
     */
    int updateByExampleSelective(@Param("record") MwCsCpnShareratio record, @Param("example") MwCsCpnShareratioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_CPN_SHARERATIO
     *
     * @mbggenerated Mon Sep 24 01:19:50 KST 2012
     */
    int updateByExample(@Param("record") MwCsCpnShareratio record, @Param("example") MwCsCpnShareratioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_CPN_SHARERATIO
     *
     * @mbggenerated Mon Sep 24 01:19:50 KST 2012
     */
    int updateByPrimaryKeySelective(MwCsCpnShareratio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_CS_CPN_SHARERATIO
     *
     * @mbggenerated Mon Sep 24 01:19:50 KST 2012
     */
    @Update({
        "update MW_CS_CPN_SHARERATIO",
        "set COMP_TYPE = #{compType,jdbcType=CHAR},",
          "COMP_ID = #{compId,jdbcType=VARCHAR},",
          "COMP_SHARE_RATIO = #{compShareRatio,jdbcType=INTEGER},",
          "USE_YN = #{useYn,jdbcType=CHAR},",
          "REG_USER = #{regUser,jdbcType=VARCHAR},",
          "REG_DTM = #{regDtm,jdbcType=TIMESTAMP}",
        "where CPN_ID = #{cpnId,jdbcType=VARCHAR}",
          "and SEQ_NO = #{seqNo,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(MwCsCpnShareratio record);
}