package com.wallet.membership.mapper;

import com.wallet.membership.model.MwMembAgree;
import com.wallet.membership.model.MwMembAgreeExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface MwMembAgreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memb_agree
     *
     * @mbggenerated Tue Aug 14 13:40:21 KST 2012
     */
    int countByExample(MwMembAgreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memb_agree
     *
     * @mbggenerated Tue Aug 14 13:40:21 KST 2012
     */
    int deleteByExample(MwMembAgreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memb_agree
     *
     * @mbggenerated Tue Aug 14 13:40:21 KST 2012
     */
    @Insert({
        "insert into memb_agree (memb_id, idx, ",
        "title, info, web, ",
        "chk, ver)",
        "values (#{membId,jdbcType=VARCHAR}, #{idx,jdbcType=INTEGER}, ",
        "#{title,jdbcType=VARCHAR}, #{info,jdbcType=VARCHAR}, #{web,jdbcType=CHAR}, ",
        "#{chk,jdbcType=CHAR}, #{ver,jdbcType=VARCHAR})"
    })
    int insert(MwMembAgree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memb_agree
     *
     * @mbggenerated Tue Aug 14 13:40:21 KST 2012
     */
    int insertSelective(MwMembAgree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memb_agree
     *
     * @mbggenerated Tue Aug 14 13:40:21 KST 2012
     */
    List<MwMembAgree> selectByExample(MwMembAgreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memb_agree
     *
     * @mbggenerated Tue Aug 14 13:40:21 KST 2012
     */
    int updateByExampleSelective(@Param("record") MwMembAgree record, @Param("example") MwMembAgreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memb_agree
     *
     * @mbggenerated Tue Aug 14 13:40:21 KST 2012
     */
    int updateByExample(@Param("record") MwMembAgree record, @Param("example") MwMembAgreeExample example);
}