package com.wallet.membership.mapper;

import com.wallet.membership.model.MwMsCompPayMent;
import com.wallet.membership.model.MwMsCompPayMentExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface MwMsCompPayMentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_COMP_PAYMENT
     *
     * @mbggenerated Fri Sep 14 19:55:25 KST 2012
     */
    int countByExample(MwMsCompPayMentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_COMP_PAYMENT
     *
     * @mbggenerated Fri Sep 14 19:55:25 KST 2012
     */
    int deleteByExample(MwMsCompPayMentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_COMP_PAYMENT
     *
     * @mbggenerated Fri Sep 14 19:55:25 KST 2012
     */
    @Delete({
        "delete from MW_MS_COMP_PAYMENT",
        "where COMP_ID = #{compId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String compId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_COMP_PAYMENT
     *
     * @mbggenerated Fri Sep 14 19:55:25 KST 2012
     */
    @Insert({
        "insert into MW_MS_COMP_PAYMENT (COMP_ID, COMP_PAY_MEMB_SAVE, ",
        "COMP_PAY_MEMB_USE, COMP_PAY_MEMB_DC, ",
        "COMP_PAY_CPN_YN, COMP_PAY_STAMP_YN, ",
        "COMP_PAY_STAMP_SAVE_YN, SAVE_RATE_FIXED_YN, ",
        "CASH_SAVE_RATE, CARD_SAVE_RATE, ",
        "COMP_SAVE_RATE, DEBIT_SAVE_RATE, ",
        "ETC_SAVE_RATE, SAVE_UNIT, ",
        "SAVE_ROUND_TYPE, DC_SAVE_PRICE_TYPE, ",
        "SAVE_MIN_PAY_PRICE, SAVE_MAX_PAY_PRICE, ",
        "MAX_SAVE_POINT, POINT_USE_TYPE, ",
        "POINT_USE_UNIT, USE_ROUND_TYPE, ",
        "FIXED_POINT, FIXED_RATE, ",
        "MIN_PAY_PRICE, MIN_USE_POINT, ",
        "MAX_USE_POINT, DC_RATE, ",
        "DC_UNIT, DC_ROUND_TYPE, DC_MIN_PAY_PRICE, ",
        "MAX_DC_PRICE, REG_USER, ",
        "REG_DTM, CHG_USER, ",
        "CHG_DTM, SAVE_NOTICE)",
        "values (#{compId,jdbcType=VARCHAR}, #{compPayMembSave,jdbcType=CHAR}, ",
        "#{compPayMembUse,jdbcType=CHAR}, #{compPayMembDc,jdbcType=CHAR}, ",
        "#{compPayCpnYn,jdbcType=CHAR}, #{compPayStampYn,jdbcType=CHAR}, ",
        "#{compPayStampSaveYn,jdbcType=CHAR}, #{saveRateFixedYn,jdbcType=CHAR}, ",
        "#{cashSaveRate,jdbcType=INTEGER}, #{cardSaveRate,jdbcType=INTEGER}, ",
        "#{compSaveRate,jdbcType=INTEGER}, #{debitSaveRate,jdbcType=INTEGER}, ",
        "#{etcSaveRate,jdbcType=INTEGER}, #{saveUnit,jdbcType=CHAR}, ",
        "#{saveRoundType,jdbcType=CHAR}, #{dcSavePriceType,jdbcType=CHAR}, ",
        "#{saveMinPayPrice,jdbcType=INTEGER}, #{saveMaxPayPrice,jdbcType=INTEGER}, ",
        "#{maxSavePoint,jdbcType=INTEGER}, #{pointUseType,jdbcType=CHAR}, ",
        "#{pointUseUnit,jdbcType=CHAR}, #{useRoundType,jdbcType=CHAR}, ",
        "#{fixedPoint,jdbcType=INTEGER}, #{fixedRate,jdbcType=INTEGER}, ",
        "#{minPayPrice,jdbcType=INTEGER}, #{minUsePoint,jdbcType=INTEGER}, ",
        "#{maxUsePoint,jdbcType=INTEGER}, #{dcRate,jdbcType=INTEGER}, ",
        "#{dcUnit,jdbcType=CHAR}, #{dcRoundType,jdbcType=CHAR}, #{dcMinPayPrice,jdbcType=INTEGER}, ",
        "#{maxDcPrice,jdbcType=INTEGER}, #{regUser,jdbcType=VARCHAR}, ",
        "#{regDtm,jdbcType=TIMESTAMP}, #{chgUser,jdbcType=VARCHAR}, ",
        "#{chgDtm,jdbcType=TIMESTAMP}, #{saveNotice,jdbcType=LONGVARCHAR})"
    })
    int insert(MwMsCompPayMent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_COMP_PAYMENT
     *
     * @mbggenerated Fri Sep 14 19:55:25 KST 2012
     */
    int insertSelective(MwMsCompPayMent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_COMP_PAYMENT
     *
     * @mbggenerated Fri Sep 14 19:55:25 KST 2012
     */
    List<MwMsCompPayMent> selectByExampleWithBLOBs(MwMsCompPayMentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_COMP_PAYMENT
     *
     * @mbggenerated Fri Sep 14 19:55:25 KST 2012
     */
    List<MwMsCompPayMent> selectByExample(MwMsCompPayMentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_COMP_PAYMENT
     *
     * @mbggenerated Fri Sep 14 19:55:25 KST 2012
     */
    @Select({
        "select",
        "COMP_ID, COMP_PAY_MEMB_SAVE, COMP_PAY_MEMB_USE, COMP_PAY_MEMB_DC, COMP_PAY_CPN_YN, ",
        "COMP_PAY_STAMP_YN, COMP_PAY_STAMP_SAVE_YN, SAVE_RATE_FIXED_YN, CASH_SAVE_RATE, ",
        "CARD_SAVE_RATE, COMP_SAVE_RATE, DEBIT_SAVE_RATE, ETC_SAVE_RATE, SAVE_UNIT, SAVE_ROUND_TYPE, ",
        "DC_SAVE_PRICE_TYPE, SAVE_MIN_PAY_PRICE, SAVE_MAX_PAY_PRICE, MAX_SAVE_POINT, ",
        "POINT_USE_TYPE, POINT_USE_UNIT, USE_ROUND_TYPE, FIXED_POINT, FIXED_RATE, MIN_PAY_PRICE, ",
        "MIN_USE_POINT, MAX_USE_POINT, DC_RATE, DC_UNIT, DC_ROUND_TYPE, DC_MIN_PAY_PRICE, ",
        "MAX_DC_PRICE, REG_USER, REG_DTM, CHG_USER, CHG_DTM, SAVE_NOTICE",
        "from MW_MS_COMP_PAYMENT",
        "where COMP_ID = #{compId,jdbcType=VARCHAR}"
    })
    @ResultMap("ResultMapWithBLOBs")
    MwMsCompPayMent selectByPrimaryKey(String compId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_COMP_PAYMENT
     *
     * @mbggenerated Fri Sep 14 19:55:25 KST 2012
     */
    int updateByExampleSelective(@Param("record") MwMsCompPayMent record, @Param("example") MwMsCompPayMentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_COMP_PAYMENT
     *
     * @mbggenerated Fri Sep 14 19:55:25 KST 2012
     */
    int updateByExampleWithBLOBs(@Param("record") MwMsCompPayMent record, @Param("example") MwMsCompPayMentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_COMP_PAYMENT
     *
     * @mbggenerated Fri Sep 14 19:55:25 KST 2012
     */
    int updateByExample(@Param("record") MwMsCompPayMent record, @Param("example") MwMsCompPayMentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_COMP_PAYMENT
     *
     * @mbggenerated Fri Sep 14 19:55:25 KST 2012
     */
    int updateByPrimaryKeySelective(MwMsCompPayMent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_COMP_PAYMENT
     *
     * @mbggenerated Fri Sep 14 19:55:25 KST 2012
     */
    @Update({
        "update MW_MS_COMP_PAYMENT",
        "set COMP_PAY_MEMB_SAVE = #{compPayMembSave,jdbcType=CHAR},",
          "COMP_PAY_MEMB_USE = #{compPayMembUse,jdbcType=CHAR},",
          "COMP_PAY_MEMB_DC = #{compPayMembDc,jdbcType=CHAR},",
          "COMP_PAY_CPN_YN = #{compPayCpnYn,jdbcType=CHAR},",
          "COMP_PAY_STAMP_YN = #{compPayStampYn,jdbcType=CHAR},",
          "COMP_PAY_STAMP_SAVE_YN = #{compPayStampSaveYn,jdbcType=CHAR},",
          "SAVE_RATE_FIXED_YN = #{saveRateFixedYn,jdbcType=CHAR},",
          "CASH_SAVE_RATE = #{cashSaveRate,jdbcType=INTEGER},",
          "CARD_SAVE_RATE = #{cardSaveRate,jdbcType=INTEGER},",
          "COMP_SAVE_RATE = #{compSaveRate,jdbcType=INTEGER},",
          "DEBIT_SAVE_RATE = #{debitSaveRate,jdbcType=INTEGER},",
          "ETC_SAVE_RATE = #{etcSaveRate,jdbcType=INTEGER},",
          "SAVE_UNIT = #{saveUnit,jdbcType=CHAR},",
          "SAVE_ROUND_TYPE = #{saveRoundType,jdbcType=CHAR},",
          "DC_SAVE_PRICE_TYPE = #{dcSavePriceType,jdbcType=CHAR},",
          "SAVE_MIN_PAY_PRICE = #{saveMinPayPrice,jdbcType=INTEGER},",
          "SAVE_MAX_PAY_PRICE = #{saveMaxPayPrice,jdbcType=INTEGER},",
          "MAX_SAVE_POINT = #{maxSavePoint,jdbcType=INTEGER},",
          "POINT_USE_TYPE = #{pointUseType,jdbcType=CHAR},",
          "POINT_USE_UNIT = #{pointUseUnit,jdbcType=CHAR},",
          "USE_ROUND_TYPE = #{useRoundType,jdbcType=CHAR},",
          "FIXED_POINT = #{fixedPoint,jdbcType=INTEGER},",
          "FIXED_RATE = #{fixedRate,jdbcType=INTEGER},",
          "MIN_PAY_PRICE = #{minPayPrice,jdbcType=INTEGER},",
          "MIN_USE_POINT = #{minUsePoint,jdbcType=INTEGER},",
          "MAX_USE_POINT = #{maxUsePoint,jdbcType=INTEGER},",
          "DC_RATE = #{dcRate,jdbcType=INTEGER},",
          "DC_UNIT = #{dcUnit,jdbcType=CHAR},",
          "DC_ROUND_TYPE = #{dcRoundType,jdbcType=CHAR},",
          "DC_MIN_PAY_PRICE = #{dcMinPayPrice,jdbcType=INTEGER},",
          "MAX_DC_PRICE = #{maxDcPrice,jdbcType=INTEGER},",
          "REG_USER = #{regUser,jdbcType=VARCHAR},",
          "REG_DTM = #{regDtm,jdbcType=TIMESTAMP},",
          "CHG_USER = #{chgUser,jdbcType=VARCHAR},",
          "CHG_DTM = #{chgDtm,jdbcType=TIMESTAMP},",
          "SAVE_NOTICE = #{saveNotice,jdbcType=LONGVARCHAR}",
        "where COMP_ID = #{compId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKeyWithBLOBs(MwMsCompPayMent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_COMP_PAYMENT
     *
     * @mbggenerated Fri Sep 14 19:55:25 KST 2012
     */
    @Update({
        "update MW_MS_COMP_PAYMENT",
        "set COMP_PAY_MEMB_SAVE = #{compPayMembSave,jdbcType=CHAR},",
          "COMP_PAY_MEMB_USE = #{compPayMembUse,jdbcType=CHAR},",
          "COMP_PAY_MEMB_DC = #{compPayMembDc,jdbcType=CHAR},",
          "COMP_PAY_CPN_YN = #{compPayCpnYn,jdbcType=CHAR},",
          "COMP_PAY_STAMP_YN = #{compPayStampYn,jdbcType=CHAR},",
          "COMP_PAY_STAMP_SAVE_YN = #{compPayStampSaveYn,jdbcType=CHAR},",
          "SAVE_RATE_FIXED_YN = #{saveRateFixedYn,jdbcType=CHAR},",
          "CASH_SAVE_RATE = #{cashSaveRate,jdbcType=INTEGER},",
          "CARD_SAVE_RATE = #{cardSaveRate,jdbcType=INTEGER},",
          "COMP_SAVE_RATE = #{compSaveRate,jdbcType=INTEGER},",
          "DEBIT_SAVE_RATE = #{debitSaveRate,jdbcType=INTEGER},",
          "ETC_SAVE_RATE = #{etcSaveRate,jdbcType=INTEGER},",
          "SAVE_UNIT = #{saveUnit,jdbcType=CHAR},",
          "SAVE_ROUND_TYPE = #{saveRoundType,jdbcType=CHAR},",
          "DC_SAVE_PRICE_TYPE = #{dcSavePriceType,jdbcType=CHAR},",
          "SAVE_MIN_PAY_PRICE = #{saveMinPayPrice,jdbcType=INTEGER},",
          "SAVE_MAX_PAY_PRICE = #{saveMaxPayPrice,jdbcType=INTEGER},",
          "MAX_SAVE_POINT = #{maxSavePoint,jdbcType=INTEGER},",
          "POINT_USE_TYPE = #{pointUseType,jdbcType=CHAR},",
          "POINT_USE_UNIT = #{pointUseUnit,jdbcType=CHAR},",
          "USE_ROUND_TYPE = #{useRoundType,jdbcType=CHAR},",
          "FIXED_POINT = #{fixedPoint,jdbcType=INTEGER},",
          "FIXED_RATE = #{fixedRate,jdbcType=INTEGER},",
          "MIN_PAY_PRICE = #{minPayPrice,jdbcType=INTEGER},",
          "MIN_USE_POINT = #{minUsePoint,jdbcType=INTEGER},",
          "MAX_USE_POINT = #{maxUsePoint,jdbcType=INTEGER},",
          "DC_RATE = #{dcRate,jdbcType=INTEGER},",
          "DC_UNIT = #{dcUnit,jdbcType=CHAR},",
          "DC_ROUND_TYPE = #{dcRoundType,jdbcType=CHAR},",
          "DC_MIN_PAY_PRICE = #{dcMinPayPrice,jdbcType=INTEGER},",
          "MAX_DC_PRICE = #{maxDcPrice,jdbcType=INTEGER},",
          "REG_USER = #{regUser,jdbcType=VARCHAR},",
          "REG_DTM = #{regDtm,jdbcType=TIMESTAMP},",
          "CHG_USER = #{chgUser,jdbcType=VARCHAR},",
          "CHG_DTM = #{chgDtm,jdbcType=TIMESTAMP}",
        "where COMP_ID = #{compId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(MwMsCompPayMent record);
}