package com.wallet.membership.mapper;

import com.wallet.membership.model.MwMsStarPayMent;
import com.wallet.membership.model.MwMsStarPayMentExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface MwMsStarPayMentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_STAR_PAYMENT
     *
     * @mbggenerated Wed Jan 16 11:29:57 KST 2013
     */
    int countByExample(MwMsStarPayMentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_STAR_PAYMENT
     *
     * @mbggenerated Wed Jan 16 11:29:57 KST 2013
     */
    int deleteByExample(MwMsStarPayMentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_STAR_PAYMENT
     *
     * @mbggenerated Wed Jan 16 11:29:57 KST 2013
     */
    @Delete({
        "delete from MW_MS_STAR_PAYMENT",
        "where COMP_ID = #{compId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String compId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_STAR_PAYMENT
     *
     * @mbggenerated Wed Jan 16 11:29:57 KST 2013
     */
    @Insert({
        "insert into MW_MS_STAR_PAYMENT (COMP_ID, STAR_POINT_SAVE, ",
        "STAR_POINT_USE, STAR_POINT_DC, ",
        "SAVE_RATE_FIXED_YN, CASH_SAVE_RATE, ",
        "CARD_SAVE_RATE, COMP_SAVE_RATE, ",
        "DEBIT_SAVE_RATE, ETC_SAVE_RATE, ",
        "SAVE_UNIT, SAVE_ROUND_TYPE, ",
        "DC_SAVE_PRICE_TYPE, SAVE_MIN_PAY_PRICE, ",
        "SAVE_MAX_PAY_PRICE, MAX_SAVE_POINT, ",
        "POINT_USE_TYPE, POINT_USE_UNIT, ",
        "USE_ROUND_TYPE, FIXED_POINT, ",
        "FIXED_RATE, MIN_PAY_PRICE, ",
        "MIN_USE_POINT, MAX_USE_POINT, ",
        "DC_RATE, DC_UNIT, DC_ROUND_TYPE, ",
        "DC_MIN_PAY_PRICE, MAX_DC_PRICE, ",
        "MID_SHOP_ID, SUPERSTAR_ADD_SAVE_RATE, ",
        "SUPERSTAR_ADD_USE_RATE, SUPERSTAR_ADD_DC_RATE, ",
        "ROYALSTAR_ADD_SAVE_RATE, ROYALSTAR_ADD_USE_RATE, ",
        "ROYALSTAR_ADD_DC_RATE, MAGICSTAR_ADD_SAVE_RATE, ",
        "MAGICSTAR_ADD_USE_RATE, MAGICSTAR_ADD_DC_RATE, ",
        "HAPPYSTAR_ADD_SAVE_RATE, HAPPYSTAR_ADD_USE_RATE, ",
        "HAPPYSTAR_ADD_DC_RATE, REG_USER, ",
        "REG_DTM, CHG_USER, ",
        "CHG_DTM, SAVE_NOTICE)",
        "values (#{compId,jdbcType=VARCHAR}, #{starPointSave,jdbcType=CHAR}, ",
        "#{starPointUse,jdbcType=CHAR}, #{starPointDc,jdbcType=CHAR}, ",
        "#{saveRateFixedYn,jdbcType=CHAR}, #{cashSaveRate,jdbcType=INTEGER}, ",
        "#{cardSaveRate,jdbcType=INTEGER}, #{compSaveRate,jdbcType=INTEGER}, ",
        "#{debitSaveRate,jdbcType=INTEGER}, #{etcSaveRate,jdbcType=INTEGER}, ",
        "#{saveUnit,jdbcType=CHAR}, #{saveRoundType,jdbcType=CHAR}, ",
        "#{dcSavePriceType,jdbcType=CHAR}, #{saveMinPayPrice,jdbcType=INTEGER}, ",
        "#{saveMaxPayPrice,jdbcType=INTEGER}, #{maxSavePoint,jdbcType=INTEGER}, ",
        "#{pointUseType,jdbcType=CHAR}, #{pointUseUnit,jdbcType=CHAR}, ",
        "#{useRoundType,jdbcType=CHAR}, #{fixedPoint,jdbcType=INTEGER}, ",
        "#{fixedRate,jdbcType=INTEGER}, #{minPayPrice,jdbcType=INTEGER}, ",
        "#{minUsePoint,jdbcType=INTEGER}, #{maxUsePoint,jdbcType=INTEGER}, ",
        "#{dcRate,jdbcType=INTEGER}, #{dcUnit,jdbcType=CHAR}, #{dcRoundType,jdbcType=CHAR}, ",
        "#{dcMinPayPrice,jdbcType=INTEGER}, #{maxDcPrice,jdbcType=INTEGER}, ",
        "#{midShopId,jdbcType=VARCHAR}, #{superstarAddSaveRate,jdbcType=INTEGER}, ",
        "#{superstarAddUseRate,jdbcType=INTEGER}, #{superstarAddDcRate,jdbcType=INTEGER}, ",
        "#{royalstarAddSaveRate,jdbcType=INTEGER}, #{royalstarAddUseRate,jdbcType=INTEGER}, ",
        "#{royalstarAddDcRate,jdbcType=INTEGER}, #{magicstarAddSaveRate,jdbcType=INTEGER}, ",
        "#{magicstarAddUseRate,jdbcType=INTEGER}, #{magicstarAddDcRate,jdbcType=INTEGER}, ",
        "#{happystarAddSaveRate,jdbcType=INTEGER}, #{happystarAddUseRate,jdbcType=INTEGER}, ",
        "#{happystarAddDcRate,jdbcType=INTEGER}, #{regUser,jdbcType=VARCHAR}, ",
        "#{regDtm,jdbcType=TIMESTAMP}, #{chgUser,jdbcType=VARCHAR}, ",
        "#{chgDtm,jdbcType=TIMESTAMP}, #{saveNotice,jdbcType=LONGVARCHAR})"
    })
    int insert(MwMsStarPayMent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_STAR_PAYMENT
     *
     * @mbggenerated Wed Jan 16 11:29:57 KST 2013
     */
    int insertSelective(MwMsStarPayMent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_STAR_PAYMENT
     *
     * @mbggenerated Wed Jan 16 11:29:57 KST 2013
     */
    List<MwMsStarPayMent> selectByExampleWithBLOBs(MwMsStarPayMentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_STAR_PAYMENT
     *
     * @mbggenerated Wed Jan 16 11:29:57 KST 2013
     */
    List<MwMsStarPayMent> selectByExample(MwMsStarPayMentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_STAR_PAYMENT
     *
     * @mbggenerated Wed Jan 16 11:29:57 KST 2013
     */
    @Select({
        "select",
        "COMP_ID, STAR_POINT_SAVE, STAR_POINT_USE, STAR_POINT_DC, SAVE_RATE_FIXED_YN, ",
        "CASH_SAVE_RATE, CARD_SAVE_RATE, COMP_SAVE_RATE, DEBIT_SAVE_RATE, ETC_SAVE_RATE, ",
        "SAVE_UNIT, SAVE_ROUND_TYPE, DC_SAVE_PRICE_TYPE, SAVE_MIN_PAY_PRICE, SAVE_MAX_PAY_PRICE, ",
        "MAX_SAVE_POINT, POINT_USE_TYPE, POINT_USE_UNIT, USE_ROUND_TYPE, FIXED_POINT, ",
        "FIXED_RATE, MIN_PAY_PRICE, MIN_USE_POINT, MAX_USE_POINT, DC_RATE, DC_UNIT, DC_ROUND_TYPE, ",
        "DC_MIN_PAY_PRICE, MAX_DC_PRICE, MID_SHOP_ID, SUPERSTAR_ADD_SAVE_RATE, SUPERSTAR_ADD_USE_RATE, ",
        "SUPERSTAR_ADD_DC_RATE, ROYALSTAR_ADD_SAVE_RATE, ROYALSTAR_ADD_USE_RATE, ROYALSTAR_ADD_DC_RATE, ",
        "MAGICSTAR_ADD_SAVE_RATE, MAGICSTAR_ADD_USE_RATE, MAGICSTAR_ADD_DC_RATE, HAPPYSTAR_ADD_SAVE_RATE, ",
        "HAPPYSTAR_ADD_USE_RATE, HAPPYSTAR_ADD_DC_RATE, REG_USER, REG_DTM, CHG_USER, ",
        "CHG_DTM, SAVE_NOTICE",
        "from MW_MS_STAR_PAYMENT",
        "where COMP_ID = #{compId,jdbcType=VARCHAR}"
    })
    @ResultMap("ResultMapWithBLOBs")
    MwMsStarPayMent selectByPrimaryKey(String compId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_STAR_PAYMENT
     *
     * @mbggenerated Wed Jan 16 11:29:57 KST 2013
     */
    int updateByExampleSelective(@Param("record") MwMsStarPayMent record, @Param("example") MwMsStarPayMentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_STAR_PAYMENT
     *
     * @mbggenerated Wed Jan 16 11:29:57 KST 2013
     */
    int updateByExampleWithBLOBs(@Param("record") MwMsStarPayMent record, @Param("example") MwMsStarPayMentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_STAR_PAYMENT
     *
     * @mbggenerated Wed Jan 16 11:29:57 KST 2013
     */
    int updateByExample(@Param("record") MwMsStarPayMent record, @Param("example") MwMsStarPayMentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_STAR_PAYMENT
     *
     * @mbggenerated Wed Jan 16 11:29:57 KST 2013
     */
    int updateByPrimaryKeySelective(MwMsStarPayMent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_STAR_PAYMENT
     *
     * @mbggenerated Wed Jan 16 11:29:57 KST 2013
     */
    @Update({
        "update MW_MS_STAR_PAYMENT",
        "set STAR_POINT_SAVE = #{starPointSave,jdbcType=CHAR},",
          "STAR_POINT_USE = #{starPointUse,jdbcType=CHAR},",
          "STAR_POINT_DC = #{starPointDc,jdbcType=CHAR},",
          "SAVE_RATE_FIXED_YN = #{saveRateFixedYn,jdbcType=CHAR},",
          "CASH_SAVE_RATE = #{cashSaveRate,jdbcType=INTEGER},",
          "CARD_SAVE_RATE = #{cardSaveRate,jdbcType=INTEGER},",
          "COMP_SAVE_RATE = #{compSaveRate,jdbcType=INTEGER},",
          "DEBIT_SAVE_RATE = #{debitSaveRate,jdbcType=INTEGER},",
          "ETC_SAVE_RATE = #{etcSaveRate,jdbcType=INTEGER},",
          "SAVE_UNIT = #{saveUnit,jdbcType=CHAR},",
          "SAVE_ROUND_TYPE = #{saveRoundType,jdbcType=CHAR},",
          "DC_SAVE_PRICE_TYPE = #{dcSavePriceType,jdbcType=CHAR},",
          "SAVE_MIN_PAY_PRICE = #{saveMinPayPrice,jdbcType=INTEGER},",
          "SAVE_MAX_PAY_PRICE = #{saveMaxPayPrice,jdbcType=INTEGER},",
          "MAX_SAVE_POINT = #{maxSavePoint,jdbcType=INTEGER},",
          "POINT_USE_TYPE = #{pointUseType,jdbcType=CHAR},",
          "POINT_USE_UNIT = #{pointUseUnit,jdbcType=CHAR},",
          "USE_ROUND_TYPE = #{useRoundType,jdbcType=CHAR},",
          "FIXED_POINT = #{fixedPoint,jdbcType=INTEGER},",
          "FIXED_RATE = #{fixedRate,jdbcType=INTEGER},",
          "MIN_PAY_PRICE = #{minPayPrice,jdbcType=INTEGER},",
          "MIN_USE_POINT = #{minUsePoint,jdbcType=INTEGER},",
          "MAX_USE_POINT = #{maxUsePoint,jdbcType=INTEGER},",
          "DC_RATE = #{dcRate,jdbcType=INTEGER},",
          "DC_UNIT = #{dcUnit,jdbcType=CHAR},",
          "DC_ROUND_TYPE = #{dcRoundType,jdbcType=CHAR},",
          "DC_MIN_PAY_PRICE = #{dcMinPayPrice,jdbcType=INTEGER},",
          "MAX_DC_PRICE = #{maxDcPrice,jdbcType=INTEGER},",
          "MID_SHOP_ID = #{midShopId,jdbcType=VARCHAR},",
          "SUPERSTAR_ADD_SAVE_RATE = #{superstarAddSaveRate,jdbcType=INTEGER},",
          "SUPERSTAR_ADD_USE_RATE = #{superstarAddUseRate,jdbcType=INTEGER},",
          "SUPERSTAR_ADD_DC_RATE = #{superstarAddDcRate,jdbcType=INTEGER},",
          "ROYALSTAR_ADD_SAVE_RATE = #{royalstarAddSaveRate,jdbcType=INTEGER},",
          "ROYALSTAR_ADD_USE_RATE = #{royalstarAddUseRate,jdbcType=INTEGER},",
          "ROYALSTAR_ADD_DC_RATE = #{royalstarAddDcRate,jdbcType=INTEGER},",
          "MAGICSTAR_ADD_SAVE_RATE = #{magicstarAddSaveRate,jdbcType=INTEGER},",
          "MAGICSTAR_ADD_USE_RATE = #{magicstarAddUseRate,jdbcType=INTEGER},",
          "MAGICSTAR_ADD_DC_RATE = #{magicstarAddDcRate,jdbcType=INTEGER},",
          "HAPPYSTAR_ADD_SAVE_RATE = #{happystarAddSaveRate,jdbcType=INTEGER},",
          "HAPPYSTAR_ADD_USE_RATE = #{happystarAddUseRate,jdbcType=INTEGER},",
          "HAPPYSTAR_ADD_DC_RATE = #{happystarAddDcRate,jdbcType=INTEGER},",
          "REG_USER = #{regUser,jdbcType=VARCHAR},",
          "REG_DTM = #{regDtm,jdbcType=TIMESTAMP},",
          "CHG_USER = #{chgUser,jdbcType=VARCHAR},",
          "CHG_DTM = #{chgDtm,jdbcType=TIMESTAMP},",
          "SAVE_NOTICE = #{saveNotice,jdbcType=LONGVARCHAR}",
        "where COMP_ID = #{compId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKeyWithBLOBs(MwMsStarPayMent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MW_MS_STAR_PAYMENT
     *
     * @mbggenerated Wed Jan 16 11:29:57 KST 2013
     */
    @Update({
        "update MW_MS_STAR_PAYMENT",
        "set STAR_POINT_SAVE = #{starPointSave,jdbcType=CHAR},",
          "STAR_POINT_USE = #{starPointUse,jdbcType=CHAR},",
          "STAR_POINT_DC = #{starPointDc,jdbcType=CHAR},",
          "SAVE_RATE_FIXED_YN = #{saveRateFixedYn,jdbcType=CHAR},",
          "CASH_SAVE_RATE = #{cashSaveRate,jdbcType=INTEGER},",
          "CARD_SAVE_RATE = #{cardSaveRate,jdbcType=INTEGER},",
          "COMP_SAVE_RATE = #{compSaveRate,jdbcType=INTEGER},",
          "DEBIT_SAVE_RATE = #{debitSaveRate,jdbcType=INTEGER},",
          "ETC_SAVE_RATE = #{etcSaveRate,jdbcType=INTEGER},",
          "SAVE_UNIT = #{saveUnit,jdbcType=CHAR},",
          "SAVE_ROUND_TYPE = #{saveRoundType,jdbcType=CHAR},",
          "DC_SAVE_PRICE_TYPE = #{dcSavePriceType,jdbcType=CHAR},",
          "SAVE_MIN_PAY_PRICE = #{saveMinPayPrice,jdbcType=INTEGER},",
          "SAVE_MAX_PAY_PRICE = #{saveMaxPayPrice,jdbcType=INTEGER},",
          "MAX_SAVE_POINT = #{maxSavePoint,jdbcType=INTEGER},",
          "POINT_USE_TYPE = #{pointUseType,jdbcType=CHAR},",
          "POINT_USE_UNIT = #{pointUseUnit,jdbcType=CHAR},",
          "USE_ROUND_TYPE = #{useRoundType,jdbcType=CHAR},",
          "FIXED_POINT = #{fixedPoint,jdbcType=INTEGER},",
          "FIXED_RATE = #{fixedRate,jdbcType=INTEGER},",
          "MIN_PAY_PRICE = #{minPayPrice,jdbcType=INTEGER},",
          "MIN_USE_POINT = #{minUsePoint,jdbcType=INTEGER},",
          "MAX_USE_POINT = #{maxUsePoint,jdbcType=INTEGER},",
          "DC_RATE = #{dcRate,jdbcType=INTEGER},",
          "DC_UNIT = #{dcUnit,jdbcType=CHAR},",
          "DC_ROUND_TYPE = #{dcRoundType,jdbcType=CHAR},",
          "DC_MIN_PAY_PRICE = #{dcMinPayPrice,jdbcType=INTEGER},",
          "MAX_DC_PRICE = #{maxDcPrice,jdbcType=INTEGER},",
          "MID_SHOP_ID = #{midShopId,jdbcType=VARCHAR},",
          "SUPERSTAR_ADD_SAVE_RATE = #{superstarAddSaveRate,jdbcType=INTEGER},",
          "SUPERSTAR_ADD_USE_RATE = #{superstarAddUseRate,jdbcType=INTEGER},",
          "SUPERSTAR_ADD_DC_RATE = #{superstarAddDcRate,jdbcType=INTEGER},",
          "ROYALSTAR_ADD_SAVE_RATE = #{royalstarAddSaveRate,jdbcType=INTEGER},",
          "ROYALSTAR_ADD_USE_RATE = #{royalstarAddUseRate,jdbcType=INTEGER},",
          "ROYALSTAR_ADD_DC_RATE = #{royalstarAddDcRate,jdbcType=INTEGER},",
          "MAGICSTAR_ADD_SAVE_RATE = #{magicstarAddSaveRate,jdbcType=INTEGER},",
          "MAGICSTAR_ADD_USE_RATE = #{magicstarAddUseRate,jdbcType=INTEGER},",
          "MAGICSTAR_ADD_DC_RATE = #{magicstarAddDcRate,jdbcType=INTEGER},",
          "HAPPYSTAR_ADD_SAVE_RATE = #{happystarAddSaveRate,jdbcType=INTEGER},",
          "HAPPYSTAR_ADD_USE_RATE = #{happystarAddUseRate,jdbcType=INTEGER},",
          "HAPPYSTAR_ADD_DC_RATE = #{happystarAddDcRate,jdbcType=INTEGER},",
          "REG_USER = #{regUser,jdbcType=VARCHAR},",
          "REG_DTM = #{regDtm,jdbcType=TIMESTAMP},",
          "CHG_USER = #{chgUser,jdbcType=VARCHAR},",
          "CHG_DTM = #{chgDtm,jdbcType=TIMESTAMP}",
        "where COMP_ID = #{compId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(MwMsStarPayMent record);
}