package com.wallet.membership.mapper.custom;

import java.util.List;

import com.wallet.membership.model.custom.BulkCoupon;

public interface BulkCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memb_agree
     *
     * @mbggenerated Tue Aug 14 13:40:21 KST 2012
     */
    int countByExample(BulkCoupon bulkCoupon);
    int PopupcountByExample(BulkCoupon bulkCoupon);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memb_agree
     *
     * @mbggenerated Tue Aug 14 13:40:21 KST 2012
     */
   
    List<BulkCoupon> selectByExample(BulkCoupon bulkCoupon);  
    List<BulkCoupon> popupByExample(BulkCoupon bulkCoupon);  
    List<BulkCoupon> selectByMemberExample(BulkCoupon bulkCoupon);  
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memb_agree
     *
     * @mbggenerated Tue Aug 14 13:40:21 KST 2012
     */
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memb_agree
     *
     * @mbggenerated Tue Aug 14 13:40:21 KST 2012
     */
    int updateByMwCsCpnlistSelective(BulkCoupon bulkCoupon);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memb_agree
     *
     * @mbggenerated Tue Aug 14 13:40:21 KST 2012
     */
    int updateByMwCsBulkCpnSelective(BulkCoupon bulkCoupon);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memb_agree
     *
     * @mbggenerated Tue Aug 14 13:40:21 KST 2012
     */
    int updateByCpnlistSelective(BulkCoupon bulkCoupon);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memb_agree
     *
     * @mbggenerated Tue Aug 14 13:40:21 KST 2012
     */
    int deleteByMwCsCpnlistSelective(BulkCoupon bulkCoupon);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memb_agree
     *
     * @mbggenerated Tue Aug 14 13:40:21 KST 2012
     */
    int deleteByMwCsBulkCpnSelective(BulkCoupon bulkCoupon);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memb_agree
     *
     * @mbggenerated Tue Aug 14 13:40:21 KST 2012
     */
    int deleteByCpnlistSelective(BulkCoupon bulkCoupon);
}